### ISSUE TITLE
Npm exception on project open

### ISSUE THREAD

**Issue by Hubrus** [Microsoft/nodejstools#633] opened 2015-12-09 07:51 UTC
When opening a NodeJs project, the following exception appears in Npm output window:

```System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.NodejsTools.Npm.SPI.PackageJson.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.RootPackage.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.NodejsTools.Npm.SPI.PackageJson.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.RootPackage.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()<---```

![exception](https://cloud.githubusercontent.com/assets/2961512/11679525/5c3de3b6-9e5a-11e5-8cc1-f49ad32f8b98.PNG)

**Comment by billti** [comment] 2015-12-12 00:59
Are you opening an existing project with an existing package.json file in the root? It looks like there may be an entry in their causing issues (perhaps the 'name' field is missing based on the stack). If so, if you'd be able to provide a copy I can try and repro and fix the exception.

If not, can you detail for me if this is happening for multiple projects or just the one? Any further details or a project to repro with you could provide? Thanks.

**Comment by mousetraps** [comment] 2015-12-14 22:23
On a side note, we should also revisit our error handling here and stop dumping stack traces out. Perhaps an entry to the diagnostics window would be good now that we have it.

**Comment by Hubrus** [comment] 2015-12-18 12:55
This is how my packages.json looks:
```
{
  "name": "es6poc",
  "version": "1.0.0",
  "description": "ES6 PoC",
  "main": "src/js/entry.js",
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "testFileExtensions": ["es6", "js"],
    "moduleFileExtensions": ["js", "json", "es6"]
  },
  "author": "Vlad",
  "license": "Apache-2.0",
  "devDependencies": {
    "babel": "^6.3.13",
	"babel-jest": "*",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babelify": "^7.2.0",
    "bootstrap": "^3.3.6",
    "bower": "^1.6.9",
    "browserify": "^12.0.1",
    "flux": "^2.1.1",
    "gulp": "^3.9.0",
    "gulp-inject": "^3.0.0",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^1.5.1",
    "jest-cli": "^0.8.2",
    "keymirror": "^0.1.1",
    "ramda": "^0.18.0",
    "react": "^0.14.3",
    "react-addons-linked-state-mixin": "^0.14.3",
    "react-dom": "^0.14.3",
    "underscore": "^1.8.3",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.6.1"
  },
  "dependencies": {
    "babel": "^6.3.13"
  }
}
```

**Comment by dmccaffery** [comment] 2016-01-04 07:52
@Hubrus Did you happen to install NPM v3 and change the path in "External Web Tools" to use yours? I just hit this bug as well, and it seems to happen when attempting to parse global packages -- could be caused by a variance in how NPM lists global packages in v3. I'm trying to isolate this myself. I did attempt to reset package.json to defaults and the error is still occurring.

**Comment by mousetraps** [comment] 2016-01-04 15:41
@hubrus Also please try upgrading to the latest release - I notice from the screenshot that you are on a version that's at least pre-July Http://github.com/Microsoft/nodejstools/releases

@dmccaffery are you using node tools for VS or is it another project type like asp.net or Cordova? The external web tools choice shouldn't affect node tools at all.

**Comment by dmccaffery** [comment] 2016-01-08 21:49
@mousetraps Not using node tools; just an asp.net project with a package.json -- I assumed that there was some shared underpinnings between them since the error I am getting is identical.

**Comment by mousetraps** [comment] 2016-01-10 23:39
@dmccaffery The npm component is indeed shared, but the version currently available in VS at the moment is currently about a year old, and doesn't have any of our recent fixes. Additionally, there remain some [inconsistencies](https://github.com/Microsoft/nodejstools/issues/534#issuecomment-147966006) wrt settings.

The delay in pushing the latest bits is partly because we have yet to establish a formal code-share and build process between our teams, so it's more of a hassle to push updates, and partly because NTVS underwent a bunch of churn for npm v3 (#386) and we weren't comfortable pushing these changes into VS-proper without some extra time to iterate and respond to issues on our end. 

In any case, could you try reproducing the issue with the latest bits of NTVS (you'll have to use a node project)? Then I can take a look. Otherwise it should be fixed when we get around to pushing the latest batch of updates into VS.

**Comment by dmccaffery** [comment] 2016-01-14 02:42
@mousetraps I'd be happy to take a look at it and report back, but I'm sure its fine. It was an assumption made on my part, and I'm thankful for all the effort you guys put in. :)

**Comment by mousetraps** [comment] 2016-01-23 04:51
Chatted with the Web Tools team today, and this issue should be fixed in the next VS Update. Closing as external.

**Closed by mousetraps** 2016-01-23 04:51 UTC
Labels: bug, npm-integration
