### ISSUE TITLE
Ability to run the Node.js debugger inline, rather than in its own console window?

### ISSUE THREAD

**Issue by Josh1billion** [Microsoft/nodejstools#1172] opened 2016-07-27 20:59 UTC
Having Node.js pop up in its own console window is a moderate inconvenience.

Is it possible to display that output inside of Visual Studio instead?  If not, does there exist any workaround to keep the window minimized?

Ideally, I'd like to be able to hit F5 to debug, and then immediately Alt+Tab to an already-open browser window for testing, but the console window gets in the way.

**Comment by mjbvz** [comment] 2016-07-27 21:15
This would be a great option to add to NTVS. I think we are already tracking this with issue #149

That issue is marked as up-for-grabs, so anyone is free to make a contribution and improve the experience here. I don't think there is a good workaround currently.

Closing as duplicate of #149

**Closed by mjbvz** 2016-07-27 21:15 UTC
