### ISSUE TITLE
When debugging a node.js program in VS2013 ? where are the node.js codes ?

### ISSUE THREAD

**Issue by sadeghitk** [Microsoft/nodejstools#816] opened 2016-04-01 23:18 UTC
I started with the simple test program, I stepped in the node.js codes. It allows me to look at the main LIB codes. They are locked, and I cannot open main folder for them. Where are they loaded at ? How I can locate the location ? is it setup in the VS2013 ? 

Terry

**Comment by mjbvz** [comment] 2016-04-01 23:40
Can you please clarify what is wrong by providing a list of repo steps and the expected behavior vs. the actual behavior.

**Comment by sadeghitk** [comment] 2016-04-01 23:50
1.       Created Sample project.

 

var http = require('http');

var port = process.env.port || 1337;

http.createServer(function (req, res) {

    res.writeHead(200, { 'Content-Type': 'text/plain' });

    res.end('Hello World\n');

}).listen(port);

 

2.       Run in DEBUG mode.

3.       Break point on line 3.

4.       Did F11 to step in the Node.js code, _http_server.js

 



 

5.       Where are these source codes ? _http_server.js

 

Thanks,

 

Terry Sadeghi
dataGate
281-698-8031  Ext. 200

This E-mail message and any attachments may contain legally privileged, confidential or proprietary information. If you are not the intended recipient's, or the employee or agent responsible for delivery of this message to the intended recipient's, you are hereby notified that any dissemination, distribution or copying of this E-mail message is strictly prohibited. If you have received this message in error, please immediately notify the sender and delete this E-mail message from your computer

**Comment by mjbvz** [comment] 2016-04-02 00:16
Yes, it seems you are stepping into one of the core Node modules (`http` in this case). That's why they are locked and do not have a specific location on disk (I believe the files are coming from the debugger, but I don't know too much about that area).

Debugging into these modules can be helpful sometimes to see what a program is doing, but you would never really want to edit them. Check out the Node.js source for their source code.

Closing since this is the expected behavior.

**Closed by mjbvz** 2016-04-02 00:16 UTC
Labels: need-more-info

**Comment by sadeghitk** [comment] 2016-04-02 17:40
Thanks for the response Matt. I have already have the code from the Node.js. I am trying to find out where the VS2013 gets it from? is it saved on the local workstation and where ? Does it use the version of the node.js that is installed on the computer or uses the latest source ? 

Thanks, Terry

**Comment by mjbvz** [comment] 2016-04-02 18:24
When you debug into this code, you are stepping into the files for whatever version of node is running. 

I'm not personally familiar how this part of the debugger works, but I suspect the source code is acquired by the debugger from the runtime: https://github.com/v8/v8/wiki/Debugging%20Protocol#request-scripts

Checkout the node source if you want to view the complete implementation.
