### ISSUE TITLE
Locals in debugger aren't displayed properly

### ISSUE THREAD

**Issue by pps83** [Microsoft/nodejstools#1242] opened 2016-08-31 14:54 UTC
I'm using latest VS2015 with latest NTVS (1.2.40726.00)
When I debug in VS it doesn't seem to work OK: [screenshot](http://i.imgur.com/7B1G8XH.png)
In my case I wrote a string into node's Writable stream and there is default encoding param which gets set to utf8 (as shown when hovering mouse over the var), however, same variable in locals window doesn't get updated and shows old value.
Here's the code to reproduce (step into write and you'll see that):

```
    var fl = fs.createWriteStream('test.txt');
    fl.write('A');
```

The other point about debugging: it's kind of common to expect that in VS you always can see last return value in Autos window. Now, I don't see anything in Autos window, it's empty.

**Comment by mjbvz** [comment] 2016-08-31 18:35
Thanks. I confirmed the first problem and will investigate. Tested on Node 6.4

---

For the return value auto, do you mean this C# feature: https://blogs.msdn.microsoft.com/visualstudioalm/2013/06/27/seeing-function-return-values-in-the-visual-studio-2013-debugger/ 

Please open another issue so we can track that separately, along with a bit more description or references so we know specifically what is being requested.

Thanks.

**Comment by mjbvz** [comment] 2016-08-31 18:57
Quick update: here's the node debugger communications from setting a breakpoint on the last line of `write` and then continuing to it from the main program:

```
[18:48:15.2039336] NodeDebugger Called ClearStepping
[18:48:15.2039336] NodeDebugger Called Resume
[18:48:15.2039336] DebuggerConnection: Request: {"command":"continue","seq":17,"type":"request","arguments":null}
[18:48:15.2059341] DebuggerConnection: Response: {"seq":22,"request_seq":17,"type":"response","command":"continue","success":true,"running":true}
[18:48:15.2129423] DebuggerConnection: Response: {"seq":23,"type":"event","event":"break","body":{"invocationText":"#<WriteStream>.write(chunk=A, encoding=undefined, cb=undefined)","sourceLine":222,"sourceColumn":2,"sourceLineText":"  return ret;","script":{"id":55,"name":"_stream_writable.js","lineOffset":0,"columnOffset":0,"lineCount":532},"breakpoints":[3]}}
[18:48:15.2163185] DebuggerConnection: Request: {"command":"backtrace","seq":18,"type":"request","arguments":{"fromFrame":0,"toFrame":2147483647,"inlineRefs":true}}
[18:48:15.2343164] DebuggerConnection: Response: {"seq":24,"request_seq":18,"type":"response","command":"backtrace","success":true,"body":{"fromFrame":0,"toFrame":10,"totalFrames":10,"frames":[{"type":"frame","index":0,"receiver":{"ref":1,"type":"object","className":"Object"},"func":{"ref":0,"type":"function","name":"","inferredName":"Writable.write","scriptId":55},"script":{"ref":9},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"chunk","value":{"ref":7,"type":"string","value":"A"}},{"name":"encoding","value":{"ref":3,"type":"undefined"}},{"name":"cb","value":{"ref":3,"type":"undefined"}}],"locals":[{"name":"state","value":{"ref":10,"type":"object","className":"Object"}},{"name":"ret","value":{"ref":11,"type":"boolean","value":true}}],"position":6772,"line":222,"column":2,"sourceLineText":"  return ret;","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#00 #<WriteStream>.write(chunk=A, encoding=undefined, cb=undefined) _stream_writable.js line 223 column 3 (position 6773)"},{"type":"frame","index":1,"receiver":{"ref":12,"type":"object","className":"Object"},"func":{"ref":13,"type":"function","name":"","inferredName":"","scriptId":62},"script":{"ref":15},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"exports","value":{"ref":12,"type":"object","className":"Object"}},{"name":"require","value":{"ref":16,"type":"function","name":"require","inferredName":"","scriptId":49}},{"name":"module","value":{"ref":19,"type":"object","className":"Object"}},{"name":"__filename","value":{"ref":20,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}},{"name":"__dirname","value":{"ref":21,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1"}}],"locals":[{"name":"fs","value":{"ref":22,"type":"object","className":"Object"}},{"name":"fl","value":{"ref":1,"type":"object","className":"Object"}}],"position":149,"line":3,"column":3,"sourceLineText":"fl.write('A');","scopes":[{"type":1,"index":0},{"type":6,"index":1},{"type":0,"index":2}],"text":"#01 #<Object>.[anonymous](exports=#<Object>, require=function require(path) {\n    try {\n      exports.requireDepth += 1;\n      return self.require(path);\n    } finally {\n      exports.requireDepth -= 1;\n    }\n  }, module=#<Module>, __filename=C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89), __dirname=C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1) C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\server.js line 4 column 4 (position 150)"},{"type":"frame","index":2,"receiver":{"ref":19,"type":"object","className":"Object"},"func":{"ref":27,"type":"function","name":"","inferredName":"Module._compile","scriptId":48},"script":{"ref":29},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"content","value":{"ref":30,"type":"string","value":"var fs = require('fs');\r\nvar fl = fs.createWriteStream('out.txt');\r\nfl.write('A'... (length: 98)"}},{"name":"filename","value":{"ref":20,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}}],"locals":[{"name":"contLen","value":{"ref":31,"type":"object","className":"Object"}},{"name":"i","value":{"ref":32,"type":"number","value":98}},{"name":"code","value":{"ref":3,"type":"undefined"}},{"name":"wrapper","value":{"ref":3,"type":"undefined"}},{"name":"compiledWrapper","value":{"ref":33,"type":"string","value":"(function (exports, require, module, __filename, __dirname) { var fs = require('... (length: 164)"}},{"name":"dirname","value":{"ref":13,"type":"function","name":"","inferredName":"","scriptId":62}},{"name":"require","value":{"ref":21,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1"}},{"name":"args","value":{"ref":16,"type":"function","name":"require","inferredName":"","scriptId":49}},{"name":"depth","value":{"ref":34,"type":"object","className":"Array"}},{"name":"result","value":{"ref":35,"type":"number","value":0}}],"position":15656,"line":540,"column":31,"sourceLineText":"  var result = compiledWrapper.apply(this.exports, args);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#02 #<Module>._compile(content=var fs = require('fs');\r\nvar fl = fs.createWriteStream('out.txt');\r\nfl.write('A'... (length: 98), filename=C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)) module.js line 541 column 32 (position 15657)"},{"type":"frame","index":3,"receiver":{"ref":37,"type":"object","className":"Object"},"func":{"ref":38,"type":"function","name":"","inferredName":"Module._extensions..js","scriptId":48},"script":{"ref":29},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"module","value":{"ref":19,"type":"object","className":"Object"}},{"name":"filename","value":{"ref":20,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}}],"locals":[{"name":"content","value":{"ref":39,"type":"string","value":"﻿var fs = require('fs');\r\nvar fl = fs.createWriteStream('out.txt');\r\nfl.write('A... (length: 99)"}}],"position":15888,"line":549,"column":9,"sourceLineText":"  module._compile(internalModule.stripBOM(content), filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#03 #<Object>..js(module=#<Module>, filename=C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)) module.js line 550 column 10 (position 15889)"},{"type":"frame","index":4,"receiver":{"ref":19,"type":"object","className":"Object"},"func":{"ref":40,"type":"function","name":"","inferredName":"Module.load","scriptId":48},"script":{"ref":29},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"filename","value":{"ref":20,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}}],"locals":[{"name":"extension","value":{"ref":41,"type":"string","value":".js"}}],"position":13116,"line":457,"column":31,"sourceLineText":"  Module._extensions[extension](this, filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#04 #<Module>.load(filename=C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)) module.js line 458 column 32 (position 13117)"},{"type":"frame","index":5,"receiver":{"ref":3,"type":"undefined"},"func":{"ref":42,"type":"function","name":"tryModuleLoad","inferredName":"","scriptId":48},"script":{"ref":29},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"module","value":{"ref":19,"type":"object","className":"Object"}},{"name":"filename","value":{"ref":20,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}}],"locals":[{"name":"threw","value":{"ref":11,"type":"boolean","value":true}}],"position":11986,"line":416,"column":11,"sourceLineText":"    module.load(filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#05 undefined.tryModuleLoad(module=#<Module>, filename=C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)) module.js line 417 column 12 (position 11987)"},{"type":"frame","index":6,"receiver":{"ref":26,"type":"function","name":"Module","inferredName":"","scriptId":48},"func":{"ref":43,"type":"function","name":"","inferredName":"Module._load","scriptId":48},"script":{"ref":29},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"request","value":{"ref":44,"type":"string","value":"c:\\users\\matb\\documents\\visual studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}},{"name":"parent","value":{"ref":25,"type":"null","value":null}},{"name":"isMain","value":{"ref":11,"type":"boolean","value":true}}],"locals":[{"name":"filename","value":{"ref":20,"type":"string","value":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89)"}},{"name":"cachedModule","value":{"ref":3,"type":"undefined"}},{"name":"module","value":{"ref":19,"type":"object","className":"Object"}}],"position":11841,"line":408,"column":2,"sourceLineText":"  tryModuleLoad(module, filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#06 function Module(id, parent) {\n  this.id = id;\n  this.exports = {};\n  this.parent = parent;\n  if (parent && parent.children) {\n    parent.children.push(this);\n  }\n\n  this.filename = null;\n  this.loaded = false;\n  this.children = [];\n}._load(request=c:\\users\\matb\\documents\\visual studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\... (length: 89), parent=null, isMain=true) module.js line 409 column 3 (position 11842)"},{"type":"frame","index":7,"receiver":{"ref":46,"type":"object","className":"Object"},"func":{"ref":47,"type":"function","name":"","inferredName":"Module.runMain","scriptId":48},"script":{"ref":29},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[],"locals":[],"position":16524,"line":574,"column":9,"sourceLineText":"  Module._load(process.argv[1], null, true);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#07 #<Timeout>._onTimeout() module.js line 575 column 10 (position 16525)"},{"type":"frame","index":8,"receiver":{"ref":3,"type":"undefined"},"func":{"ref":50,"type":"function","name":"tryOnTimeout","inferredName":"","scriptId":39},"script":{"ref":52},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"timer","value":{"ref":46,"type":"object","className":"Object"}},{"name":"list","value":{"ref":53,"type":"object","className":"Object"}}],"locals":[{"name":"threw","value":{"ref":3,"type":"undefined"}}],"position":7722,"line":223,"column":10,"sourceLineText":"    timer._onTimeout();","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#08 undefined.tryOnTimeout(timer=#<Timeout>, list=#<TimersList>) timers.js line 224 column 11 (position 7723)"},{"type":"frame","index":9,"receiver":{"ref":55,"type":"object","className":"Timer"},"func":{"ref":56,"type":"function","name":"listOnTimeout","inferredName":"","scriptId":39},"script":{"ref":52},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[],"locals":[{"name":"list","value":{"ref":53,"type":"object","className":"Object"}},{"name":"msecs","value":{"ref":57,"type":"number","value":50}},{"name":"now","value":{"ref":58,"type":"number","value":414}},{"name":"diff","value":{"ref":59,"type":"number","value":56}},{"name":"timer","value":{"ref":46,"type":"object","className":"Object"}},{"name":"domain","value":{"ref":3,"type":"undefined"}}],"position":7049,"line":197,"column":4,"sourceLineText":"    tryOnTimeout(timer, list);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":6,"index":2},{"type":0,"index":3}],"text":"#09 #<Timer>[0](aka listOnTimeout)() timers.js line 198 column 5 (position 7050)"}]},"refs":[{"handle":9,"type":"script","name":"_stream_writable.js","id":55,"lineOffset":0,"columnOffset":0,"lineCount":532,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // A bit simpler t","sourceLength":14368,"scriptType":2,"compilationType":0,"context":{"ref":8},"text":"_stream_writable.js (lines: 532)"},{"handle":15,"type":"script","name":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\server.js","id":62,"lineOffset":0,"columnOffset":0,"lineCount":5,"sourceStart":"(function (exports, require, module, __filename, __dirname) { var fs = require('","sourceLength":164,"scriptType":2,"compilationType":0,"context":{"ref":14},"text":"C:\\Users\\matb\\Documents\\Visual Studio 2015\\Projects\\NodejsWebApp1\\NodejsWebApp1\\server.js (lines: 5)"},{"handle":29,"type":"script","name":"module.js","id":48,"lineOffset":0,"columnOffset":0,"lineCount":641,"sourceStart":"(function (exports, require, module, __filename, __dirname) { 'use strict';\n\ncon","sourceLength":18185,"scriptType":2,"compilationType":0,"context":{"ref":28},"text":"module.js (lines: 641)"},{"handle":52,"type":"script","name":"timers.js","id":39,"lineOffset":0,"columnOffset":0,"lineCount":649,"sourceStart":"(function (exports, require, module, __filename, __dirname) { 'use strict';\n\ncon","sourceLength":18103,"scriptType":2,"compilationType":0,"context":{"ref":51},"text":"timers.js (lines: 649)"}],"running":false}
[18:48:15.2503186] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7BreakpointEvent (501C1E21-C557-48B8-BA30-A1EAB0BC4A74)
[18:48:15.2593221] AD7Engine Called EnumThreads
[18:48:15.7031559] AD7Engine Called EnumThreads
[18:48:16.9891357] NodeDebugger Called Execute Text Async
```

For us, I believe the important part is the `backtrace` response which contains an argument: 

```
{"name":"encoding","value":{"ref":3,"type":"undefined"}}
```

Which seems to be why we show `undefined` as the value in the autos.

If you then double click on the actual `encoding` entry in the autos window, you see the correct value:

```
[18:48:16.9901320] DebuggerConnection: Request: {"command":"evaluate","seq":19,"type":"request","arguments":{"expression":"encoding","frame":0,"global":false,"disable_break":true,"maxStringLength":-1}}
[18:48:16.9931343] DebuggerConnection: Response: {"seq":25,"request_seq":19,"type":"response","command":"evaluate","success":true,"body":{"handle":64,"type":"string","value":"utf8","length":4,"text":"utf8"},"refs":[],"running":false}
```

`"value":"utf8"` is returned and shown in the ui while editing the value.

`evaluate` is also the command we use on hover to get the value.

**Comment by mjbvz** [comment] 2016-08-31 19:00
Here's a simple repo for the problem:

```js
function f(a) {
    a = 10;
    debugger;
}
f();
```

![image](https://cloud.githubusercontent.com/assets/12821956/18142431/5dcdd1e8-6f72-11e6-9fa2-0bded09525d9.png)

It has something to do with arguments. Normal local value do not show this in my testing

**Comment by mjbvz** [comment] 2016-08-31 21:12
Looks like we should probably be using the [v8 `scope` command](https://github.com/v8/v8/wiki/Debugging%20Protocol#request-scope) instead of `backtrace` for this. The behavior of `backtrace` is not too well documented, but it does seem to be designed to return the value of the `arguments` from invocation, not from the current point in execution.

Marking this as up for grabs for anyone who wants to look into a fix. `PerformBacktraceAsync` is a good starting point: https://github.com/Microsoft/nodejstools/blob/0896944ff388243674a519834c052e6ef5f68327/Nodejs/Product/Nodejs/Debugger/NodeDebugger.cs#L809

**Comment by paulvanbrenk** [comment] 2018-05-04 01:00
Closing as we're not investing in Node 6 support, unless it's a critical issue.

**Closed by paulvanbrenk** 2018-05-04 01:00 UTC
Labels: bug, debugging, up-for-grabs
