### ISSUE TITLE
Should include completions on "this" inside of callback function

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#194] opened 2015-06-09 04:16 UTC
```javascript
foo.on('bar', function () {
        this.<doesn't show completions on foo unless defined in scope of this function>
});
```

**Comment by mjbvz** [comment] 2016-04-05 00:49
With ES6 Intellisense preview, we at least get some generic completions for various names in scope.

The problem is not an easy one to solve in the general case, because it is hard to know how the callback will be invoked. For cases where we do have typings, [Typescript may support annotating the `this` argument](https://github.com/Microsoft/TypeScript/issues/3694) but I do not think this is supported yet.

**Closed by mjbvz** 2016-04-05 00:49 UTC
Labels: feature, intellisense
