### ISSUE TITLE
ntvs tool fails after update nuget package manager for VS 15

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#842] opened 2016-04-11 04:40 UTC
![image](https://cloud.githubusercontent.com/assets/4515120/14416976/03a474de-ffeb-11e5-9268-23281bc7bd8d.png)

**Comment by alanpurple** [comment] 2016-04-11 08:44
I had to "repair" visual studio 15, and it's fine now

**Comment by mjbvz** [comment] 2016-04-11 18:14
Glad you were able to find a fix. Did you notice anything that triggered the problem in the first place?

Closing this issue. Please let us know if you start hitting it again or come up with a reliable repo for the problem.

**Comment by alanpurple** [comment] 2016-04-11 23:58
@mjbvz It's just a workaround, I just uninstalled nuget package manager and repaired installation

This is a problem of compatibility between ntvs tool and nuget extension

https://www.visualstudiogallery.msdn.microsoft.com/f37ad94a-b840-4145-bcc1-07442906689b

**Comment by mjbvz** [comment] 2016-04-12 01:00
@alanpurple Ok, reopening. From the original report it was not clear if the machine had just gotten into a bad state, but it seems like this is a reproducible issue that we can investigate. 

Are any other steps required to trigger this behavior, or do you just have to install the NuGet package manager extension and boot VS15?

**Comment by alanpurple** [comment] 2016-04-12 01:01
@mjbvz  as you said, just install nuget package manager extension and restart VS15

**Comment by mjbvz** [comment] 2016-06-09 23:46
Sorry for the delay getting back on this one. I was unable to repo the problem.

Also, I thought that the nuget package manager extension also was automatically with VS15? Which version or configuration of VS15 were you using? Understanding that may help get a repo.

**Comment by mousetraps** [comment] 2016-06-13 23:22
Looks like a MEF composition issue. devenv /setup should fix issues like this, but let us know if you're running into it consistently. Thanks!

**Closed by mousetraps** 2016-06-13 23:22 UTC
Labels: crash-or-hang
