### ISSUE TITLE
error when uninstalling npm package in Visual Studio

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/nodejstools#1163] opened 2016-07-25 09:24 UTC
I am using Visual Studio 2015 Community Update 3. I have installed Node.js Tools 1.1. Node version is v0.12.2. Everything that I have installed are latest stable version. I have installed `typings` npm package using NTVS. I am uninstalling `typings` using NTVS using context menu that I have installed locally as told in previous step. The error I am getting while uninstalling is shown below:

`====Executing command 'npm uninstall typings --save'====

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "uninstall" "typings" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! Cannot read property 'del' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     E:\SolutionName\SolutionName\npm-debug.log

====npm command completed with exit code 1====
`

Why isn't it getting uninstalled? What is the workaround?

Snapshot is attached for reference:
![2](https://cloud.githubusercontent.com/assets/16834561/17096585/b0272cb8-5277-11e6-99ca-0409a602b52e.png)

**Comment by mjbvz** [comment] 2016-07-25 19:59
Thanks for reporting this. 

I suspect that it may be a npm/node issue. Can you please try installing and uninstalling typings using the command line:

```bash
$ cd my_project
$ npm --version # should be 2.7.4
$ npm install  typings --save
$ npm uninstall typings --save 
```

This will help us understand if this is a npm/node error or an NTVS error.

Thanks.

**Comment by ranjan-ranjan** [comment] 2016-07-26 01:31
node version is 2.7.4 as given in issue earlier.

Other results are as follows:

```
E:\SolutionName\SolutionName\node_modules\typings>npm install typings --save
npm WARN install Refusing to install typings as a dependency of itself

E:\SolutionName\SolutionName\node_modules\typings>npm uninstall typings --save
npm WARN uninstall not installed in E:\SolutionName\SolutionName\node_modules\typings\node_modules: "typings"
```

**Comment by ranjan-ranjan** [comment] 2016-07-26 08:11
I have deleted `"typings": "^1.3.2"` from `package.json`. And repeated the same steps, i.e., uninstalling `typings` using context menu from VS. The message in status bar is `npm uninstall typings --save successfully completed`. Snapshot is attached for reference.
![2](https://cloud.githubusercontent.com/assets/16834561/17130548/ae2e11c8-5336-11e6-9ab1-cf716e2aa23e.png)

**Comment by ranjan-ranjan** [comment] 2016-07-26 08:16
Now, when I deleted `typings` folder from `E:\SolutionName\SolutionName\node_modules`, the npm package `typings` is gone. Snapshot is attached for reference.
![1](https://cloud.githubusercontent.com/assets/16834561/17130669/607ebdbe-5337-11e6-99ec-d2a3d7496ca2.png)

**Comment by ranjan-ranjan** [comment] 2016-07-26 09:10
Updating the installed npm package using context menu in VS also gives similar errors as given in https://github.com/Microsoft/nodejstools/issues/1163#issuecomment-235193304.

What role does `package.json` play in all these steps here?

**Comment by mjbvz** [comment] 2016-07-26 17:36
In your manual run of the npm commands, it doesn't look like typings was ever installed. Try creating an test folder and trying this again:

```bash
$ cd my_temp_test_folder
$ npm init -y # create package.json
$ npm install  typings --save
$ npm uninstall typings --save 
```

The default behavior of NTVS is to install packages using `--save`. This updates the `package.json` file to list the installed package as a dependency. `uninstall --save` removes the package from the `package.json`.

**Comment by ranjan-ranjan** [comment] 2016-07-27 05:53
Here is the output of npm command.![1](https://cloud.githubusercontent.com/assets/16834561/17165205/6b7836ea-53ec-11e6-8ae7-e5cd1e04e0c3.png)

**Comment by mjbvz** [comment] 2016-07-27 17:11
@ranjan-ranjan I just want to see if you can install and uninstall this package using npm directly so we can determine if NTVS or npm is the root cause here.

Please create a test project folder and share the output of these commands:

```bash
$ mkdir my_temp_test_folder
$ cd my_temp_test_folder
$ npm init -y # create package.json
$ npm install  typings --save
$ npm uninstall typings --save
```

**Comment by ranjan-ranjan** [comment] 2016-07-28 18:41
Output:

C:\>cd my_temp_test_folder

C:\my_temp_test_folder>npm init -y # create package.json
author: ranjan
Wrote to C:\my_temp_test_folder\package.json:

{
  "name": "my_temp_test_folder",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "ranjan",
  "license": "ISC"
}



C:\my_temp_test_folder>npm install typings --save
npm WARN package.json my_temp_test_folder@1.0.0 No description
npm WARN package.json my_temp_test_folder@1.0.0 No repository field.
npm WARN package.json my_temp_test_folder@1.0.0 No README data
typings@1.3.2 node_modules\typings
├── listify@1.0.0
├── xtend@4.0.1
├── archy@1.0.0
├── wordwrap@1.0.0
├── minimist@1.2.0
├── any-promise@1.3.0
├── bluebird@3.4.1
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── columnify@1.5.4 (strip-ansi@3.0.1, wcwidth@1.0.1)
├── update-notifier@1.0.2 (is-npm@1.0.0, lazy-req@1.1.0, xdg-basedir@2.0.0, semver-diff@2.1.0, boxen@0.6.0, configstore@2.0.0, latest-version@2.0.0)
└── typings-core@1.4.0 (array-uniq@1.0.3, thenify@3.2.0, zip-object@0.1.0, popsicle-status@2.0.0, popsicle-retry@3.2.1, promise-finally@2.2.1, throat@3.0.0, graceful-fs@4.1.5, lockfile@1.0.1, string-template@1.0.0, sort-keys@1.1.2, strip-bom@2.0.0, make-error-cause@1.2.1, has@1.0.1, mkdirp@0.5.1, rc@1.1.6, typescript@1.8.7, debug@2.2.0, object.pick@1.1.2, parse-json@2.2.0, invariant@2.2.1, touch@1.0.0, configstore@2.0.0, detect-indent@4.0.0, is-absolute@0.2.5, popsicle-proxy-agent@3.0.0, popsicle@8.0.2, rimraf@2.5.4)

C:\my_temp_test_folder>npm uninstall typings --save
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "uninstall" "typings" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'del' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\my_temp_test_folder\npm-debug.log

C:\my_temp_test_folder>

**Comment by mjbvz** [comment] 2016-07-28 19:24
Closing as external since this error occurs with just regular NPM and is not an NTVS issue.

The root cause could be either typings or npm itself. You can also try upgrading node versions, since I don't see this error on more recent npm versions.

**Closed by mjbvz** 2016-07-28 19:24 UTC
Labels: external

**Comment by ranjan-ranjan** [comment] 2016-08-12 10:47
solved in recent npm
