### ISSUE TITLE
npm install package in a blank nodejs project in Visual Studio 2017 Throwing exception.

### ISSUE THREAD

**Issue by singsuyash** [Microsoft/nodejstools#1498] opened 2017-03-14 06:33 UTC
I tried to right click on NTVS "npm" icon in solution explorer and install package, here is what happens
##### Expected Behavior

Should install package, and show the package manager UI properly, but the UI doesn't show anything and even on searching for packages(any package) it says not found.

##### Actual Behavior
Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\suyashs\AppData\Local\Microsoft\Node.js Tools\NpmCache\95371fe7-4938-438b-8f41-c5bec70d4ef6\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Downloaded 1MB of the package list (85MB total)
...
Downloaded 84MB of the package list (85MB total)
Download complete - updating database
Reading 88174592 bytes from C:\Users\suyashs\AppData\Local\Microsoft\Node.js Tools\NpmCache\95371fe7-4938-438b-8f41-c5bec70d4ef6\all_packages.json (3/14/2017 11:58:39 AM)
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'grunt-cssshrink.description', line 1, position 88102702.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackage(JsonTextReader jsonReader, NodeModuleBuilder builder)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\suyashs\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting 95371fe7-4938-438b-8f41-c5bec70d4ef6
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'grunt-cssshrink.description', line 1, position 88102702.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackage(JsonTextReader jsonReader, NodeModuleBuilder builder)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()
 

- NTVS Version: 1.3.0.4
- Visual Studio Version:  2017
- Node.js Version: 6.10.0

##### Steps to Reproduce
1.  Blank solution for node js project
2.  try to install a package

**Comment by stakx** [comment] 2017-03-16 18:45
Same here, though with slightly different tool versions (Node.js 7.7.1, npm 4.1.2, Visual Studio 2015 Update 3, NTVS 1.2), and in my case, only 11 MB were downloaded. I manually inspected the downloaded  `all_packages.json` file and the JSON was abruptly cut off. I guess that the downloaded data might not get fully flushed to disk, resulting in the last few bytes missing.

**Comment by billti** [comment] 2017-03-17 23:14
Duplicate of #1481. The issue is at the NPM end currently. We plan to move away from this registry endpoint, but that's not a quick fix.

**Closed by billti** 2017-03-17 23:14 UTC
Labels: duplicate
