### ISSUE TITLE
Set as Node.js Startup File - package.json

### ISSUE THREAD

**Issue by MaciejHanajczyk** [Microsoft/nodejstools#658] opened 2016-01-08 11:53 UTC
When setting a file as a Node.js Startup file the field 'main' in package.json should be edited to this selected file name.

**Comment by mousetraps** [comment] 2016-01-11 00:00
Closing as a dupe of #7, so follow that issue for further updates, but agreed. We're planning to overhaul our project system to move towards more of a folder / file-based model and this is one of the things that we'll fix in the process.

**Closed by mousetraps** 2016-01-11 00:00 UTC
