### ISSUE TITLE
TypeScript: Go to definition fails to work in Visual Studio 2015

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#18] opened 2015-04-02 10:43 UTC
This issue was logged on the TypeScript project: Microsoft/TypeScript#1210.

But turns out to be an NTVS issue. See https://github.com/Microsoft/TypeScript/issues/1210#issuecomment-67249740

**Comment by mousetraps** [comment] 2015-04-07 06:42
Thanks, I'll close the duplicate Codeplex issue. We're focusing on VS2015 for our next milestone, so this issue will definitely make the cut :-)

**Comment by mousetraps** [comment] 2015-04-21 18:24
According to the linked thread, this only occurs when you are working with two projects, and there is a dot in the filepath.

The problem isn't exactly in the open document code, but rather that the VS item id is not set properly in this scenario unless the document is opened first.

Is this the only time F12 is not working?

**Comment by NoelAbrahams** [comment] 2015-04-21 18:28
@mousetraps, yes, the F12 fails when there's a dot in the file path, but works correctly otherwise.

The F12 only fails to work in NTVS projects. We also have plain TypeScript project, and they don't have this problem.

**Comment by mousetraps** [comment] 2015-04-27 15:21
Working together with TS team to resolve this sometime after BUILD. The issue occurs in the OpenDocument code, but it is the arguments passed in that are problematic, not the code itself. One possibility is that TS is making some assumptions about the Project System that do not apply to NTVS, which results in OpenItem being passed an invalid projectHierarchy and vsitemid.

**Comment by NoelAbrahams** [comment] 2015-06-03 11:36
@mousetraps, is this included in the May release?

**Comment by mousetraps** [comment] 2015-06-09 04:42
It is not - still investigating, and we pushed it back to the July milestone because it appeared to be a very isolated scenario that would take a lot of time to root cause the first time I played around with it. I may have found a simpler repro now, though, so we'll see...

**Comment by NoelAbrahams** [comment] 2015-06-09 08:26
@mousetraps, thanks for looking into it.

**Comment by NoelAbrahams** [comment] 2015-06-10 05:51
@mousetraps, 

> it appeared to be a very isolated scenario that would take a lot of time to root cause

We've been working without F12 on NTVS projects for quite a while now and I feel rather aggrieved that nothing is being done about this.

**Comment by paulvanbrenk** [comment] 2015-07-08 22:38
Just verified that this is fixed in the latest version of TypeScript 1.5 and NodeTools 1.1 RC, both of which should be released around VS 2015 RTM.

**Closed by paulvanbrenk** 2015-07-08 22:38 UTC
Labels: bug, fixed

**Comment by NoelAbrahams** [comment] 2015-07-21 11:01
This looks to be fixed. Thanks!

**Comment by Daskul** [comment] 2015-08-13 14:40
changing the tabs option from "keep tabs" to "insert spaces" solves the issue. Why?!

**Comment by paulvanbrenk** [comment] 2015-08-13 18:51
@Daskul Did you reply to the right issue? Can you clarify?

**Comment by Daskul** [comment] 2015-08-14 17:02
Yup. I got the solution from this link. https://social.msdn.microsoft.com/Forums/vstudio/en-US/3a331ad9-4217-480b-a299-62587d22b1db/visual-studio-2015-go-to-definition-is-not-working-on-referenced-assemblies?forum=visualstudiogeneral

**Comment by paulvanbrenk** [comment] 2015-08-14 17:05
@Daskul that issue doesn't seem related to the node tools. It seems to be limited to C#/VB and reference assemblies.

**Comment by Daskul** [comment] 2015-08-14 17:08
Oops sorry! Im so stupid! :) I'll just delete my comments

**Comment by Taztoons** [comment] 2016-09-10 15:58
How do i remove typescript from visual studio 2015 as it is driving me crazy with this cannot navigate to caret issue. I do not use typescript and just want it off so I can continue working productively.

**Comment by paulvanbrenk** [comment] 2016-09-10 18:38
@Taztoons  unfortunately you cannot remove TypeScript, however if you don't use TypeScript is shouldn't interfere with your work. What is this 'navigate to caret' issue you mention? Can you open a new bug to explain your issue?
