### ISSUE TITLE
Visual Studio 2017 (15.4.4) always Rebuilds Node.js with TypeScript (2.6.2) after outDir is set

### ISSUE THREAD

**Issue by JochenAtWork** [Microsoft/nodejstools#1794] opened 2017-11-23 12:51 UTC
##### Steps to Reproduce
1. Create a brand new Node.JS Console App with Type Script
2. Compile twice, the second will do nothing (1 up-to-date)
3. Now enter some outDir (e.g. "dist") in the tsconfig.json (or delete the tsconfig.json and use UI)
4. Compile will ALWAYS rebuild (0 up-to-date)

Inspecting the MSBuild log (verbosity diagnostic) shows that there are two build processes, the first one indeed detecting no change. The issue can not be observed with a ASP.NET TypeScript Web Application - setting the outDir works as expected (only tested with UI without a tsconfig.json). So it seems (guess only) that the Node.Js Tools integration may not use the correct files for change detection and start the second build.

In addition some strange error message about "OutputPath not set" is reported in the MSBuild diagnostics log. The may indicate that the second MSBuild call misses some context information - OutputPath is definitly set in the njsproj file. Personally I think this is a different issue normally unnotable to the developer.

##### Expected Behavior 

Do not build when nothing changed.

##### Actual Behavior 

Always builds. 

- NTVS Version: 1.4.10918.1
- Visual Studio Version: 15.4.4
- Node.js Version: 9.2.0

**Comment by JMS-1** [comment] 2017-11-23 16:25
Must be a matter of seconds: duplicate of https://github.com/Microsoft/nodejstools/issues/1793

Sorry

**Comment by paulvanbrenk** [comment] 2017-11-27 19:04
Thanks for reporting, this is an issue in the TypeScript tools for VS, which should be fixed in a future update of VS 2017. (Probably update 6)

**Closed by paulvanbrenk** 2017-11-27 19:04 UTC
