### ISSUE TITLE
Visual Studio UI not refreshing correctly when opening a new file while project and gulp task is running

### ISSUE THREAD

**Issue by cveld** [Microsoft/nodejstools#819] opened 2016-04-04 10:01 UTC
I have the following setup:
* Visual Studio 2015 update 2
* Modified the nodejs path settings so that Visual Studio picks the globally installed nodejs version
* An ASP.NET Core RC update1 project 
* In running state, through IIS Express
* A gulp-watch task running monitoring .ts (TypeScript) files

Then I execute the following steps:
1. Open an existing .ts file with multiple lines
2. Create a new .ts file through solution explorer's context menu
In the task window you see the gulp watch task spotting the newly added file and executing the task.
Albeit invisible as the UI is not correctly refreshing, Visual Studio immediately opens the new file.
3. Focus on the new .ts file through solution explorer by double clicking

The result is that Visual Studio shows the empty file on top of the file that was opened by step 1. It does not clear the window first.

Expected result: Visual Studio should clear the window first before displaying the file at step 2.

![image](https://cloud.githubusercontent.com/assets/6196260/14244716/db22f28a-fa5c-11e5-864e-8f418569779e.png)

![image](https://cloud.githubusercontent.com/assets/6196260/14244700/cc30d0ee-fa5c-11e5-9fc8-d5be4055b3cf.png)

**Comment by mjbvz** [comment] 2016-04-04 18:46
Is the new file just displaying wrong, or are the file contents wrong? If you edit the file, what happens? 

Also, just want to double check that you are in an NTVS project and not just using Node/Typescript, correct?

This seems more like a Visual Studio issue that should not be specific to NTVS. I tried repoing with a simple noop gulp task and was not able to reproduce this behavior. Can you perhaps try narrowing down the required repo steps. Thanks.

**Comment by cveld** [comment] 2016-04-05 20:07
1. The new file is just a 0-byte blank file. If I edit the file, the
characters I am typing will appear; even when I copy/paste a text fragment
it completely appears on top of the non-refreshed UI. I can workaround the
issue by switching quickly to another tab and back. This will enforce the
refresh.
2. I am in an ASP.NET Core project. Not in an NTVS project. But I was
assuming to be reusing parts of NTVS such as NPM package.json support and
the Gulp Task Manager plug-in. Is this assumption incorrect?
3. If you think it has nothing to do with NTVS, what would be the proper
channel to report my issue?

2016-04-04 20:46 GMT+02:00 Matt Bierner <notifications@github.com>:

**Comment by mjbvz** [comment] 2016-04-05 20:29
Thanks for the info.

@mousetraps It seems to me that this is not NTVS specific, what do you think? A quick search turned up a few similar sounding problems ([this one is in VS 2013 but seems to show the same behavior](https://connect.microsoft.com/VisualStudio/feedback/details/823415/visual-studio-window-does-not-refresh-its-content-properly)).  Do you have a recommended place to report the issue?

**Comment by mjbvz** [comment] 2016-04-05 23:09
I've opened a bug against the Visual Studio team to track this issue. 

Closing as external.

**Closed by mjbvz** 2016-04-05 23:09 UTC
Labels: external
