### ISSUE TITLE
"Invalid access to memory location" on run

### ISSUE THREAD

**Issue by cros79** [Microsoft/nodejstools#128] opened 2015-05-18 07:12 UTC
Sometimes i get this error message in a pop up when I try to run my app after having worked for a while. I can't start debugging or start without debugging. I can still run the app from the command line outside of Visual Studio and the error goes away if I close down my instance of Visual Studio and restart it. 

Visual Studio 2013 Premium with NTVS v1.

**Comment by oocx** [comment] 2015-05-26 10:40
I have the same problem. I first tried NTVS 1.0, then I tried 1.1 beta. I see this problem with both versions. Sometimes the problem disappears when I close / open some files in VS, sometimes it does not disappear until I restart VS.

The problem occurs nearly every time I try to start / debug an application, so that I cannot work with NTVS.

VS Premium 2013, NTVS 1.0  / 1.1, Windows 7 x64, many other VS extensions installed (ReSharper, ...)

**Comment by mousetraps** [comment] 2015-05-28 02:21
@oocx can you try disabling resharper? It's known to cause some major issues when working with NTVS. Also since it reproduces consistently for you... it would be helpful if you could share your project (if possible), otherwise it will be very very difficult for us to resolve this issue.

**Comment by mousetraps** [comment] 2015-05-28 04:04
Also try installing this hotfix.
https://support.microsoft.com/en-us/kb/2588507/

**Comment by sanjeevmajgotra** [comment] 2015-06-23 09:53
started facing same issue all of a sudden.

**Comment by circuitrider** [comment] 2015-09-29 18:19
Happening here too on 2015 pro with Resharper. Still happens with Resharper disabled.

**Comment by circuitrider** [comment] 2015-09-29 18:21
And just for anyone finding this who is stuck thinking there are no other debugging options, start up Chrome and go to url "about:inspect" in order to get your console output and dom inspector.

**Comment by cros79** [comment] 2015-12-04 07:52
@mousetraps Sadly I no longer work on the project where this issue arose so can't provide more feedback on it.

**Comment by gitsoft** [comment] 2015-12-07 12:34
I get this issue as well. 

Prior to getting this error I changed from npm to npm3 in an attempt to avoid the MAX_PATH issue related to dependency trees in npm. 

The node application runs fine if started in a prompt. It also builds just fine in visual studio 2015. But starting it in Visual Studio 2015 cause "invalid access to memory location" to be thrown immediately.

The issue persists even if resharper is turned off.

**Comment by gitsoft** [comment] 2015-12-07 13:57
I uninstalled our npm application and then reinstalled it and all its dependencies with **NPM3**. With resharper turned off I restarted Visual Studio 2015 and now it works for me.

**Comment by billti** [comment] 2015-12-12 00:44
Sorry you are also hitting this @gitsoft . Are you using the final Node Tools 1.1 release? Do you have any specific project or sequence of actions that causes this to occur?

I've never seen this myself, so any info you have that would help me reproduce this issue so I can debug it would be helpful.

**Comment by designerx2** [comment] 2016-01-26 03:39
I experience this issue. Currently have to shut down VS each time I want to run my project. 

Microsoft Visual Studio Community 2015 Version 14.0.24720.00 Update 1 
Node.js Tools   1.1.31117.00

**Comment by hungchai** [comment] 2016-02-05 01:29
@designerx2 
Same as you! I have to restart VS each time.

Microsoft Visual Studio Community 2015 Version 14.0.24720.00 Update 1
 Node.js Tools 1.1.31117.00

**Comment by mousetraps** [comment] 2016-02-05 03:09
Okay, we're not ignoring this, but I genuinely have no idea what's going on here, and would *really* appreciate the help. Let's see if we can crowd-source :smiley:. How about we start by listing windows version, language, node versions, VS version, NTVS version, interesting things about your environment (domain joined, proxy, etc.) etc. and see if we can discern any patterns.

**Comment by DK-Warder** [comment] 2016-02-10 09:17
@mousetraps 
Hotfix https://support.microsoft.com/en-us/kb/2588507/ solve problem for me

**Comment by agthenbo** [comment] 2016-02-13 11:45
@mousetraps +1 'solved' with hotfix [https://support.microsoft.com/en-us/kb/2588507/] on Win7x64+VS2015

[microsoft-nodejstools #128 agthenbo win7-x64+visual-studio-2015 about.txt](https://github.com/Microsoft/nodejstools/files/129089/microsoft-nodejstools.128.agthenbo.win7-x64.visual-studio-2015.about.txt)

**Comment by mousetraps** [comment] 2016-02-14 04:42
Excellent, thanks all! Closing this issue since the [hotfix](https://support.microsoft.com/en-us/kb/2588507/) appears to be working for everyone.

**Closed by mousetraps** 2016-02-14 04:42 UTC
Labels: debugging, external

**Comment by hungchai** [comment] 2016-02-15 01:38
@mousetraps +1 'solved' with hotfix [https://support.microsoft.com/en-us/kb/2588507/] on Win7x64+VS2015

Does it be included from window auto update?

**Comment by designerx2** [comment] 2016-02-16 22:11
So this hotfix from 2012 is for Visual Studio 2015 and Node Tools? Confused.

**Comment by mousetraps** [comment] 2016-02-16 22:13
@designerx2 Yes - the issue is with Windows, not NTVS or VS
