### ISSUE TITLE
Visual Studio 2015 has to be force-closed while debugging

### ISSUE THREAD

**Issue by vickymittal** [Microsoft/nodejstools#732] opened 2016-03-05 15:56 UTC
1. Installed Visual Studio Community 2015 (Version 14.0.24720.00 Update 1)
2. Installed Node.js Tools 1.1.31117.00
3. Installed Node.js v4.3.0
4. Started Visual Sudio
5. New Project -> Blank Node.js Console Application
6. app.js edited with following:
<pre>console.error.apply(this,);
console.log('Hello world');</pre>
7. Press F5.
8. Got dialog
![image](https://cloud.githubusercontent.com/assets/17675168/13548515/3bb4de08-e318-11e5-8962-5716348411f0.png)
9. Visual Studio becomes unresponsive, have to force close it.

**Comment by mousetraps** [comment] 2016-03-05 16:40
Thanks for reporting! This is duplicate of #604. Please try our latest dev build and verify it works for you. http://github.com/Microsoft/nodejstools/releases

**Closed by mousetraps** 2016-03-05 16:40 UTC

**Comment by vickymittal** [comment] 2016-03-06 14:28
Thanks, got it working
