### ISSUE TITLE
Project isn't built on rebuild

### ISSUE THREAD

**Issue by john-cullen** [Microsoft/nodejstools#1857] opened 2018-02-19 14:27 UTC
##### Expected Behavior 
The TypeScript project is built when doing a solution Rebuild or building a project that has been configured to depend on it.

##### Actual Behavior 
The project is not built.

- NTVS Version: 1.4.11025.7
- Visual Studio Version: 15.5.6
- Node.js Version: 8.9.1

There are two TypeScript projects in the solution, one of them builds as expected, one of them does not. I have been unable to see any configuration or project file differences that could explain this.

##### Steps to Reproduce
1. Rebuild

**Comment by paulvanbrenk** [comment] 2018-02-21 01:23
@uniqueiniquity Looks like the issue you were working on in TypeScript.

**Comment by john-cullen** [comment] 2018-02-21 10:05
@paulvanbrenk I've tried 2.5 and 'latest available'. The one that currently works is 'latest' but that didn't make any difference. 

The working one was created as a NodeJS project from existing directory and the one that isn't building was the new typescript project template. I tried setting the project type guids to match the working one but that didn't seem to affect it either.

**Comment by paulvanbrenk** [comment] 2018-05-21 23:46
Closing, as I don't reproduce this. If you do, can you share a project on e.g. GitHub which shows the behavior you're describing?

**Closed by paulvanbrenk** 2018-05-21 23:46 UTC
Labels: external, typescript
