### ISSUE TITLE
npm refresh hangs on refresh

### ISSUE THREAD

**Issue by MarkAurit** [Microsoft/nodejstools#398] opened 2015-08-28 20:14 UTC
windows 7/64 bit/8G
vs 2013 professional
Ive just created a small 'blank console' project and added express using the npm manager express.  After adding it I noticed there was a red message that the catalog of packages was old, so I hit refresh, and it just hangs on the 'loading published package list' dialog. After a few minutes, if I close it, and then choose the "install new package" option, I just get the same dialog. If I let it go for a total of maybe 5-7 minutes I get a "refresh failed - see output below for details", although there is no output that I can tell.
nothing in C:\Users\<user>\AppData\Local\Microsoft\Node.js Tools\NpmCache looked helpful
SOLVED: closed the project, shutdown vs, opened vs and the project.  Now I get the original
screen when adding a package (including the "updated more than 1 month ago" message,
which apparently I need to ignore).

**Comment by jamesxv7** [comment] 2015-09-07 02:34
I am experiencing the same issue but using VS2015 on Win8. There is a workaround mentioned by @mousetraps in [another issue](https://github.com/Microsoft/nodejstools/issues/99#issuecomment-99344063) that worked for me but temporarily. It turns out that as soon I erase the cache in **%localappdata%\Microsoft\Node.js Tools\** and click again on Refresh, the window remains *Loading published package list... / Download completed - updating database* eternally. My output log is:
```
Registry url: https://registry.npmjs.org/
Current Time: 9/6/2015 10:14:41 PM
Last Refreshed: 9/6/2015 8:51:53 PM
Number of Results: 192835
Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\Jaime\AppData\Local\Microsoft\Node.js Tools\NpmCache\1d79c43a-7038-4e54-ac6a-881485af293c\since_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1441586403199
Download complete - updating database
Reading 593255 bytes from C:\Users\Jaime\AppData\Local\Microsoft\Node.js Tools\NpmCache\1d79c43a-7038-4e54-ac6a-881485af293c\since_packages.json (9/6/2015 10:14:57 PM)
```
@mousetraps - Any other information that you need just let me know.

**Comment by billti** [comment] 2015-09-08 16:03
I believe this is the issue I've found and started fixing as discussed in https://github.com/Microsoft/nodejstools/issues/415#issuecomment-137896870 and the next couple of comments. I hope to have a full fix for this in shortly.

**Comment by jamesxv7** [comment] 2015-09-08 16:57
@billti Thanks a lot for the feedback. @MarkAurit since root cause were covered in details on issue #415 this issue should considered closed. What do you think @billti?

**Comment by billti** [comment] 2015-09-09 23:47
Actually, looks like #415 had another root cause, which we seem to have found. I'll keep this issue open for tracking the NPM refresh issue.

**Comment by billti** [comment] 2015-09-10 19:14
This is merged into master now.

**Closed by billti** 2015-09-10 19:14 UTC

**Comment by billti** [comment] 2015-09-11 16:31
@MarkAurit @jamesxv7 We just pushed a new release with this fix. See https://github.com/Microsoft/nodejstools/releases if you'd like to check it out. Thanks!

**Comment by Vandyke-IT-Solutions** [comment] 2015-09-30 08:30
@billti 
I had the same problem and can confirm that the new release fixes the problem. Thanx!
