### ISSUE TITLE
VS 2015 stop working if changes any code while debugging(1.1 rc3)

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#584] opened 2015-11-10 14:05 UTC
VS2015 stop working if I change something and save

**Comment by mousetraps** [comment] 2015-11-11 22:02
Cant repro this. Can you please provide more info? What do you mean by "stops working"? Can you provide simple repro steps starting from one of the project templates? Or do you have a project you can send us where you can reproduce the issue consistently?

**Comment by alanpurple** [comment] 2015-11-12 03:27
Crash I mean
On Nov 12, 2015 7:02 AM, "Sara Itani" <notifications@github.com> wrote:
>
> Cant repro this. Can you please provide more info? What do you mean by
"stops working"? Can you provide simple repro steps starting from one of
the project templates? Or do you have a project you can send us where you
can reproduce the issue consistently?

**Comment by mousetraps** [comment] 2015-11-12 08:52
Thanks, but that's *really* not enough information for us to do anything about it... 
* since it was a crash, there should be a corresponding entry in the Windows event log, and grabbing the stack trace from that is necessary for us to track this down if we can't reproduce the issue. 
* what are steps to reproduce the issue?
* can you reproduce the issue consistently?
* on which projects types does it occur? does it occur in a basic console app?

**Comment by alanpurple** [comment] 2015-11-12 08:57
@mousetraps 
just for any nodejs project,
press F5 for start debugging
and then modify any file which is included in the process, and then ctrl+s and immediately you can see the VS2015 stops working message

If you still can't reproduce this, I will provide a log, tell me, anyway now I'm outside so I can work later

**Comment by aruneshchandra** [comment] 2015-11-12 17:37
@alanpurple please provide the log if you can. Also, can you repro this consistently ?

Is anybody else having this issue ? it will be helpful for us to understand how widespread is this issue.

**Comment by kant2002** [comment] 2015-11-13 14:25
I have similar issue before 1.1rc3. It was sporadic, but I lately avoid debugging in NTVS since it is start using much more memory, and I have to restart VS

**Comment by billti** [comment] 2015-11-13 18:33
Looks potentially the same as #589 .

**Comment by zhengbli** [comment] 2015-11-13 19:49
@kant2002 @alanpurple Are you guys on node v5? It runs fine for me on VS 2013 and VS 2015 with node v4.2, though I can indeed repro the crash on node v5, so I wonder if it is related.

**Comment by alanpurple** [comment] 2015-11-14 09:37
@zhengbli  yes, node 5.0

@mousetraps  I think this is same as #589 as billti said, still need a log?

**Comment by kant2002** [comment] 2015-11-14 12:02
@zhengbli I was on 0.12, but I have something like that just couple times. Not 100% sure that this was exactly this issue. Could try to reproduce

**Comment by mousetraps** [comment] 2015-11-14 15:51
@alanpurple It's your call. If you think it's the same issue, and I believe it is - great, let's close this as a dupe. But if for some unforeseeable reason it turns out to be a different issue, we won't fix it, and you'll keep running into it.
Basically, the more info we have, the more likely (and sooner) any given issue will be fixed. We *really* don't like going back and forth trying to extract out a simple piece of information or otherwise guess a machine setup.
So yes, now that we can reproduce, it probably doesn't matter. But please please please send us more info in the future.
Sent from my Rotary Phone




On Sat, Nov 14, 2015 at 1:37 AM -0800, "alanpurple" <notifications@github.com> wrote:
@zhengbli  yes, node 5.0

@mousetraps  I think this is same as #589 as billti said, still need a log?

---

**Comment by alanpurple** [comment] 2015-11-15 08:03
@mousetraps  Sorry for late response, I've been outside lately

Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: KERNELBASE.dll, version: 10.0.10586.0, time stamp: 0x5632da1c
Exception code: 0xe0434352
Fault offset: 0x000bd8a8
Faulting process id: 0x368
Faulting application start time: 0x01d11f7b97527969
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 7e14acee-f291-404d-94b5-6935531b7499
Faulting package full name: 
Faulting package-relative application ID:

**Comment by syagev** [comment] 2015-12-02 14:00
Experiencing the exact same issue including identical crash logs.

**Comment by billti** [comment] 2015-12-02 20:47
@syagen - did you update to the final 1.1 release? The fix went into that build, so if you are running something earlier, you should expect the same crash and logs.

**Comment by syagev** [comment] 2015-12-03 08:22
@billti - indeed! I'm now hot swapping code smoothly. Thanks! ;)

**Comment by jonmaxwell** [comment] 2016-01-14 19:58
Turn off "Edit and Continue". That solved it for me.

**Comment by mousetraps** [comment] 2016-01-19 11:10
the fix is available in the latest release.

**Closed by mousetraps** 2016-01-19 11:10 UTC
Labels: crash-or-hang, in-progress, next-release
