### ISSUE TITLE
Memory consumption of npm nodes is too high for slns w/ many projects

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#354] opened 2015-08-04 06:21 UTC
We create a new GlobalModulesNode for every project even though they are the same - we should be able to significantly cut down on memory consumption by ensuring we only create/refresh a single instance of global modules

**Comment by kant2002** [comment] 2015-08-04 06:34
Is this based on findings from #264?

**Comment by mousetraps** [comment] 2015-08-04 06:47
Yep! thx, I was trying to find that issue - this is one of the more actionable pieces that came out of it, though let's wait until I get npm v3 changes in this week so things aren't in too much flux.

**Comment by mjbvz** [comment] 2016-04-12 18:33
@mousetraps I'm assuming that you mean the actual GlobalModules data structure, not the GlobalModule project node hierarchy object? I do not believe that the project node can be shared, but the global modules list certainly can be.

While the current code is inefficient, I'm not sure that the GlobalModules are the root cause of the high memory usage.  #815 reduces the memory used for globals and all other modules by discarding the Json objects after they are parsed.

**Comment by mjbvz** [comment] 2016-08-08 18:57
Closing since we've since deleted the global modules node entirely.

**Closed by mjbvz** 2016-08-08 18:57 UTC
Labels: code-happiness, in-progress, npm-integration, performance
