### ISSUE TITLE
Performance - Creating Hierarchy Nodes for every file in `node_modules`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#869] opened 2016-04-19 22:41 UTC
We currently create `FolderNodes` for every file in `node_modules` during project initialization. For projects with many installed packages, this results in extra start up time and extra memory usage since several thousand extra nodes end up being created.

I think that the `FolderNodes` are actually required if we want to show the contents of `node_modules` (even if the folder is excluded from the actual project). However, if possible, we should create the node_modules folder child nodes lazily when the parent is expanded.

**Comment by mjbvz** [comment] 2016-05-04 22:39
Just noting down some thoughts on this.

The easiest sub problem to solve first seems to be the NPM `DependencyNode`. We end up creating between several hundred to several thousand of these nodes for no real reason during project loading, which consumes memory but mostly just slows down project initialization and slows down NPM module update operations. I'm not sure how helpful browsing the entire NPM dependency tree really is, but let's assume we want to keep this behavior.

Here are my thoughts on making the children lazy instead:

1. `DependenyNode` inherits from `HierarchyNode`. Currently, `ReploadHeirachy` is what populates the `DependenyNode` children. It would be more clear to have  `DependenyNode` know how to populate its own children. Move the `ReploadHeirachy` logic to `DependenyNode` and make `ReploadHeirachy` call into this to preserve the existing behavior.

2. In `HierarchyNode`, add a overridable method to determine if a node should be expandable. Expandability is currently based on if the node has any children. But in the case of `DependencyNode`, we know that children should exists from `Package`, but do not actually want to create the children before they are needed. Add this base method to `HierachyNode` and override it on `DependenyNode` using the `Package` information.

3. In `HierarchyNode`, add a way to hook into an `OnExpand` type event that is invoked when the node is expanded  (either by the user or programmatically) or is loaded in an already expanded state. 

4. In `DependenyNode`, use `OnExpand` to populate the children for the first time or update its children. This would just invoke the old `ReploadHeirachy` logic moved in step 1, but not recursively like `ReploadHeirachy ` currently does. 

5. Remove the old calls to `ReploadHeirachy` introduced in step 1.

6. 🌈

**Comment by paulvanbrenk** [comment] 2017-12-28 00:08
Looks like the issue is that the scanning of the file system happens on the UI thread... which for obvious reasons is terrible. Further we don't need any of these node until the uses enables show all files... so going to change this to move the scanning to a low-priority bg thread.

**Comment by paulvanbrenk** [comment] 2018-01-11 00:10
This should be greatly improved by #1835, which will be part of Visual Studio 2017 Update _8_. (I have very little control over that schedule unfortunately).

**Closed by paulvanbrenk** 2018-01-11 00:10 UTC
Labels: performance
