### ISSUE TITLE
Visual Studio crash when opening project

### ISSUE THREAD

**Issue by nearwood** [Microsoft/nodejstools#820] opened 2016-04-04 17:49 UTC
Hello, I've opened this Node.js project before but after an update to NuGet (the only thing I've done) I get a crash every time I try to open my Node.js project.

Exception details:
```
Version 1.01.31117.0
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.NodejsTools.Analysis.dll
Additional information: Object reference not set to an instance of an object.
```

Windows Application Event Log:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.NodejsTools.Analysis.AnalysisUnit.AnalyzeWorker(Microsoft.NodejsTools.Analysis.Analyzer.DDG, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.Analyzer.DDG.Analyze(Microsoft.NodejsTools.Analysis.Deque`1<Microsoft.NodejsTools.Analysis.AnalysisUnit>, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.JsAnalyzer.AnalyzeQueuedEntries(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue+GroupAnalysis.Analyze(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue.Worker(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

```

**Comment by nearwood** [comment] 2016-04-04 17:51
I've noticed #70 and #656 as well, and will try the options in those.

**Comment by nearwood** [comment] 2016-04-04 17:55
package.json:
```
{
  "name": "ULCreate",
  "version": "0.0.0",
  "description": "",
  "main": "server/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server/index.js",
    "build-min-client-prod": "node client/www/build/private/buildScript.js",
    "build-min-client-dev": "node client/www/build/private/buildScript.js dev"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "async-waterfall": "^0.1.5",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.2.0",
    "browserify": "^13.0.0",
    "browserify-css": "^0.9.1",
    "compression": "^1.6.1",
    "exorcist": "^0.4.0",
    "express": "^4.13.3",
    "fast-json-patch": "^0.5.6",
    "fs-extra": "^0.26.7",
    "jquery": "^1.12.2",
    "jsonpatch-to-mongodb": "^0.2.0",
    "mongodb": "^2.1.4",
    "ramda": "^0.20.0",
    "react": "^0.14.7",
    "react-addons-transition-group": "^0.14.7",
    "react-dom": "^0.14.7",
    "socket.io": "^1.4.4",
    "socket.io-client": "^1.4.5",
    "uglifyify": "^3.0.1",
    "watchify": "^3.7.0"
  },
  "devDependencies": {}
}

```

**Comment by mjbvz** [comment] 2016-04-04 18:29
What version of NTVS and visual studio are you on?

#781 recently added a few more null checks to `AnalyzeWorker` to at least prevent crashes, but is only in the 1.2 Alpha.

**Comment by nearwood** [comment] 2016-04-04 20:41
VS: 14.0.24720.00 U1
Node.js Tools: 1.1.31117.0 (reported as 1.01.31117.0 in the exception (?)).

Full spiel:
```
Microsoft Visual Studio Professional 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Visual Basic 2015   00322-50051-48306-AA906
Microsoft Visual Basic 2015

Visual C# 2015   00322-50051-48306-AA906
Microsoft Visual C# 2015

Visual C++ 2015   00322-50051-48306-AA906
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   4.3.60226.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40204.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.6.0
TypeScript for Microsoft Visual Studio
```

**Comment by mjbvz** [comment] 2016-04-04 22:05
Thanks. I can't be 100% sure that #781 will fix what you are running into, but it may. I can't repo the issue at least on the latest builds.

We plan on getting out a V1.1 patch sometime this week and I'll make sure that  #781 gets in. You can also give the NTVS 1.2 alpha a try, but it will be more unstable and you would need to update VS 2015 to update two.

Closing for now as a duplicate of #766 but please reopen if you run into the issue on the new releases.

Thanks

**Closed by mjbvz** 2016-04-04 22:05 UTC
Labels: crash-or-hang, duplicate
