### ISSUE TITLE
node js window no option to stop process

### ISSUE THREAD

**Issue by Jack85** [Microsoft/nodejstools#1866] opened 2018-02-23 08:34 UTC
##### Expected Behavior 
ctl+c to exit proces, also some button stoping task
##### Actual Behavior 
there is now way to stop task running, except task manager and kill the process, this is very wrong
option for several windows not present

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
1. start any process using npm
2.

**Comment by paulvanbrenk** [comment] 2018-02-27 01:29
Thanks this is a duplicate of #578

**Closed by paulvanbrenk** 2018-02-27 01:29 UTC
