### ISSUE TITLE
Visual Studio (2013 Professional) crashes when debugging is started

### ISSUE THREAD

**Issue by flobraun** [Microsoft/nodejstools#82] opened 2015-04-28 08:23 UTC
Hi,

I have a setup with Visual Studio 2013 Professional and node.js 0.12.2

I try to follow the setup guide and run the hello-example. (blank server project, no changes).

Whenever i start debugging VS crashes with:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-04-28T08:34:52.000000000Z" /> 
  <EventRecordID>41572</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>xxxl</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Anwendung: devenv.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet. Ausnahmeinformationen: System.ArgumentException Stapel: bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__1(System.Object) bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object) bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() bei System.Threading.ThreadPoolWorkQueue.Dispatch() bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</Data> 
  </EventData>
  </Event>

and 

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-04-28T08:34:52.000000000Z" /> 
  <EventRecordID>41573</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>xxx</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>devenv.exe</Data> 
  <Data>12.0.31101.0</Data> 
  <Data>54548724</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>6.1.7601.18409</Data> 
  <Data>531599f6</Data> 
  <Data>e0434352</Data> 
  <Data>0000812f</Data> 
  <Data>894</Data> 
  <Data>01d0818dfaf07a9d</Data> 
  <Data>C:\Program Files\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe</Data> 
  <Data>C:\Windows\system32\KERNELBASE.dll</Data> 
  <Data>706205e1-ed81-11e4-bba1-00accd073ba8</Data> 
  </EventData>
  </Event>

I can start without debugging and i get the following exception in the console window:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Server.listen (net.js:1257:5)
    at Object.<anonymous> (C:\Users\kofbr\Source\Workspaces\Bibliothek\NodejsWeb
App2\NodejsWebApp2\server.js:6:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Press any key to continue...

but the browser is opened and "Hello World" is shown and VS doesn't crash.

**Comment by mousetraps** [comment] 2015-05-03 18:31
Unfortunately I can't repro the crash. Does it happen for other project types, or just Node projects?

Regarding the EADDRINUSE issue, you'll probably get the same error if you run your application in the command line. It happens when another server is already running on the requested port, so you'll need to verify that there are no lingering node processes associated with the port you are using.

**Comment by flobraun** [comment] 2015-05-04 13:57
I guess the EADDRINUSE - Error happens as visual studio is closed after the exception and the connection for the debugger is lost.

The first error (the crashing visual studio) happens only for node.js - projects.

**Comment by mousetraps** [comment] 2015-05-08 20:43
So just to clarify, because I'm not entirely sure I understand the issue...
* you start **with debugging** with a new project using the blank web application template
* a node.js EADDRINUSE error occurs (can you see this before visual studio crashes, or are you 
* Visual Studio crashes with the stack trace you included

And...
* you start **without debugging** with a new project using the blank web application template
* a node.js EADDRINUSE error occurs, but the application runs fine.

If so... let's tackle the no-debugging case first. 
* if you try killing any lingering node.exe processes before starting Visual Studio... do you still get the EADDRINUSE error when you start without debugging?
* If you run your application from the command prompt - ```node server.js```, do you see the same error, or do you see a different behavior?

**Comment by laingmatthew** [comment] 2015-05-13 17:33
I am having the same issue with Visual Studio pro 2013... 
When I run node.js in the command prompt `node app.js` the program works.
When I run from within Visual Studio and select "Without Debugging" it runs fine.
When I run from within Visual Studio "Start Debugging" Visual Studio crashes.

![image](https://cloud.githubusercontent.com/assets/12433222/7616701/823c0f6a-f974-11e4-9b6e-e8dc6e445f3d.png)

The window above is open along with the "Debugging console" that I would expect to normally have the program be running in (the console that pops open when I run the program from within Visual Studio).

Let me know if any other info could help.

**Comment by mousetraps** [comment] 2015-05-14 05:43
@laingmatthew any chance you could share a sample app or set of repro steps?

**Comment by laingmatthew** [comment] 2015-05-14 10:52
The app is the most simple it could be...

`console.log("Hello World");`

I haven't run into this before (I've used the tools on a different PC). All I did was download and install on top of visual studio pro 2013. Sorry I know that isn't much help to reproduce it...

**Comment by flobraun** [comment] 2015-05-28 06:44
Just to clearify again: it's Visual Studio thats crashing when starting to debug. The error on console is just the result of the sudden close of visual studio. 

Interesting: i additionally installed Visual Studio 2015 RC and there everything works fine. Installing VS 2013 again didn't help to fix it.

**Comment by michalhainc** [comment] 2015-06-03 10:40
Hi I have the same here... my VS  2013 comunity edition crashes when trying to debug any node.js application.

When I open the debugger when crashed, I can see this exception of node.js tools happening which exactly shows, that it crashes in the constructor of the NodeBackTraceVariable class in the NodejsTools.Debugger.Serialization namespace:

`Can not convert Boolean to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Microsoft.NodejsTools.Debugger.Serialization.NodeBacktraceVariable..ctor(NodeStackFrame stackFrame, JToken parameter)
   at Microsoft.NodejsTools.Debugger.Commands.BacktraceCommand.<>c__DisplayClass4.<GetVariables>b__2(JToken t)
   at System.Linq.Enumerable.<>c__DisplayClass12``3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator``2.MoveNext()
   at System.Collections.Generic.List``1..ctor(IEnumerable``1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable``1 source)
   at Microsoft.NodejsTools.Debugger.Commands.BacktraceCommand.GetVariables(NodeStackFrame stackFrame, IEnumerable``1 variables)
   at Microsoft.NodejsTools.Debugger.Commands.BacktraceCommand.ProcessResponse(JObject response)
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient.<SendRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger.<TrySendRequestAsync>d__f3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger.<PerformBacktraceAsync>d__98.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger.<>c__DisplayClass4f.<<OnBreakpointEvent>b__4e>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient.<RunWithRequestExceptionsHandled>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

I love the node.js tools extension for visual  studio, and I am willing to help with fixing, but I definitely would need some guidance.

BR

M.

**Comment by PritamUpadhyay** [comment] 2015-06-03 10:56
Same issue.

**Comment by mrvamsidhar** [comment] 2015-06-16 07:16
I am also having the same issue. Can some one explain how to resolve this issue?

**Comment by MStruntze** [comment] 2015-08-16 12:06
I experienced this issue as well and started to debug why exactly.
It seems like it happens if your app listens (app.listen(port) with express 4) to the same port as defined in your project's "Node.js port"property defined in projectname.njsproj. Having different ports, starting the app and then navigating away from the port you're sent to as set in the properties and to the port your app is listening to shows that two apps are running. One on each port. Hence why you get the error about the address already being in use.

**Comment by mousetraps** [comment] 2015-10-11 00:35
@MStruntze that's really odd. Are both processes launched when you begin debugging or was one lingering around beforehand? Are you using process.env.port (which is what "Node.js Port" sets) anywhere else in your code? Does this issue still occur with the Express starter templates? What are the command line arguments to both processes if you look into task manager?
![image](https://cloud.githubusercontent.com/assets/762848/10414002/0f12d02e-6f75-11e5-9536-4d7f66de9b81.png)

**Comment by mousetraps** [comment] 2015-11-16 06:59
Closing this info since it's been a while, we still can't reproduce, and we've made a ton of debugger changes since that very well could have fixed things. If you're still running into this issue, please provide the following info, and we'll be happy to re-open.

1. try our latest release: https://github.com/Microsoft/nodejstools/releases
2. let us know the results of running `node --debug app.js` in the command line
3. provide the corresponding windows event log entry that will include details about the crash
4. provide the corresonding crash dump from: `%LOCALAPPDATA%\CrashDumps`
5. what version / architecture of Node.js, Windows, VS, and NTVS are you using?
6. Have you discovered any workarounds, or noticed otherwise interesting behaviors?

Thanks in advance!

**Closed by mousetraps** 2015-11-16 06:59 UTC
Labels: bug, crash-or-hang, debugging, need-more-info, next-release

**Comment by vickymittal** [comment] 2016-03-05 15:52
Finally able to emulate this issue:

1. Installed Visual Studio Community 2015 (Version 14.0.24720.00 Update 1)
2. Installed Node.js Tools 1.1.31117.00
3. Installed Node.js v4.3.0
4. Started Visual Sudio
5. New Project -> Blank Node.js Console Application
6. app.js edited with following:
<pre>console.error.apply(this,);
console.log('Hello world');</pre>
7. Press F5.
8. Got dialog
![image](https://cloud.githubusercontent.com/assets/17675168/13548515/3bb4de08-e318-11e5-8962-5716348411f0.png)
9. Visual Studio becomes unresponsive, have to force close it.

**Comment by mousetraps** [comment] 2016-03-05 16:32
@vickymittal have you tried the latest dev build? http://github.com/microsoft/nodejstools/releases we've actually fixed the issue you're running into

**Comment by vickymittal** [comment] 2016-03-06 14:30
Thanks, tried it and the issues stands resolved
