### ISSUE TITLE
 "Error - Cannot load global packages." after fresh install of node/npm

### ISSUE THREAD

**Issue by dariagrigoriu** [Microsoft/nodejstools#476] opened 2015-09-22 18:05 UTC
Expected: no node_modules folder found, no error
Actual: "Error - Cannot load global packages." when no node_modules folder is found

**Comment by haferje** [comment] 2015-10-02 18:51
+1

**Comment by sgireddy** [comment] 2015-11-11 05:20
+1
I had to abandon VS 2015 due to this bug.

Error - Cannot load global packages.
Error - Cannot load global packages.
System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Users\sgireddy\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm\node_modules\graceful-fs\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
***

**Comment by mousetraps** [comment] 2015-11-12 00:40
hey, everyone, this looks like a duplicate of #208, which has been fixed and is available in our latest release! https://github.com/Microsoft/nodejstools/releases

**Closed by mousetraps** 2015-11-12 00:40 UTC
Labels: bug, npm-integration

**Comment by slowkot** [comment] 2015-11-14 00:01
@sgireddy 
It looks like vs2015 does not work with the latest 5.0.0 Node. Replacing with 4.2.2 one solves this issue for me.

To make Visual Stuido use the same Node and npm as cmd by changing some files including node.exe under following folder:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External

Look for this article http://jameschambers.com/2015/09/upgrading-npm-in-visual-studio-2015/
