### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#640] opened 2015-12-12 14:05 UTC
Error running tests

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Could not find all.json

   at Microsoft.NodejsTools.Analysis.JsAnalyzer..ctor(AnalysisLimits limits) in E:\d\kant\GitHub\nodejstools\Nodejs\Product\Analysis\Analysis\JsAnalyzer.cs:line 103
   at AnalysisTests.AnalysisHashSetTests.CreateProjectEntry() in E:\d\kant\GitHub\nodejstools\Nodejs\Tests\AnalysisTests\AnalysisHashSetTests.cs:line 185
   at AnalysisTests.AnalysisHashSetTests.TestImmutableSet(IAnalysisSet emptySet) in E:\d\kant\GitHub\nodejstools\Nodejs\Tests\AnalysisTests\AnalysisHashSetTests.cs:line 153
   at AnalysisTests.AnalysisHashSetTests.TestEmptySet(IAnalysisSet emptySet) in E:\d\kant\GitHub\nodejstools\Nodejs\Tests\AnalysisTests\AnalysisHashSetTests.cs:line 38
   at AnalysisTests.AnalysisHashSetTests.TestEmpty() in E:\d\kant\GitHub\nodejstools\Nodejs\Tests\AnalysisTests\AnalysisHashSetTests.cs:line 31
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestExecuter.DefaultTestMethodInvoke(Object[] args)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.DefaultTestMethodDecorator.Invoke(Object[] args)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestExecuter.RunTestMethod()
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestExecuter.ExecuteTest()
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestExecuter.Execute(UnitTestResult result)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestRunner.ExecuteSingleTest(UnitTestExecuter executer, UnitTestElement test, ITestContext testContext, UnitTestAdapterContext userContext, Boolean isLoadTest)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestRunner.Run(UnitTestElement test, ITestContext testContext, Boolean isLoadTest, Boolean useMultipleCpus)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by mousetraps** [comment] 2015-12-14 22:41
Closing as a duplicate of #646 (we have hundreds of tests failing and I don't think it'll be particularly useful to have a separate issue for each, unless of course we've concretely identified a class of issues - e.g. debugger tests failing because of X) - fwiw you should be able to get past this particular issue by running the tests in release mode.

**Closed by mousetraps** 2015-12-14 22:41 UTC
