### ISSUE TITLE
use Custom Code Snippets

### ISSUE THREAD

**Issue by pungggi** [Microsoft/nodejstools#317] opened 2015-07-25 06:12 UTC
Hello when working with server files or better with property Build Action = Compile,
there is no chance to use any code snippet at all.

For example right click Insert Code Snippet Ctrl+K, Ctrl+X is not available.

**Comment by mousetraps** [comment] 2015-07-26 18:39
This is a duplicate of #158 , which is currently in progress.

**Closed** 2015-07-26 18:39 UTC
