### ISSUE TITLE
"Wait for input when process exits" options have no effect when debugging

### ISSUE THREAD

**Issue by AlexVallat** [Microsoft/nodejstools#1976] opened 2018-05-24 12:14 UTC
##### Expected Behavior 
When either of the "Wait for input when process exits" options are checked, the node console window should wait for the user to press a key before exiting.

##### Actual Behavior 
The console window immediately closes on process exit, regardless of the settings

- NTVS Version: 1.1.11027.3
- Visual Studio Version: 15.7.2
- Node.js Version: 8.11.2

##### Steps to Reproduce
1. Install Visual Studio 2017 and Node.js LTS.
2. Create a new project from the "Blank Node.js Console Application" template
3. Ensure the "Wait for input when process exits" options are checked
4. Hit F5 to run the project in the debugger. Note that it exits immediately after running.
5. Hit Ctrl+F5 to run the project without debugging. Note that it correctly waits for user input before exiting.

Further, it appears that the debugger is completely ignoring the Debugger port and Node.js port settings in the project properties - not sure if that's related or should be a separate bug.

**Comment by enek** [comment] 2018-06-25 17:30
This makes it very hard to debug NodeJS apps.  Only started happening with recent updates.  Anyone find out how to work around this issue?

**Comment by jasonkaler** [comment] 2018-07-01 12:32
I'm also experiencing this issue. It makes debugging impossible.

**Comment by gha88** [comment] 2018-07-01 13:09
Me too but I don't understand if is a problem of few or if everybody is experiencing it. If the latter why no official reply ?

**Comment by kant2002** [comment] 2018-07-01 14:06
The no reply, is that nobody give a damn about this workflow in Visual
Studio. Welcome to Node.JS tools for visual studio. If any errors happens,
you will have following responses: could not reproduce work fine with
latest VS bits, this is issue with Visual Studio Project System, this is
should be implemented by TypeScript, so times is “NodeJs broke things and
we will update in next release”

**Comment by kant2002** [comment] 2018-07-01 14:10
To say true, very likely team is underfunded and not much cycles put into
the work, but overall result is that this workflow about which nobody care

**Comment by paulvanbrenk** [comment] 2018-07-23 22:42
For Node 8 we had to switch to a different debugger, since the debugger protocol used by node changed. Since then we've moved to the same debugger as VS Code, but we haven't been able to implement all the features. 

Closing this as we're tracking this in the debugger issue tracker, which is a different team and unfortunately not public.

**Closed by paulvanbrenk** 2018-07-23 22:42 UTC
Labels: debugging
