### ISSUE TITLE
Cannot install missing scoped packages

### ISSUE THREAD

**Issue by benquarmby** [Microsoft/nodejstools#636] opened 2015-12-10 22:29 UTC
It's possible to install scoped packages using a custom registry, as seen here:
![image](https://cloud.githubusercontent.com/assets/1434816/11730442/5126b698-9fe9-11e5-81b4-53fb320f07e4.png)

However, it is not possible to restore them in a new environment when the `node_modules` folder is missing:
![image](https://cloud.githubusercontent.com/assets/1434816/11730435/4533a33c-9fe9-11e5-8e93-f28503af2d80.png)

The "Install Missing npm Packages" context menu item is also disabled.

Edit: A workaround is to add a non-scoped package which will be shown as missing and enable the context menu item.

**Comment by billti** [comment] 2015-12-12 01:10
I'm not sure I understand the scenario. Can you provide a little more detail?

Also, is this easily solved via from the command line? Or is there a specific scenario that is not possible until this is addressed?

**Comment by benquarmby** [comment] 2015-12-13 03:49
There are two issues really which I'll explain below, but I'd categorize them both as nuisances. Yes, they can be easily worked around from the command line.

To replicate:
* Start a new NTVS project such as a console app
* Install a single scoped package from the npm dialog and save to `package.json`
* Close the solution
* From the file system, delete the `node_modules` folder
* Open the solution
* Observe issue 1: The package does not show it's scoped name in the list and says "not listed in package.json" which is not true
* Observe issue 2: Right clicking on the npm node displays the "Install Missing npm Packages" context menu item, but it is disabled.

**Comment by mousetraps** [comment] 2015-12-14 22:35
Looks like this might be a duplicate of #590. We haven't investigated the scoped modules scenario as closely as we should have just yet, but definitely follow that issue to be updated on future progress.

**Closed by mousetraps** 2015-12-14 22:35 UTC

**Comment by benquarmby** [comment] 2015-12-14 22:39
Yes, looks like it's related to #590. Will follow that for updates.
