### ISSUE TITLE
Visual Studio 2015 support for automatic brace completion with ES5, ES6

### ISSUE THREAD

**Issue by vBlueFlag** [Microsoft/nodejstools#1159] opened 2016-07-25 01:57 UTC
Below link is what I suffered.
[http://stackoverflow.com/questions/38538736/visual-studio-2015-support-for-automatic-brace-completion-with-ecmascript-6]

I just want to use auto brace completion in Node.js. Although I already set all options of 'auto brace completion', it didn't work.
Even it happenes in ES5, sometimes, not always.

It causes me pain so much. Please fix this problem.
I'm wating for your answer eagerly.

- NTVS Version: 1.2RC
- Visual Studio Version: 2015
- Node.js Version: 4.4.7

**Comment by mjbvz** [comment] 2016-07-25 18:36
Thanks for reporting this and sorry you are running into this issue This is a known regression and tracked by #1142.

The root cause appears to be that ES6 IntelliSense is power by TypeScript, and the Typescript editor doesn't support automatic brace completion yet: https://github.com/Microsoft/TypeScript/issues/1484 This should be in Typescript 2.0 once that is released. 

Closing as duplicate of #1142.

**Closed by mjbvz** 2016-07-25 18:36 UTC
Labels: duplicate
