### ISSUE TITLE
Some strange error in the Error List 'Cannot write file'

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1108] opened 2016-06-27 10:58 UTC
##### Expected Behavior 
I don't think that providing errors 'Cannot write file ... because it overwrite existing files' is correct.
maybe this show some race condition in the code. The actual error is 'TS5055 TypeScript Cannot write file because it would overwrite input file.'

After I let VS handing for some time without touching it, errors appear in the list. Please wait around 1-2 minute, this issue appear on the new project.

##### Actual Behavior 
![image](https://cloud.githubusercontent.com/assets/4257079/16377177/55d65b64-3c86-11e6-91ee-2cbbbdae9771.png)

- NTVS Version: NTVS 1.2 Beta
- Visual Studio Version: VS2015 RC3
- Node.js Version: 

##### Steps to Reproduce
1. Create new Nodejs Project
2. Wait 1-2 minutes
3. Error should appear in the Error list

cc: @mousetraps, @mjbvz

**Comment by mjbvz** [comment] 2016-06-27 14:47
Duplicate of #928 

This is a Typescript/Salsa issue that should be resolved by VS 2015 Update 3 RTM (the RC does not have the fix.) RTM is going live today. Once it does, try upgrading and let us know if you still see the issue. Thanks.

**Closed by mjbvz** 2016-06-27 14:47 UTC
Labels: external

**Comment by kant2002** [comment] 2016-06-28 03:15
@mjbvz thanks.
