### ISSUE TITLE
Support debugging spawned node child processes

### ISSUE THREAD

**Issue by tyson-benson** [Microsoft/nodejstools#1127] opened 2016-07-06 04:28 UTC
##### Expected Behavior 
When I spawn a child node process of another script in my application (in order to improve the speed of CPU intensive tasks). I would like the debugger to be able to attach to the spawned process.

##### Actual Behavior 
The spawned node process runs independently and completes before I have a chance to attach to the node process.

- NTVS Version: 1.2.40627.01
- Visual Studio Version: 14.0.25421.03 Update 3
- Node.js Version: 6.2.2

##### Steps to Reproduce
1. Create main.js
```
var execFile = require('child_process').execFile;

execFile('node', ['child.js'], function (err, stdout, stderr) {
    //handle result
   console.log(stdout.toString());
});
```
2. Create child.js
```
console.log('hello');
```
3. Put a breakpoint in main.js on `console.log(stdout.toString());`
4. Put a breakpoint in child.js on `console.log('hello');`
5. Start the debugger on main.js
6. Observe that breakpoint in child.js is not hit.

**Comment by mjbvz** [comment] 2016-07-06 17:54
Out of curiosity, does the builtin node debugger support this workflow?

This [StackOverflow question](http://stackoverflow.com/questions/16840623/how-to-debug-node-js-child-forked-process) and this NodeInspector issue look relevant: https://github.com/node-inspector/node-inspector/issues/130

If using `execFile` instead of `fork`, I think you would have to launch the child node process with  `--debug-brk=PORT`. You should then be able to attach to this child process from Visual Studio.

NTVS is somewhat limited by Node, but what would your ideal workflow look like here?

**Comment by mjbvz** [comment] 2016-08-04 21:11
Closing as by design. If anyone wants to look into improving the experience, let me know.

**Closed by mjbvz** 2016-08-04 21:11 UTC
Labels: by-design, debugging, feature
