### ISSUE TITLE
nodejs tools for visual studio 2017 can not load npm package list

### ISSUE THREAD

**Issue by aisok** [Microsoft/nodejstools#1507] opened 2017-03-21 01:45 UTC
##### Expected Behavior 
List all the npm packages in the 'Install New npm packages' window.
##### Actual Behavior 
There is no one package in the 'Install New npm packages' window.

- NTVS Version:1.2
- Visual Studio Version: 2017
- Node.js Version: 
v7.2.1
##### Steps to Reproduce
1. On the Nodejs project's 'npm' menu,Right click the 'npm' node, and select the 'Install New npm packages...'
2. In the ''Install New npm packages' window,display the result:'Installed locally Refresh failed,-- see output'
3.The output message is here:
Reading 9994844 bytes from C:\Users\Administrator\AppData\Local\Microsoft\Node.js Tools\NpmCache\all_packages.json (3/21/2017 8:41:04 AM)
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\Administrator\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting b28e3012-bb4b-4071-b359-e9b4cac9a031
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()
Registry url: http://registry.cnpmjs.org/
Path to npm: C:\Program Files\nodejs7.2.1\npm.cmd
Downloading package cache to C:\Users\Administrator\AppData\Local\Microsoft\Node.js Tools\NpmCache\b28e3012-bb4b-4071-b359-e9b4cac9a031\all_packages.json
Downloading list of packages from http://registry.cnpmjs.org/-/all
Downloaded 1MB of the package list (10MB total)
Downloaded 2MB of the package list (10MB total)
Downloaded 3MB of the package list (10MB total)
Downloaded 4MB of the package list (10MB total)
Downloaded 5MB of the package list (10MB total)
Downloaded 6MB of the package list (10MB total)
Downloaded 7MB of the package list (10MB total)
Downloaded 8MB of the package list (10MB total)
Downloaded 9MB of the package list (10MB total)
Download complete - updating database
Reading 9995030 bytes from C:\Users\Administrator\AppData\Local\Microsoft\Node.js Tools\NpmCache\b28e3012-bb4b-4071-b359-e9b4cac9a031\all_packages.json (3/21/2017 9:28:42 AM)
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\Administrator\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting b28e3012-bb4b-4071-b359-e9b4cac9a031
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()

**Comment by billti** [comment] 2017-03-21 20:36
Duplicate of https://github.com/Microsoft/nodejstools/issues/1481 . It's an issue on the NPM end. We'll be removing this functionality soon as it uses an API they plan to deprecate.

**Closed by billti** 2017-03-21 20:36 UTC

**Comment by codputer** [comment] 2017-05-10 20:56
This problem exits today VS 2017 - new install of node

**Comment by spevilgenius** [comment] 2017-06-15 08:52
Started happening to me this morning! Same error. Was a fix ever made on NPM end?

**Comment by nikhilgupta8990** [comment] 2017-06-19 07:40
Happening for me too.

**Comment by stefaanv** [comment] 2017-06-27 08:41
Same problem here

**Comment by qwertie** [comment] 2017-06-28 06:20
I have the same error, but in VS2015. The entire contents of all_packages.json is `{"message":"deprecated"}` so it's unclear where the "Unexpected JSON token" is...

**Comment by coffeeaddict19** [comment] 2017-06-29 18:32
Had the same problem with VS2017 trying to get the Edge.JS package in my solution. Ended up right-clicking on project and opening up command prompt. Then did this in command window and it worked: "npm install edge". The Package Manager Console that comes with VS2017 was useless. Kept saying "Install-Package : Project 'Default' is not found."

**Comment by billti** [comment] 2017-06-29 23:19
Looks like NPM deprecated the endpoint if that's the message coming back. The latest releases of VS 2017 don't use that endpoint anymore, but use their search API (which also makes it pretty quick - especially on first load). See #1558 . I honestly can't recall if that's in the latest "official" release (15.2) or the next (15.3). You can always use the command-line to install packages in the meantime.

**Comment by rajarajan1985** [comment] 2017-08-12 01:22
Is there any fix or workaround to continue using npm node in VS2013 to download packages ? Please share. Thanks in Advance!

**Comment by KEMBL** [comment] 2017-08-20 01:51
Guys, use this advice https://developercommunity.visualstudio.com/content/problem/88970/npm-package-manager-dose-not-work.html

i.e. Install Visual Studio 2017 Update 3, i have checked it works.

**Comment by KEMBL** [comment] 2017-08-20 01:57
Guys, install Visual Studio 2017 Update 3, I have checked it works.

more: https://developercommunity.visualstudio.com/content/problem/88970/npm-package-manager-dose-not-work.html
