### ISSUE TITLE
Scoped modules not supported in package.json

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#590] opened 2015-11-12 07:41 UTC
When entering scoped module following issues happens:
1. Intellisense does not show versions available
2. NPM install process does not start, you have to trigger it manually

**Comment by mousetraps** [comment] 2015-11-12 08:03
What do you mean by "npm install process does not start"? When do you expect it to be automatic?

**Comment by kant2002** [comment] 2015-11-12 08:08
when I press save, Bower and NPM in the VS2015 start installing packages. That's quite useful feature.

**Comment by mousetraps** [comment] 2015-11-12 08:36
Ahh, are you on VS Update 1 RC? We actually disabled that feature in NTVS because it's provided by another team who is using our npm component, and it...
* caused issues with machine config (doesn't respect NTVS node/npm settings and defaults to its own privately installed and un-updated version of npm)
* causes tons of node.exe processes to fire up that never die when offline
* uses an older version of the npm integration in ntvs, which will have more errors and make it difficult for us to isolate / fix issues
* results in two versions of the same component running which would double memory usage and potentially cause other conflicts

For update 2, we plan to work together to figure out a more cohesive story, but the new functionality simply wasn't worth the cost at this time.

**Comment by kant2002** [comment] 2015-11-12 08:59
Ok. Make sense. I suspect something like this.

But Intellisense in package.json is also not yours? If not, could you ping another team, that scoped modules version does not show up in the Intellisense. I understand reasoning why install on save does not working, but why not have Intellisens for scoped modules?

**Comment by mjbvz** [comment] 2016-06-22 20:43
Closing this. Moving to the ES6 IntelliSense engine, I believe the first part of this issue is not longer relevant, or is an external Typescript/Salsa scenario. The second part seems to be by design. Let me know if you disagree.

**Closed by mjbvz** 2016-06-22 20:43 UTC
Labels: external, feature

**Comment by wizarrc** [comment] 2017-03-16 18:22
@mjbvz @kant2002 I can confirm that this problem still exists in VS 2017 RTM when trying to get available versions of scoped packages like @angular/core using IntelliSense in package.json. If you are saying that this was moved to salsa, where would I go to report this issue?

**Comment by billti** [comment] 2017-03-17 23:16
NPM does not provide an endpoint to search for scoped packages, so we can't fetch the data to provide intellisense for them unfortunately.

**Comment by wizarrc** [comment] 2017-03-18 04:10
@billti How unfortunate :/
