### ISSUE TITLE
Launch Node.js Profiling - 0 total samples collected

### ISSUE THREAD

**Issue by Luis06** [Microsoft/nodejstools#659] opened 2016-01-08 15:48 UTC
Hi! 

I'm currently working with a TypeScript - Node.js project. I have Visual Studio Community 2015, Node.js Tools  and Node.js Tools - Profiling 1.1.31117.00, TypeScript 1.7.6.0. 
I tried to launch Node.js profiling tools -> Select Open project for my current project and I got "Unexpected Token import" in my startup module, and the profiling tools exits. 
If I, instead of selecting Open project, create a Standalone script in the profiling settings and define the "script" to my startup module in JavaScript (already compiled) and "Working directory" to my output folder (where I redirect my .js files) the profiling tools oepn correctly. However, when I close the app and see the generated report I get: "0 total samples collected"..no call tree, no functions...But I can see the CPU (% usage) correctly.

What am I doing wrong? Can you please assist me?
Thanks.

**Comment by mousetraps** [comment] 2016-01-10 23:51
Could you try following the instructions we have here for creating and importing an existing v8 log?  https://github.com/Microsoft/nodejstools/wiki/Profiling#using-an-existing-v8-log

Understanding the result of that will help us better understand what's going on.

**Comment by Luis06** [comment] 2016-01-11 11:10
Hi, 

Thanks for the response. After following you instructions I saw that:

1 - When running command Microsoft.NodejsTools.NodeLogConverter, warning messages of "Unknown

**Comment by Luis06** [comment] 2016-01-11 11:22
Hi,

Thanks for the response. After following you instructions I saw that:

1 - When running command Microsoft.NodejsTools.NodeLogConverter, warning messages of "Unknown record type" appeared.

2 - Opening the .vspx with Visual Studio I can see that it only recognizes two functions, identified by .1054 and .221. Both modules and processes views are filled with Unknowns:

![img1](https://cloud.githubusercontent.com/assets/10677677/12232196/ead714c6-b854-11e5-8ba3-1cd9461b3a5c.PNG)
![img2](https://cloud.githubusercontent.com/assets/10677677/12232195/ead57ecc-b854-11e5-8700-b3618eb4bf9a.PNG)
![img3](https://cloud.githubusercontent.com/assets/10677677/12232197/eaedbf82-b854-11e5-89b8-b96ca48ad195.PNG)

If I instead use node-debug (from node-inspector) everything is correctly identified, all the objects, functions,... Am I forgetting something?

Thanks

**Comment by mousetraps** [comment] 2016-01-20 23:15
Thanks for the screenshots. Let's try and isolate the issue. What version/architecture of Node are you running? If you're running x64, would you mind running the same LogConverter steps on x64?

**Comment by Luis06** [comment] 2016-01-22 14:05
I was running on x64 Node.js. I supposed you asked me to try in x32 Node.js. I obtained similar results with it. I'm also using CommonJs (I don't know if it is important).

**Comment by mousetraps** [comment] 2016-01-23 02:41
You mentioned architecture, but what version of Node are you using? Is the issue specific to your project?

**Comment by Luis06** [comment] 2016-01-26 15:33
Thank you so much!!

I was using version v4.2.6 (x64). I'm sorry about my previous post but I must have reinstalled x64 version again because today when trying with v4.2.6 (x32) on Visual Studio it gave much more information. The correct call tree, funcions call, modules..So it currently works with x32 but not x64. 
There is still Unknown function names, but for the most part it works fine (see image). Also, in order to run profiling tools I had to create a standalone script and redirect to the build folder manually.

Despite this, I'm happy with the workaround and it works for me!

![52ca2698908034783b7768e2decae784c447c1815527ff25d0 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/10677677/12584893/8ab2b3cc-c441-11e5-9878-245e7c83ee3d.jpg)

**Comment by mousetraps** [comment] 2016-02-20 08:03
Awesome - closing as this looks like a duplicate of #434

**Closed by mousetraps** 2016-02-20 08:03 UTC
Labels: bug, need-more-info, profiling
