### ISSUE TITLE
No completions in REPL window when ES6 Mode is on

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1019] opened 2016-06-12 01:11 UTC
Using latest build from master (VS2015 U2, 6/11/2016)

**Expected**
REPL Window shows completions after `.` or `Ctrl-Space`

**Actual**
No completions are available

**Comment by mjbvz** [comment] 2016-06-13 18:50
Duplicate of #916

**Closed by mjbvz** 2016-06-13 18:50 UTC
Labels: duplicate, interactive-window
