### ISSUE TITLE
Node.js app with child_process fork() call failes with Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by eljamaki01** [Microsoft/nodejstools#575] opened 2015-10-30 20:50 UTC
Debugger listening on port 5858
 Error: listen EADDRINUSE
     at exports._errnoException (util.js:746:11)
     at Agent.Server._listen2 (net.js:1146:14)
     at listen (net.js:1172:10)
     at Agent.Server.listen (net.js:1257:5)
     at Object.start (_debugger_agent.js:20:9)
     at startup (node.js:86:9)
     at node.js:814:3

I have two files, the app.js file, and the code that the forked process will be running in sub.js. I copied this direcly from the official Node.js documentation -  https://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle_callback

// app.js
 var cp = require('child_process');

var n = cp.fork(__dirname + '/sub.js');

n.on('message', function(m) {
   console.log('PARENT got message:', m);
 });

n.send({ hello: 'world' });

// sub.js
 process.on('message', function(m) {
   console.log('CHILD got message:', m);
 });

process.send({ foo: 'bar' });

**Comment by kant2002** [comment] 2015-10-31 05:35
This is possible duplicate of #197

**Comment by eljamaki01** [comment] 2015-10-31 18:16
So, as it turns out, I can run my Mocha test from the command line and it runs fine.

From Visual Studio <Ctrl> F5 works. This only happens with F5 debug run!

**Comment by eljamaki01** [comment] 2015-10-31 20:34
Correction:
From Visual Studio <ctrl> F5 works. The error happens with F5 debug run!

**Comment by eljamaki01** [comment] 2015-11-01 04:02
Ok, for some reason, the way I was typing in control with angle brackets does not work.
From visual studio control-F5 works, but with just F5 debugging, it does not work. Something to do with the debug port being used twice.

**Comment by mousetraps** [comment] 2015-11-01 16:11
What happens when you run 'node --debug app.js' in the command line?

**Comment by eljamaki01** [comment] 2015-11-02 17:26
I get the same exact error when I run 'node --debug app.js' from the command line.

C:\TempENB\newsio\newsio>node --debug app.js
Debugger listening on port 5858
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Agent.Server.listen (net.js:1257:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3

**Comment by billti** [comment] 2015-11-02 22:33
Hmmmm, interesting. Looks like the same as the issue documented at https://github.com/nodejs/node/issues/3469 - namely the forked process gets the same arguments, and tries to open the same debug port.

As can be seen, this isn't an NTVS issue, you get the same error launching from the command-line. Not sure what NTVS can do at this point to address this.

**Comment by mousetraps** [comment] 2015-11-16 05:33
Closing this, as it appears to be a Node.js issue, rather than an NTVS issue.

**Closed by mousetraps** 2015-11-16 05:33 UTC
Labels: debugging, external

**Comment by neico** [comment] 2016-07-24 14:25
I can't believe that this was just disregarded as an external issue (especially since the exact same thing was reported earlier in #131), [while it's clearly NodeJSTools that's putting `--debug-brk=5858` into the command line](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Debugger/NodeDebugger.cs#L105).

[There's code](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Debugger/NodeDebugger.cs#L92) to increment the port if the default is already used, but it appears it's never triggered

I suspect that [this line](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Debugger/DebugEngine/AD7Engine.cs#L544) might be responsible for that

Basically it's overriding the `debuggerPort = null` part of the NodeDebugger constructor.

One way to solve this is to either rethink the logic in detecting if debuggerPort is defined (or has valid data).

Another one would be to make `--debug-brk` optional alltogether, by this I mean actually putting it into NodeExeArguments so the user can edit it out if he desires so.

This could be further improved by actually putting `--debug-brk` behind the Debug Configuration like I manually put inside my njsproj file (as you can't use the per configuration setting forms):
```
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <NodeExeArguments>--debug</NodeExeArguments>
    <Environment>DEBUG=1</Environment>
  </PropertyGroup>
```

What makes this issue so devestating when it comes to child processes is that there are packages that use childs workers, alas you can't just inject a new `execArgv` array to their `fork()`

And since NodeJSTools is injecting `--debug-brk` right before running the process you can't even hack around it by doing `process.argv = process.argv.slice( 0, 2 );` somewhere before the `fork()` calls

**Comment by mjbvz** [comment] 2016-07-28 01:13
@neico I'm still inclined to say that this is the expected behavior for node and not an NTVS issue. Can you please provide a step-by-step example that reproduces this issue, along with your expected behavior, and the actual behavior.

---

[Node using `process. execArgv` for the forked child is expected](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options), so the child should attempt to use the same debug port as at the parent process if no other actions are taken. But you can change `process.execArgv` before forking:

```js
process.execArgv =  ["--debug=9999"];
var n = cp.fork(__dirname + '/sub.js');
```

 or provide an explicit `execArgv` value:

```js
var n = cp.fork(__dirname + '/sub.js', [], {
  execArgv: ["--debug=9999"]
});
```

NTVS does pass`--debug-brk=X` when launching the main node file, but is not involved with forking child processes at all to my knowledge. The code you referenced doesn't get hit when forking.

**Comment by emilioriosvz** [comment] 2016-09-02 14:35
I have the same problem. Sometimes the vcode debugger does not finish successfully and leave busy the port

**Comment by mjbvz** [comment] 2016-09-02 19:49
@emilioriosvz Could you please explain the problem and your expected behavior a bit more?

If the port is already in use by a zombie process, you need to kill the process. You would hit the same issue when launching `node --debug` on its own too, so it's  not NTVS specific.

**Comment by emilioriosvz** [comment] 2016-09-03 09:15
@mjbvz The problem is, I'm working with the vcode debugger, and sometimes when I restart my project several times I got the `EADDRINUSE` error.

I tried to kill node, to restart vcode, to find this zombie process (I can't found them) ... but unsuccessfully, even killing the nodejs process.

The only solution I have is restart my machine or change the port to still working.
