### ISSUE TITLE
Solution explorer has empty spaces

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#628] opened 2015-12-08 11:52 UTC
![image](https://cloud.githubusercontent.com/assets/4257079/11655004/46af34ae-9dd4-11e5-9039-e94ca3ad644c.png)

Not sure is this NTVS or VS issue, but I see such thing very often in NTVS projects only, not in Cordova, ASP.NET 5, ASP.NET 4 projects

**Comment by yrtimiD** [comment] 2015-12-08 22:03
Confirm same issue in VS 2015.1

**Comment by billti** [comment] 2015-12-12 00:49
How often are you seeing this? On any specific projects, or just randomly? Any specific steps or setup that might help repro this.

I've never seen it. Unless I can repro, I don't fancy my chances of trying to figure it out just by looking at the code.

**Comment by kant2002** [comment] 2015-12-12 08:19
@billti  I seen this on the specific project. Maybe this is related to `gulp-tsc` configuration and the fact that it is configured to create temporary folder inside project. I will play to create small project which show the issue

**Comment by mousetraps** [comment] 2015-12-14 22:07
Yeah a repro would be great. This issue occurs when the project hierarchy gets corrupted in some way, but the project system is pretty complex and these issues are pretty much impossible track down without a solid repro.

**Comment by kant2002** [comment] 2015-12-17 10:31
1. Create console Node.js project
2. Add following `package.json`

```
{
  "name": "NodejsConsoleApp1",
  "version": "0.0.0",
  "description": "NodejsConsoleApp1",
  "main": "app.js",
    "author": {
        "name": "Andrey Kurdyumov",
        "email": "kant2002@gmail.com"
    },
    "dependencies": {
        "async": "^1.5.0",
        "body-parser": "^1.12.4",
        "colors": "^1.1.2",
        "compression": "^1.4.4",
        "express": "^4.12.4",
        "express-csv": "^0.6.0",
        "express-zip": "^2.0.0",
        "jsonwebtoken": "^5.0.2",
        "lwip": "^0.0.8",
        "mkdirp": "^0.5.1",
        "mssql": "^2.1.5",
        "passport": "^0.3.0",
        "passport-local": "^1.0.0",
        "ping": "^0.1.10",
        "sequelize": "^3.14.2",
        "sequelize-cli": "^1.8.2",
        "socket.io": "^1.3.7",
        "cookie-parser": "^1.4.0",
        "express-session": "^1.11.3",
        "session-file-store": "0.0.21",
        "tedious": "^1.11.2",
        "xlsx-template": "0.0.3"
    },
    "devDependencies": {
        "gulp": "^3.9.0",
        "gulp-load-plugins": "^1.0.0-rc.1",
        "gulp-tsc": "^1.1.4",
        "require-dir": "^0.3.0",
        "typescript": "^1.7.3"
    }
}
```

3. In the 'Solution Explorer' enable 'Show All files'
4. Run Install Missing packages

That likely should be enough. But in case if this is not the 100% reproduced, I add compilation using `gulp-tsc` which shake NodeJS project hierarchy. Basically it just create temp folder during compilation which is removed, but that enough for issue to be reproduced.

![image](https://cloud.githubusercontent.com/assets/4257079/11867315/94d96246-a4da-11e5-8a0e-39cd99322493.png)

Attached the full project with which you could play with issue.
http://www.filedropper.com/issue-628

Also this package.json configuration is bring my VS instance on the knees.

**Comment by mjbvz** [comment] 2016-04-21 21:17
Just ran across this problem. One trigger is the `node_modules` folder when not being included in the project. Repo steps:

* Have a node modules folder excluded in the project but shown in the explorer.
*  Have a `mocha` install in `node_modules`, but not listed in the `package.json`
* In NTVS, run `$ npm install mocha --save`
* Now there are two `node_modules` folders

![image](https://cloud.githubusercontent.com/assets/12821956/14724503/6b633564-07cb-11e6-83cb-a529b206ed82.png)

* Collapse the parent node and expand again. Now there is an empty space where the empty `node_modules` used to be

![image](https://cloud.githubusercontent.com/assets/12821956/14724505/7612d8fc-07cb-11e6-874e-4c42cf3579c9.png)

**Comment by kant2002** [comment] 2016-07-23 13:48
@mjbvz Any news on this issue? If you know root cause, or remember it, you could point me why it is happens and I could fix that myself.

**Comment by mjbvz** [comment] 2016-07-27 17:49
Feel free to investigate this issue. I do not know what the root cause is.

I recommend trying the repo I provided or seeing If you can find an easier repo for the issue. Then debug and look to see how nodes are being added or removed from the hierarchy. [NodeJsFolderNode](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Project/NodejsFolderNode.cs), [NodeJsFileNode](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Project/NodejsFileNode.cs), and [NodeJsProjectNode](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Project/NodejsProjectNode.cs) are probably good starting points, along with their base classes.

**Comment by paulvanbrenk** [comment] 2018-07-23 19:51
I haven't encountered this anymore in VS 2017. Closing as we're not likely to fix this using the existing project system

**Closed by paulvanbrenk** 2018-07-23 19:51 UTC
Labels: bug, project-system, test-adapter, up-for-grabs
