### ISSUE TITLE
Autobrace completion doesn't seem to work on .js files in Node projects.

### ISSUE THREAD

**Issue by balajikris** [Microsoft/nodejstools#1338] opened 2016-10-13 21:13 UTC
##### Expected Behavior 
Auto Brace completion works
##### Actual Behavior 
No brace completion

- NTVS Version: 1.2.40726.00
- Visual Studio Version:  VS 2015, update 3 25431.01
- Node.js Version: v6.6.0

##### Steps to Reproduce

1. Tools -> Options -> text editor -> javascript -> automatic brace completion turned on
2. File -> New Project -> Javascript -> Node.js -> From existing Node.js code
3. In index.js type a function, then type a brace
4. No brace completion, see screenshot below
5. This happens for all tokens - ( { [ ' "

Additional info: have viasfora extension to colorize braces, but turning that off doesn't seem to make a difference.

![image](https://cloud.githubusercontent.com/assets/4213867/19363124/0dd869ee-913e-11e6-8563-8cce89132a39.png)

**Comment by mjbvz** [comment] 2016-10-17 20:50
Thanks for the report. This looks like a duplicate of #1142 to me. 

To summarize: NTVS 1.2 moved to use the TypeScript editor for node file by default. This brought a few regressions in functionality, such as the loss of auto brace completion, but also gives us a much more stable editor that provides a much better overall experience. The Typescript team is aware of these regressions and is working to fix them.

Auto brace completion is [now available](https://github.com/Microsoft/TypeScript/issues/1484#issuecomment-245333904) in [Typescript 2.0 or later](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/). To enable it, make sure you have Typescript 2.0+ installed and make sure `Tools -> Options -> text editor -> Typescript` has auto brace completion turned on. You should now see brace completion in your node JavaScript files.

Please let me know if you run into any trouble getting this working.

Thanks.

**Closed by mjbvz** 2016-10-17 20:50 UTC
Labels: duplicate, editor

**Comment by balajikris** [comment] 2016-10-17 20:55
@mjbvz Thanks for the pointer, I'll try that out.

**Comment by balajikris** [comment] 2016-10-17 22:28
@mjbvz -- Thanks, that worked for me. 👍
