### ISSUE TITLE
Update npm Package option does not update dev dependencies

### ISSUE THREAD

**Issue by Mikejo5000** [microsoft/nodejstools#2129] opened 2019-01-29 23:23 UTC
##### Expected Behavior 
1. Update a npm package version in package.json devDependencies
2. Right-click on the package in Solution Explorer, choose Update npm Package.
3. Package gets updated

##### Actual Behavior 
Package does not get updated

- NTVS Version: 1.5.1228.1
- Visual Studio Version: Dev16
- Node.js Version: 10.13.0

##### Steps to Reproduce
1. Update a npm package version in package.json devDependencies
2. Right-click on the package in Solution Explorer, choose Update npm Package.
3. Check whether package version was updated.

**Comment by amcasey** [comment] 2019-04-05 21:03
@uniqueiniquity Can you please check whether there's a reason we're not doing this?  It seems intuitively reasonable.

**Comment by rakatyal** [comment] 2019-07-16 21:35
@Mikejo5000: I played around with this today and could repro the behavior, however I verified that npm itself behaves the same way so it may be that 'npm update' isn't supposed to be used this way. Kindly verify my investigations by these 2 workflows and let me know if you observe the same. 

1. If I do not update the package.json file (keep it same as the version installed) to the new version and then run 'Update npm package' from the solution explorer, it does update the package to the latest version and also update the 'package.json' file to reflect the same. If you look at the logs in the 'Output' window inside VS and filter it to show output from 'Npm', you can see what command VS executed for this action. In this case it should say 'npm update <package_name> --save'. 

2. If I try your workflow and update the package.json file with a newer version and then run the 'Update npm package' it doesn't do anything. But if you notice the output window again, you would notice that the command executed by npm is the same as (1). 

I believe the problem is that when you update the package.json file beforehand, npm fails to pick it as a package to be updated and hence nothing happens. The correct workflow here is to do this directly from the solution explorer *without* modifying package.json beforehand, which is what I did in (1). 

I also verified this by trying the 'npm outdated' command. It should list all the packages that can be updated in your project and basically tells you what will happen if you run 'npm update'. Try this command in workflows (1) and (2). You should notice that (1) will list you the package you wish to update but (2) would not. 

Please let me know what you find!

**Comment by rakatyal** [comment] 2019-07-30 17:37
I made the experience better in the referenced PR above. Closing this issue. Kindly re-open if you have further comments.

**Closed by rakatyal** 2019-07-30 17:37 UTC

**Comment by Mikejo5000** [comment] 2019-07-30 18:17
Looks good. Thanks!
