### ISSUE TITLE
Exception upon opening

### ISSUE THREAD

**Issue by John0x** [Microsoft/nodejstools#1194] opened 2016-08-05 12:22 UTC
Hey, I have visual studio 15 preview 3 and installed the newst version of ntvs.
 7-24-2016 Dev Build 

I get the following error upon opening a node.js project:
``` xml
<entry>
    <record>536</record>
    <time>2016/08/05 12:19:58.376</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.DllNotFoundException: Die DLL &quot;ChakraCore.dll&quot;: Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.ChakraCoreEngine.JsCreateRuntime(JavaScriptRuntimeAttributes attributes, JavaScriptThreadServiceCallback threadService, JavaScriptRuntime&amp; runtime)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.ChakraCoreEngine.CreateRuntime(JavaScriptRuntimeAttributes attributes, JavaScriptThreadServiceCallback threadService, JavaScriptRuntime&amp; runtime)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.JavaScriptEngine..ctor(String text, String url, INativeEngine nativeEngine)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.TryAddLexicalClassifications(String lineText, Int32 lexState, Int32 offset, TypeScriptLexicalClassificationMap classificationMap, ITextSnapshot snapshot, List`1 tagSpans, Int32&amp; newEndOfLineState)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.AddLexicalClassifications(ClassifierProxy classifier, String text, Int32 lineNum, Int32 offset, ITextSnapshot snapshot, List`1 tagSpans)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 result)&#x000D;&#x000A;   bei Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
```

**Comment by mjbvz** [comment] 2016-08-05 16:30
Thanks. We use Typescript to power our IntelliSense and I suspect that Typescript is the root cause here (although we may be triggering it somehow and I didn't know ChakraCore was something Typescript depended on).

Can you please share which version Typescript you have installed for VS? This is under `Help-> About Microsoft Visual Studio`. If you can share more info, the entire list of installed extensions and versions may be helpful too. Just use the `copy info` button on the `about Microsoft Visual Studio Screen`.

**Comment by John0x** [comment] 2016-08-05 17:01
Sure, here you go:

````
Microsoft Visual Studio Enterprise 15 Preview 3
Version 15.0.25428.1 PREVIEW
Microsoft .NET Framework
Version 4.6.01586

Installierte Version: Enterprise

Architecture and Modeling Tools   
Microsoft Architecture and Modeling Tools
    
UML® und Unified Modeling Language™ sind Marken oder eingetragene Marken der Object Management Group, Inc. in den Vereinigten Staaten und anderen Ländern.

Visual Basic 15 Preview 3  
Microsoft Visual Basic 15 Preview 3

Visual C# 15 Preview 3   
Microsoft Visual C# 15 Preview 3

Visual C++ 15 Preview 3   
Microsoft Visual C++ 15 Preview 3

Allgemeine Azure-Tools   1.7
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

Application Insights-Tools für Visual Studio-Paket   8.0.60607.2
Application Insights-Tools für Visual Studio

ASP.NET and Web Tools 2016   15.0.20317.0
ASP.NET and Web Tools 2016

ASP.NET Web Frameworks and Tools 2013   5.2.40316.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.2   15.0.20316.0
Azure App Service Tools v2.8.2

Code alignment   12.1
Code alignment helps you present your code beautifully, enhancing clarity and readability.

CodeMaid   10.1.93
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

CodeRush for Roslyn   16.1.4.0
DevExpress CodeRush for Roslyn package.

devCmd   1.0
Open Visual Studio Developer Command Prompt from Visual Studio IDE, Execute Commands directly from IDE, Can be acced from Tools Menu, Solution Explorer, Toolbar.

Image Optimizer   3.6.93
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

JavaScript-Sprachdienst   2.0
JavaScript-Sprachdienst

JavaScript Project System   2.0
JavaScript Project System

Markdown Editor   1.6.133
A full featured Markdown editor with live preview and syntax highligting. Supports GitHub flavored Markdown.

Microsoft .NET Core Tools   15.0.20317.0
Microsoft .NET Core Tools

Node.js Tools   1.2.40727.01
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40727.01
Profiling support for Node.js projects.

NuGet-Paket-Manager   3.4.2
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter "http://docs.nuget.org/".

Package Installer   1.8.85
Makes it easier, faster and more convenient than ever to install Bower, npm, JSPM, TSD, Typings and NuGet packages to any project

Parallel Debugger   1.0
Concurrency debugging

SQL Server Data Tools   15.0.60611.0
Microsoft SQL Server Data Tools

TypeScript   1.9.0.0
TypeScript-Tools für Visual Studio

Visual Studio-Tools für Apache Cordova   Update 10
Visual Studio-Tools für Apache Cordova

Visual Studio Tools für Universelle Windows-Apps   15.0.25302.00
Mit den Visual Studio Tools für Universelle Windows-Apps können Sie eine universelle App-Erfahrung erstellen, die auf jedem Gerät genutzt werden kann, das Windows 10 ausführt: Smartphone, Tablet, PC und viele weitere Geräte. Das Microsoft Windows 10 SDK ist in den Tools enthalten.
````

**Comment by mjbvz** [comment] 2016-08-05 17:38
Thanks. After more searching, I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/9572

This should be fixed in the next preview, but until then, try the [workaround from the issue](https://github.com/Microsoft/TypeScript/issues/9572) copying chakracore.dll into `C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript`

**Closed by mjbvz** 2016-08-05 17:38 UTC
Labels: external

**Comment by John0x** [comment] 2016-08-05 18:01
Sadly I don't have a vs 2015 installation. Gotta wait then
