### ISSUE TITLE
VS 2015 crashes when cutting collapsed text

### ISSUE THREAD

**Issue by elmojo** [Microsoft/nodejstools#343] opened 2015-08-02 01:41 UTC
My VS 2015 crashes when I try to cut collapsed text.  Sometimes it works but most times it crashes Visual Studio.

Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Professional

**Comment by mousetraps** [comment] 2015-08-02 02:48
Thx for reporting this. Unfortunately I can't reproduce so we'll need a little more info to figure it out. Since VS crashed, there should be a corresponding entry in the Windows event log. Mind grabbing the details from there?

**Comment by elmojo** [comment] 2015-08-02 03:32
Here you go.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
Stack:
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextContentLayer.UpdateTextVisuals()
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextContentLayer.ArrangeOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.ArrangeCore(System.Windows.Rect)
   at System.Windows.UIElement.Arrange(System.Windows.Rect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54504ade
Exception code: 0xe0434352
Fault offset: 0x00014598
Faulting process id: 0x2d98
Faulting application start time: 0x01d0ccc4556f2425
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: bb66a61d-38b7-11e5-827d-9ae5f29e0900
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mousetraps** [comment] 2015-10-10 23:46
Hmm, we don't handle copy commands in any special way, and this looks like a general VS issue based on the trace... are you able to share any code that reproduces the issue consistently?

**Comment by mousetraps** [comment] 2015-11-16 06:12
Closing this issue as it doesn't appear to be NTVS-related, and we haven't received any more info that might help us diagnose. Let us know if you can provide a sample project or some other piece of info, and / or whether this is still broken in VS Update 1 RC or RTW when it's released, and we can re-open.

**Closed by mousetraps** 2015-11-16 06:12 UTC
Labels: bug, crash-or-hang, editor, external, need-more-info
