### ISSUE TITLE
TypeScript debugging does not seem to work with Node.js 0.12.2

### ISSUE THREAD

**Issue by irakliy81** [Microsoft/nodejstools#94] opened 2015-05-03 19:07 UTC
I've recently updated Node.js version from 0.10.38 to 0.12.2 and dubbing TypeScript files seems to have broken. The message I get when hovering over a breakpoint is:

`This breakpoint will not currently be hit. No code has been loaded for this location`

As soon as I revert back to 0.10.38 - everything works fine again.

Info about the environment:

* VS: Community 2013 Update 4
* NTVS: 1.0 (although the same thing happens with 1.1Beta)
* Node.js: tried both 32 and 64-bit MSI installers

Additional note: my environment is set up to compile all TypeScript files into \bin directory

**Comment by mousetraps** [comment] 2015-05-03 19:17
Hmm... unfortunately I can't reproduce this issue. Would it be possible to provide a sample app where the issue occurs? You can email it to ntvshelp at microsoft if you don't want to share it publicly.

**Comment by irakliy81** [comment] 2015-05-03 19:53
Sure thing! I've created a test app that has the same problem. I've zipped up the project folder (excluding node_modules) and you can get the zip file here:

https://onedrive.live.com/?cid=b4431af732931785&id=b4431af732931785%2112864&ithint=file,zip&authkey=!AB_mPNE5GQXD-qE

As you'll notice, there are 2 files:
* app.ts - breakpoints in this file are being hit as expected
* routes\index.ts - breakpoints in this file are not hit

Thanks!

**Comment by nippur72** [comment] 2015-07-06 11:40
I experience the same bug. 

It seems that server code is being debugged correctly, while client code running on the browser is not debugged for some reason.

Also, if I force debugging with the instruction `debugger;` on a client script, the IE browser asks for opening a new instance of VS2015, where debugging seems to work (source maps loaded, stepping in breakpoints, etc..)

**Comment by mousetraps** [comment] 2015-07-06 11:43
@nippur72  are you sure this is the same issue? We don't actually support browser-side debuggin in NTVS, but check out our docs for a recommended workflow
https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS#debugging

**Comment by nippur72** [comment] 2015-07-06 11:57
@mousetraps sorry, you are right, it's not the same issue. 

And thank you for the link, I've been searching the whole day how to debug both client and server in node, but haven't found anything and so I started to think it was because of this bug!

**Comment by zhengbli** [comment] 2015-08-31 21:11
The onedrive link seems expired. Can you share the files again?

**Comment by billti** [comment] 2015-09-11 21:43
Any progress on this? @zhengbli did you try to reproduce based on the info given? If it worked fine for you, and we don't have any further info to go on at this point, we should close this for now.

**Comment by zhengbli** [comment] 2015-09-11 21:53
I couldn't download the file because the onedrive link @irakliy81 provided expired. Though on my own simple test (VS 13 and VS 15), I can set breakpoints fine:
![1](https://cloud.githubusercontent.com/assets/1171301/9827208/d14fd314-5894-11e5-908f-a1ea54439d0e.PNG)

**Comment by mousetraps** [comment] 2015-09-12 01:39
Are you compiling the TS files into a single directory?

**Comment by mousetraps** [comment] 2015-09-16 19:21
@zhengbli also it looks like this entire scenario is blocked because of #322, so maybe that's why we can't reproduce (I can't actually get the project to compile to the output directory)

**Comment by zhengbli** [comment] 2015-09-17 20:18
I did compile the TS files into a single directory "bin", if the following configuration is the :
![capture](https://cloud.githubusercontent.com/assets/1171301/9944597/33c026e6-5d3d-11e5-9e94-135260f0bca5.PNG)
(also both vs 13 and vs 15 under node v0.12.2)]

Oddly regarding #322, the "redirect JavaScript output to directory" is working fine for me (both vs 13 and 15). There is no compiled app.js in the same path as app.ts, instead it showed up under "bin" folder. I'm on NTVS build 30910.02

**Comment by zhengbli** [comment] 2015-09-17 20:52
Ah, I got a repro finally, though only on the ts files one level below the root path (namely in a folder). The issue happens for v0.12.2, v0.12.7, but not for the recently merged nove v4.0

**Comment by zhengbli** [comment] 2015-09-17 21:00
This looks like a sourcemap issue. Because when I set breakpoints on the ts file, the breakpoint wouldn't hit; however if I set breakpoints on the compiled js file in the same folder, the breakpoint hits on the ts file.

**Comment by mousetraps** [comment] 2016-04-05 09:44
closing as it's been a while and we've significantly improved the debugging experience since. Please verify that the issue is resolved in the latest release (if not, we'll re-open): https://github.com/Microsoft/nodejstools/releases

**Closed by mousetraps** 2016-04-05 09:44 UTC
Labels: bug, debugging, typescript, up-for-grabs
