### ISSUE TITLE
Install appears to be stuck 

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#306] opened 2015-07-21 17:48 UTC
Installing 1.1 for VS 2015 RTM on Windows 10240 via the VS extensions tool it took a very long time at the updating registration stage. I was about to cancel. I had to close VS manually first

**Comment by mousetraps** [comment] 2015-07-21 17:54
Interesting... This is our first time using the gallery for releases so there may be some kinks to be worked out. The installer didn't ask you to close VS first?

**Comment by mousetraps** [comment] 2015-07-21 20:45
I just tried it, and can't reproduce the behavior you ran into. Can you provide some more details about how you launched the installer? Did a dialog pop up in the beginning asking you to close VS?

**Comment by SteveALee** [comment] 2015-07-22 09:31
So I installed VS 2015 RC (though some comps like Android emulator left around) and installed RTM. Can recall if uninstalled node tools. Then Tools -> Extensions Updates search "node" and install 1.1 RC for 2015. Yes I'm pretty sure I closed VS so could continue. Sorry for being so vague.

I wonder do you install node? I didn't follow any links for node as you suggest in your natty little video :) But Latest node *is* installed. I can't recall if I did this before or was done by previous node tools install.

I just tried to uninstall node tools and reinstall from gallery. But all 3 Node tool items have Disable and Unistall buttons disabled

**Comment by GotCode** [comment] 2015-07-24 01:44
I ran into the same situation.  The VTVS 1.1 RC - MSI package installs with VS2015 CTP 6 on Windows 10 Enterprise (10161).  The installer is stuck at the stage "Updating extension registration with Visual Studio.."  (I waited for over an hour without any progress)
![ntvs1 1 stuck](https://cloud.githubusercontent.com/assets/586999/8865882/8aded642-316a-11e5-89be-6ce07e34d9c0.png)

**Comment by SteveALee** [comment] 2015-07-24 06:15
I had vs 2015 Pro from MSDN subscriptons. I took 20 mins or so.

**Comment by mousetraps** [comment] 2015-07-25 00:39
Okay, thanks for the additional info. At this step, we are running ```devenv /setup```, which is the longest setup step. If you can reproduce the issue, can you verify in process explorer that devenv /setup is indeed running throughout the duration of this step?
![image](https://cloud.githubusercontent.com/assets/762848/8887044/58168eb6-3229-11e5-969c-8e882f8c7d1a.png)

@SteveALee how long were installs taking for you before? (it varies per machine) Also were you performing an upgrade? If so, this would effectively double setup time because we run devenv /setup twice (see #315, just filed an issue to prevent this.) 

In the past, while remoting into a slow machine, I've run into an issue where install appeared stuck on that step until I brought the installer window into the foreground, but was never able to reproduce it, so it may be related.

@GotCode we really can't vouch for CTP 6 (many issues have been fixed in VS since then, and the latest versions of NTVS were built using the RTM bits)

**Comment by SteveALee** [comment] 2015-07-25 20:00
I was likely updating from 1.0 as it appears uninastalling leaves Vs leaves extensions around. I'll try to uninstall nt4vs in control panel so can try to reproduce.

Indeed the install moved again once I activated a few Windows including the install.

**Comment by SteveALee** [comment] 2015-07-27 14:16
OK, It doesn't reproduce for me. Though it does sit at the noted step for a short while. 

I uninstalled NT4VS 1.1 using Windows Remove Programs. Then Select installed and close VS. Note VS can't be closed by the installer as the Extensions/Update dialog is open. So the installer had already got to the place where it stuck before.

**Comment by billti** [comment] 2015-08-20 18:54
It could take up to 20 mins on a slow machine due to VS needing to rescan after components are installed. Are you still seeing this on VS 2015 RTM and the latest NTVS builds?

I'll close this for now, if this is encountered again please reopen and attached the setup logs (the dd* files from under %LOCALAPPDATA%\Temp).

**Closed by billti** 2015-08-20 18:54 UTC
Labels: bug, installation

**Comment by enicolasWebs** [comment] 2015-09-01 21:04
I am seeing this on the latest builds for VS 2013.  I'm on a fast machine and the installer continues to hang at that step after 20 minutes..

**Comment by enicolasWebs** [comment] 2015-09-02 18:29
I let the installer run overnight, and the install completed.  Strange, I've got a pretty fast machine but at least it completed :)  Great plugin all, loving it so far !

**Comment by jmistx** [comment] 2016-09-20 09:07
Same problem for me. 
Installing 1.2 for VS 2015 Update 3
It looks like installation stuck and there is no possibility to understand how much time this step will consume. 
![image](https://cloud.githubusercontent.com/assets/5122685/18664146/1bda8e44-7f2a-11e6-8db4-3a41b9990e6d.png)
