### ISSUE TITLE
VS 2015 exception caused by extension

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#371] opened 2015-08-17 06:28 UTC
![image](https://cloud.githubusercontent.com/assets/4515120/9299208/929ad258-44f4-11e5-9ac0-defdde748f9a.png)

and yet I can't get anything from the activitylog.xml

**Comment by billti** [comment] 2015-08-20 18:22
Do you see any errors in the Application Event log (in Windows Event Viewer)? When you say you can't get anything from the log, do you mean it doesn't even exist? You can't open it? It's empty?...

Also, some information on what you were doing when the exception occurred would be helpful. Are you sure this is an NTVS issue as opposed to some other extension?

**Comment by alanpurple** [comment] 2015-08-21 07:08
@billti  yeah I'm not so sure but it was  a clean  Windows10 x64 pro -> VS2015 Enterprise -> plugin(native recommended by Microsoft) -> NTVS installation

**Comment by MarioLiebisch** [comment] 2015-08-24 10:23
Having the same error and loading seems to take forever during "Loading cached Node.js analysy for project...", even if I delete all sub folders in my project dir (just keeping solution + project file).

ActivityLog's last entry reads (tried to make the formatting more readable):

> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.NodejsTools.SmartIndentProvider". ---> System.InvalidOperationException: Sequence contains no elements at System.Linq.Enumerable.First[TSource][](IEnumerable`1 source) at Microsoft.NodejsTools.SmartIndentProvider..ctor(IEditorOptionsFactoryService editorOptionsFactory, Lazy`2[] classifierProviders) --- End of inner exception stack trace --- at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue() at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create() at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState) at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState) at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata](Object errorSource, Lazy`2 provider)

**Comment by ernestabrahams** [comment] 2015-08-27 20:33
Repairing Visual Studio brought back the test explorer window. Not sure about the cause but can share my activity log if needed.

**Comment by billti** [comment] 2015-08-27 21:59
Normally when you see an error containing "CompositionFailedException" it is due to the extension cache being out of date or corrupt. After installing any new component, it should rebuild this by scanning the file system (and caches it to avoid needing to do it on every launch).

One way to force this to be rebuilt is:
1) Delete the contents of the folder at "%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\ComponentModelCache"
2) Run "DevEnv.exe /setup" (this is under "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE", but should be on your PATH if you open a Developer Command Prompt).

Next time you launch VS it will take a while to rebuild (which may be part of the delay above), but should resolve any MEF errors.

@MarioLiebisch can you try this and let us know if this resolves error?

**Comment by ernestabrahams** [comment] 2015-08-29 09:16
Updating the NuGet Package Manager prompted an error on start-up. 
This update had been removed when VS was repaired (earlier - and on separate virtual machines).
Seems to have stabilised now. @billti Thanks for the tip!

![image](https://cloud.githubusercontent.com/assets/8538803/9561248/482b917c-4e35-11e5-856b-bddbc0ee1bd7.png)

![image](https://cloud.githubusercontent.com/assets/8538803/9561249/540e4566-4e35-11e5-91c2-0fdc6d932bca.png)

```
<errorinfo>
Could not load file or assembly 'Microsoft.VisualStudio.Azure.ResourceManager.Contracts.1.0, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified.
</errorinfo>
```

**Comment by billti** [comment] 2015-09-11 18:44
Looks like this was a MEF issue caused by some other component. Closing until we can get more info that helps point to an NTVS issue.

**Closed by billti** 2015-09-11 18:44 UTC
Labels: need-more-info

**Comment by MarioLiebisch** [comment] 2015-09-16 14:18
> @MarioLiebisch can you try this and let us know if this resolves error?

Oh, completely missed that question. Yes, it seems like this did the trick.

**Comment by alanpurple** [comment] 2015-09-16 14:19
I haven't seen this error since RC2

**Comment by ElPumpo** [comment] 2017-03-25 17:31
Having the same issue but only occures when installing the official GitHub plugin for VS2015. Thanks for the fix dude.
