### ISSUE TITLE
console does not close on exit when debugging

### ISSUE THREAD

**Issue by panlina** [Microsoft/nodejstools#818] opened 2016-04-03 07:23 UTC
Suppose I create a project from the Blank Node.js Console Application template, which contains only a `console.log();` statement. When I press F5 to debug it, the console window does not close after the message is printed. However, when I Ctrl+F5(Start Without Debugging), it closes just like running in a standalone Node environment.
It is a different behavior from that in a c++ or c# project in Visual Studio. Is it because of some technical reason?
Once I saw a question about this on SO, but cannot find it now.

**Comment by yisk** [comment] 2016-04-03 08:10
I think Node.js app simply closes when it has nothing to do. Add any infinite listener and your code will run forever. For example:
```javascript
require('http').createServer().listen(3000, '127.0.0.1');
```
Visual Studio debugger for Node.js is the same endless listener.

**Comment by panlina** [comment] 2016-04-03 10:59
@yisk can't the debugger just terminate as the debugged program terminates?

**Comment by mjbvz** [comment] 2016-04-04 18:15
Looks like a duplicate of #89 which seems like an external Node issue. We plan on revisiting this at some point to see if there are better work arounds for newer Node releases.

**Closed by mjbvz** 2016-04-04 18:15 UTC
Labels: duplicate
