### ISSUE TITLE
When removing debugger VS crash

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#617] opened 2015-11-27 18:23 UTC
When I run TS NodeJS app and remove breakpoint which was set on the older version of code(at least I suspect this is the cause), VS is crashing.

Here more info about crash. 

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at Microsoft.NodejsTools.Debugger.DebugEngine.AD7Engine.OnBreakpointBound(System.Object, Microsoft.NodejsTools.Debugger.BreakpointBindingEventArgs)
   at Microsoft.NodejsTools.Debugger.NodeDebugger.HandleBindBreakpointSuccess(Microsoft.NodejsTools.Debugger.NodeBreakpointBinding, Microsoft.NodejsTools.Debugger.NodeBreakpoint)
   at Microsoft.NodejsTools.Debugger.NodeDebugger+<BindBreakpointAsync>d__85.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.Extensions+<WaitAsync>d__6`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger+<>c__DisplayClass66_0+<<AddModules>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient+<RunWithRequestExceptionsHandled>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by billti** [comment] 2015-12-11 22:26
Can you clarify the repro steps a little more for me? What would I need to do on my end to try and reproduce and debug this issue? What does "set on an older version of the code" mean?

**Comment by kant2002** [comment] 2015-12-12 08:47
@billti Here the steps which what happens. Not 100% sure since it was ago.

1. Set breakpoint on some portion of TS code.
2. VS freeze
3. Run project from console. and discover issue. Stop the webserver.
4. Go to VS Code to quickly change offending code.
5. Compile outside VS using gulp
6. VS unfreeze
7. Run project from within VS.
8. Crash.

I very often go to VS Code for quick fixes, since NTVS is constantly freezing. And to not interrupt my flow, I take any editor which do the job.

**Comment by mousetraps** [comment] 2016-03-15 23:04
Unfortunately I wasn't able to reproduce this with the steps provided , so closing this for now, but lmk if you're still running into issues here.

**Closed by mousetraps** 2016-03-15 23:04 UTC
Labels: bug, crash-or-hang, debugging, need-more-info

**Comment by balajikris** [comment] 2016-09-26 18:47
Hi, I'm still seeing this with NTVS 1.2 on VS2015. ran into this twice in the last week (9/23/16)

Not sure precisely what operation i was doing (adding or removing a bp), but in general i was debugging.

I couldn't quite get a dump, but i did notice watson reporting show up. So, its possible watson reports _may_ have a dump. Let me know if I could help somehow getting a repro for this.

~~~
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at Microsoft.NodejsTools.Debugger.DebugEngine.AD7Engine.OnBreakpointBound(System.Object, Microsoft.NodejsTools.Debugger.BreakpointBindingEventArgs)
   at Microsoft.NodejsTools.Debugger.NodeDebugger.HandleBindBreakpointSuccess(Microsoft.NodejsTools.Debugger.NodeBreakpointBinding, Microsoft.NodejsTools.Debugger.NodeBreakpoint)
   at Microsoft.NodejsTools.Debugger.NodeDebugger+<BindBreakpointAsync>d__85.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.Extensions+<WaitAsync>d__0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger+<>c__DisplayClass66_0+<<AddModules>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient+<RunWithRequestExceptionsHandled>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

~~~
