### ISSUE TITLE
Breakpoints not working unless debugger statement is present in source file

### ISSUE THREAD

**Issue by enicolasWebs** [Microsoft/nodejstools#564] opened 2015-10-22 21:32 UTC
I'm using the latest commit (fb5c884fccfa204e4d1a12fd12132f716a3ee2f0 ) and I'm noticing that I can't hit breakpoints on a file unless I write an explicit "debugger;" statement in the file and then I can hit alternate breakpoints within that file.  Is this a known issue ?

**Comment by mousetraps** [comment] 2015-10-22 21:36
No, it's not a known issue. Does it occur in every file? Even a basic hello world app?

**Comment by enicolasWebs** [comment] 2015-10-22 21:40
Not sure, I'll try it out now...

**Comment by mousetraps** [comment] 2015-10-22 21:46
Awesome thanks - if we can get a repro, we can try and track it down. Also worth turning on the Live Diagnostics pane, which helps us diagnose issues in the even that they aren't easy to reproduce. See this comment for more details:
https://github.com/Microsoft/nodejstools/issues/246#issuecomment-127715686

**Comment by enicolasWebs** [comment] 2015-10-22 21:52
Breakpoints work fine on a basic hello world app so didn't get a repro there.  Here are the diagnostic logs from when I do get the breakpoint set error & then when I get a successful breakpoint set (appears to raising this AD7BreakpointErrorEvent on failure)...
[21:50:53.9853486] DebuggerConnection: Request: {"command":"setbreakpoint","seq":13,"type":"request","arguments":{"line":71,"column":0,"type":"script","target":"C:\\vp\\git\\LocalListings\\routes\\authentication.js"}}
[21:50:54.0233486] DebuggerConnection: Response: {"seq":855,"request_seq":13,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":8,"script_name":"C:\\vp\\git\\LocalListings\\routes\\authentication.js","line":71,"column":0,"actual_locations":[]},"refs":[],"running":true}
[21:50:54.0253486] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7BreakpointErrorEvent (abb0ca42-f82b-4622-84e4-6903ae90f210)
[21:51:18.4133486] AD7Engine Called CreatePendingBreakpoint
[21:51:18.4133486] NodeDebugger Called Set Breakpoint
[21:51:18.4133486] DebuggerConnection: Request: {"command":"setbreakpoint","seq":14,"type":"request","arguments":{"line":7,"column":1,"type":"script","target":"d:\\vp\\git\\LocalListings\\routes\\crossSellOffer.js"}}
[21:51:18.4913486] DebuggerConnection: Response: {"seq":856,"request_seq":14,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":9,"script_name":"d:\\vp\\git\\LocalListings\\routes\\crossSellOffer.js","line":7,"column":1,"actual_locations":[{"line":7,"column":1,"script_id":700}]},"refs":[],"running":true}
[21:51:18.4983486] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7BreakpointBoundEvent (1dddb704-cf99-4b8a-b746-dabb01dd13a0)

**Comment by mousetraps** [comment] 2015-10-23 17:24
Can you describe the code that reproduces the issue? Or better yet, any chance you could share a small sample project?

**Comment by Earl-Brown** [comment] 2016-03-25 21:42
I had a problem like this a long time ago when debugging with chrome and node-inspector.  I always figured it was a Chrome bug.

**Comment by mjbvz** [comment] 2016-04-19 21:28
Closing since we need more info to take action. @enicolasWebs Please reopen if the original problem is still occurring for you.

Anyone experiencing a similar problem should open a new bug.

Thanks

**Closed by mjbvz** 2016-04-19 21:28 UTC
Labels: bug, debugging, need-more-info
