### ISSUE TITLE
Unsuportted Project Subtype

### ISSUE THREAD

**Issue by berni69** [Microsoft/nodejstools#1208] opened 2016-08-16 15:22 UTC
I'm trying to load a node.js project into VS2015 Update 3, i'm getting the following error:

```
There is a missing project subtype.
Subtype: '{3AF33F2E-1136-4D97-BBB7-1795711AC8B8}' is unsupported by this installation.
```

Versions:
- Windows 8.1 Spanish Version
- NTVS Version: NTVS 1.2 VS2015
- Visual Studio Version: VS2015 Update 3 Comunity edition
- Node.js Version: v5.10.1
##### Steps to Reproduce
1. In order to reproduce the error you can clone the repo: https://github.com/berni69/BootstrapTreeNav
2.  And open it with VS2015

With other versions of VS2015 and nodejstools this project is working 

It also happens if I try to create a new project.

I tried to reinstall VS2015, NTVS, and .Net Core Tooling 1.0.0 Preview 2, but I'm still getting the same error.

**Comment by mjbvz** [comment] 2016-08-16 17:44
It looks like VS doesn't know about the NTVS project type guid. A few questions to help with the investigation:

1. Is NTVS listed in the installed extensions for VS? This is under `Tools -> Extensions and Updates`

2. Do you see any messages in the `ActivityLog.xml` file? This can be found in `%appdata%\Microsoft\VisualStudio\14.0` by launching VS with the `/log` option. Open a the vs developer command prompt and run `devenv /log`. Repo the problem and then check the log for any messages about node or ntvs.

Also, to unblock yourself, there are a few things you can try.

First, try opening the VS developer command prompt in administrator mode and try running `devenv /setup /clearCache /allowDuringSetup`. This will reset some internal visual studio caches. The problem may just be that NTVS somehow got into a bad state.

If that fails, you can try going to `%localappdata%\Microsoft\VisualStudio\14.0`, deleting the entire `ComponentModelCache` file, and then launching VS.


Let me know if either of those works. Thanks.

**Comment by berni69** [comment] 2016-08-17 07:26
I'm seeing three components: "Node.js Tools", "Node.js Tools - Interactive Window", and "Node.js Tools - Profiling" under Extensions and Updates.

On the activity log there are some errors like:

```xml
  <entry>
    <record>446</record>
    <time>2016/08/17 07:09:30.320</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [NodejsPackage]Source: &apos;&apos; Description: El par&#x00E1;metro no es correcto. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;System.ArgumentException: El par&#x00E1;metro no es correcto. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)&#x000D;&#x000A;   at Microsoft.NodejsTools.NodejsPackage.GetNodejsLanguagePreferencesFromTypeScript(IVsTextManager4 textMgr)&#x000D;&#x000A;   at Microsoft.NodejsTools.NodejsPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{FE8A8C3D-328A-476D-99F9-2A24B75F8C7F}</guid>
    <hr>80070057 - E_INVALIDARG</hr>
  </entry>
  <entry>
    <record>447</record>
    <time>2016/08/17 07:09:30.331</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [NodejsPackage](null)</description>
    <guid>{FE8A8C3D-328A-476D-99F9-2A24B75F8C7F}</guid>
    <hr>80070057 - E_INVALIDARG</hr>
  </entry>
  <entry>
    <record>448</record>
    <time>2016/08/17 07:09:30.333</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [NodejsPackage]</description>
    <guid>{FE8A8C3D-328A-476D-99F9-2A24B75F8C7F}</guid>
    <hr>80070057 - E_INVALIDARG</hr>
  </entry>
```
And theese others, i'm not sure if they are related with this issue;

```xml
  <entry>
    <record>131</record>
    <time>2016/08/17 07:09:11.319</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
    <description>Still unable to load MEF component DLL: No se puede cargar el archivo o ensamblado &apos;Microsoft.TeamFoundation.Controls, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\VWEWJTSV.3VE\GitHub.TeamFoundation.15.dll</path>
  </entry>
  <entry>
    <record>132</record>
    <time>2016/08/17 07:09:11.321</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
    <description>Still unable to load MEF component DLL: No se puede cargar el archivo o ensamblado &apos;Microsoft.AspNet.Scaffolding.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\WINDOWS AZURE TOOLS\SERVICES\Microsoft.VisualStudio.WindowsAzure.Services.WebExtensions.dll</path>
  </entry>
  <entry>
    <record>133</record>
    <time>2016/08/17 07:09:11.323</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
    <description>Still unable to load MEF component DLL: No se puede cargar el archivo o ensamblado &apos;Microsoft.VisualStudio.Workspaces.Contracts, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\HHM4FHOK.ENN\TMLanguage.dll</path>
  </entry>

```

After run `devenv /setup /clearCache /allowDuringSetup`, the first time I tried to open the solution, VS throws me this error: 

``` The 'NodejsPAckage' package  did not load correctly.
....
Restarting visual studio could help resolve this issue. 
Continue to show this error message?```

After accept or deny this message, I can see the first error on the console. 

If I remove the folder ComponentModelCache I see not changes when I try to open the solution. 

Thaks for your help.
Regards.

**Comment by berni69** [comment] 2016-08-17 12:48
I tried this on a fresh install of VS2015 Comunity  Update 3 with the same results.

**Comment by mjbvz** [comment] 2016-08-17 18:08
Thanks.

Yes, it looks like the main NTVS package is failing to load. The specific error seems to [be on this line in `GetNodejsLanguagePreferencesFromTypeScript`](https://github.com/Microsoft/nodejstools/blob/b1c25881889353e5ab48a9c9be20d7285222be59/Nodejs/Product/Nodejs/NodejsPackage.cs#L259).

Do you have Typescript installed in Visual Studio? This is found under `Help -> About Visual Studio`. Typescript should be listed in the Installed Products. If it is installed, what version is listed?

We probably could handle this error more gracefully, so I will investigate to see if we can improve things with a code change, but I would really like to understand the root cause of the problem on your system too.

**Comment by berni69** [comment] 2016-08-18 07:08
Before you asked me I tried to install a new TypeScript package, but i have no success with the english version. After that I tried to install successfully an spanish version, But it doesn't appear in Help -> About Visual Studio.

Thats my VS package info:

```
Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA885
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA885
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA885
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20810.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40623.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40623.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40623.00
Profiling support for Python projects.

```

The package I tried to install was TypeScript_Dev14Full.exe (TypeScript Tools for Microsoft Visual Studio 2015 1.8.6.0).
I've downloaded the file from:  https://www.microsoft.com/es-es/download/confirmation.aspx?id=48593

Thanks for your help. 

Best regards,

**Comment by mjbvz** [comment] 2016-08-18 17:23
Yes, the missing Typescript looks like the root cause of the problem. I don't know why Typescript would not be installed, so my only other suggestions of what to try or investigate are pretty generic:

* Do you perhaps have multiple Visual Studio installations on the machine? Is VS installed in a non-standard location?
* Are there any errors or warnings about Typescript in `ActivityLog.xml`? If you could just upload the entire log, I can take a quick look as well.
* Try fully uninstalling Typescript with `Add or Remove Programs`. Then reinstall typescript again. I think you've already tried this, but it may be worth a shot.

I'm going to try quickly setting up a machine with this specific language configuration (8.1 with Spanish windows, english VS 2015) to make sure language is not the root cause.

Also, if NTVS just didn't throw an exception here, I think you may still have been able to use the old IntelliSense engine. I'll investigate to see if that is something we want to enable. We really want everyone using our new, typescript powered IntelliSense engine, so I'm not sure we want support scenarios where Typescript is not installed in VS. In either case, we could provide a better error message to users in this case.

**Comment by berni69** [comment] 2016-08-18 19:35
Hi Again,

I  only have one installation on my machine, It was installed in standard location.  Before you ask me I tried to add and remove the typescript package. 
Idon't see more errors with typescript, I have attached my activitylog.

[ActivityLog.xml.txt](https://github.com/Microsoft/nodejstools/files/425747/ActivityLog.xml.txt)


I agree with you, the message could be more descriptive. I'm trying to install typscript in VS but i'm not able to do it.

**Comment by berni69** [comment] 2016-08-19 07:58
I found a workarround to open the project:
* Uninstall typescript
* Install Typescript 2.0.0 Beta
* Reinstall Web Application tools for visual studio. 
After that, I can see TypeScript installed under `Help -> About Visual Studio` 

![captura2](https://cloud.githubusercontent.com/assets/1116133/17802917/646ac246-65f3-11e6-8273-60552dd952ee.PNG)

But when I open the project, a new message appears : 

`Could not find Typings package manager tool used for Intellisense`

**Comment by mjbvz** [comment] 2016-08-22 20:57
@berni69 The Typings tool is an internal npm package we use to power our modern IntelliSense. It looks like it is not being properly installed for some reason. Can you please try the following:

* Restart VS. Open an NTVS project. Can you copy and paste any messages you see in the `Output` window for Node.js. 
* Try going to `Tools -> Options` and then `Node.js Tools -> Npm` and hitting the `Clear Cache` button. Then reload the NTVS project. This will clear the typings tools and try to reinstall it.

Also, what versions of NPM and Node are you using?

Thanks.

**Comment by kevinvavelin** [comment] 2016-11-25 15:19
Hi there, I have the same issue, after multiple install and uninstall of typescript, I still don't get TypeScript in my "About Visual Studio" window. Can anyone tell me how we can install TypeScript in Visual Studio ? 

I use VS2015 enterprise edition update 3 (which have typescript installed by default :/ but impossible to create a project due to this issue)

**Comment by CharlesMoore** [comment] 2016-11-28 06:06
Just to chime in, I have this issue as well. Pretty much identical to the symptoms described above by @berni69 and then by @kevinvavelin . And just as Kevin describes, this makes it impossible for me to create a NodeJs project using TypeScript.

**Comment by paulvanbrenk** [comment] 2016-12-09 23:41
going to close this. If you have install issues with TypeScript, please open a bug in the [TypeScript repo](https://github.com/microsoft/typeScript/issues/)

**Closed by paulvanbrenk** 2016-12-09 23:41 UTC
Labels: crash-or-hang, project-system

**Comment by Devjossy** [comment] 2017-10-14 10:38
None of the suggestions above worked for me, any help would be appreciated... Thanks in anticipation

**Comment by kevinvavelin** [comment] 2017-10-14 12:45
I think it's not an issue related to TypeScript itself, but more with Visual Studio and NVTS.

**Comment by Devjossy** [comment] 2017-10-14 13:06
Do you have any suggestion regarding what should be done to correct the error, I tried reinstalling the latest version of NVTS for Visual Studio 2015, it;s working perfectly but no option for the Empress template with Bootstrap

**Comment by paulvanbrenk** [comment] 2017-10-16 17:26
@Devjossy One thing you can try in an admin devdeloper command prompt. 

`devenv /setup` this should reset VS and force it to re-discover templates.
