### ISSUE TITLE
2-22-2016 Dev Build MSI Corrupt / Invalid

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/nodejstools#714] opened 2016-02-27 13:12 UTC
![msisignaturecorrupt](https://cloud.githubusercontent.com/assets/80310/13373030/c2d5e728-dd10-11e5-8173-4ef0bab39c2c.PNG)
Dev build MSI's corrupt. At least IE is blocking me from download.

**Comment by mjbvz** [comment] 2016-02-29 18:30
Thank you for reporting this. It looks like all three of the 2/22 MSIs have this problem. 

I confirmed that the downloads do work as expected in Chrome, and you can also ignore the warning and  manually run the downloaded MSI through edge or IE, but this should be fixed. We're looking into it.

**Comment by mousetraps** [comment] 2016-03-01 07:10
Looks like something's up with our build server. I removed the dev build temporarily, and will look into this tomorrow.

**Comment by NoelAbrahams** [comment] 2016-03-01 09:37
Worked fine for me in Chrome.

**Closed** 2016-03-01 19:49 UTC
Labels: bug, installation

**Comment by mousetraps** [comment] 2016-03-01 21:01
Okay, just uploaded a new dev build!
https://github.com/Microsoft/nodejstools/releases

**Comment by rkavalap** [comment] 2016-03-01 21:50
@mousetraps  That was quick. Thanks will try out with the new changes.
