### ISSUE TITLE
function analysis fails in vs2015 update 2

### ISSUE THREAD

**Issue by ianaykh** [Microsoft/nodejstools#936] opened 2016-05-11 09:01 UTC
Node.js analysis fails during the code analysis. Intellisense doesn't work for even the current code.

**Comment by mjbvz** [comment] 2016-05-11 18:20
It's unclear exactly what is going wrong. Can you please provide:

* Visual Studio Version
* NTVS Version (both can be found under `Help -> About Visual Studio`)
* Intellisense Level
* Steps to reproduce the problem
* Expected behavior
* Actual Behavior

Thanks.

**Comment by ianaykh** [comment] 2016-05-11 19:06
VS version 14.0.25123.00 update 2
Microsoft Visual Studio Community 2015


Node.js Tools   1.1.40329.04
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.40329.04
Profiling support for Node.js projects.

Intellisense level - full intellisense and quick intellisense(gives error in both)

Steps to reproduce - Launching the app from the start page, the app loads (VS crashes most of the time I'm using nodejs tools)the blue status bar below says Node function analysis failed. 

Expected behaviour - node analysis has compeleted analysis of x functions in y time
Actual behaviour- node analysis has falied to analyse functions(has given ablove me the expected behavior output rarely)

**Comment by mjbvz** [comment] 2016-05-13 00:11
Thanks. A few more questions:

Does this happen for all projects or just one specifically? Does it happen for a new, blank project? Is there anything different about the project it is crashing in? If you can share the `package.json`, that may help with the investigation.

A few things to unblock yourself in the meantime:
* Enable diagnostics logging: `Tools -> Node.js Tools -> Diagnostics Info` and check `Enable Node.js Tools Live Diagnostics output pane`. This will print any debug error messages to the visual studio output window.
* Try deleting the `.ntvs_analysis.dat` file in your project folder.
* Upgrade to NTVS 1.2 Alpha and switching to ES6 Intellisense Preview. This is generally much more stable and performant. 
* Try disabling `Save To Disk` for Intellisense. This option is found under Options: `Text Editor -> Node.js -> Intellisense`.

**Comment by ianaykh** [comment] 2016-05-13 02:31
Now that I've tried yes it does happen for every other project. I've tried reinstalling both visual studio and nodejs tools but in vain. However I'll try your suggestions.Also , I would appreciate if you could give me an insight over the schedule for the future releases for NTVS 1.2

**Comment by mjbvz** [comment] 2016-05-13 19:17
Ok, it's interesting that this happens for every project. Did you see any error messages after enabling `Enable Node.js Tools Live Diagnostics output pane`? 

---

The NTSV 1.2 alpha is available for both VS 2015 (the current VS release) and for VS15 (the preview / next VS release). You can [download the latest releases here](https://github.com/Microsoft/nodejstools/releases/tag/v1.2.Alpha2).

The NTVS 1.2 builds are alphas, so expect some instability and bugs in the short term, but 1.2 significantly improves the overall reliability, stability, and experience of using Node in Visual Studio. NTVS 1.2 and its ES6 Preview Intellisense is the modern experience we are moving towards and we want as many people using it as possible.

As for scheduling, NTVS 1.2 will leverage some significant, new VS15 work, such as [Any Folder Projects](https://blogs.msdn.microsoft.com/visualstudio/2016/04/12/open-any-folder-with-visual-studio-15-preview/) and [lightweight installation](https://blogs.msdn.microsoft.com/vcblog/2016/04/01/lightweight-cpp-installation-in-vs-15/). Because of these dependencies, we have not committed to a final release date for NTSV 1.2 (or whatever we end up calling it) but should keep pushing out Alphas about once a month.

**Comment by mjbvz** [comment] 2016-06-23 00:38
Since my original comment, we've shuffled some things around. We just released [NTVS 1.2 beta](https://github.com/Microsoft/nodejstools/releases) and are targeting VS 2015 Update 3 for the RTM version of NTVS 1.2.

NTVS 1.2 brings a number of important performance improvements and features, and should just offer a much better experience all around. It's still a beta release, but I recommend downloading it and giving it a try. Please report any issues you run into and feel free to share general feedback too #1077 

For VS15, we plan to continue releasing dev builds along with alphas, but cannot release a final NTVS version until VS15 RTM. We're working hard to support many of the new platform enhancements the VS15 brings, but we plan to keep working on NTVS for both VS 2015 and VS15 for the immediate future.

**Closed by mjbvz** 2016-06-23 00:38 UTC
Labels: crash-or-hang, intellisense, need-more-info
