### ISSUE TITLE
Global packages not loading due to Microsoft.NodejsTools.Npm.PackageJsonException with npm dependency.

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#533] opened 2015-10-14 00:42 UTC
The root cause of this exception has been reported over at [npm/npm#9965 - Node 4.2.1 installs NPM with a invalid package.json for at least one dependency](https://github.com/npm/npm/issues/9965).

Because of that issue, I get the following error in VS2015 Pro with the 9-17-2015 Dev Build release of NTVS:

```
Error - Cannot load global packages.
System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JTokenWriter.AddValue(JValue value, JsonToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteNull()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEnd()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.Linq.JTokenWriter.Close()
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource.WrapExceptionAndRethrow(String fullPathToFile, Exception ex)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JTokenWriter.AddValue(JValue value, JsonToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteNull()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEnd()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.Linq.JTokenWriter.Close()
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource.WrapExceptionAndRethrow(String fullPathToFile, Exception ex)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules.AddModuleIfNotExists(IRootPackage parent, String moduleDir, Boolean showMissingDevOptionalSubPackages, Int32 depth, IDependency dependency)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModulesToDepth, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()<---
```

I am on Windows 10 Pro and I have used [nvm-windows](https://github.com/coreybutler/nvm-windows) to install Node v4.2.1 on this particular machine.

**Comment by waynebloss** [comment] 2015-10-14 00:44
I thought it was weird that NTVS descended into npm's dependencies - but of course I don't know how NTVS works internally. Weirder though was that some invalid JSON in one package.json file stopped up the whole process. I think it should continue if possible.

**Comment by waynebloss** [comment] 2015-10-14 02:16
After fixing the single invalid package.json file, everything loaded fine. They are also fixing the root issue over at npm.

**Comment by waynebloss** [comment] 2015-10-14 04:41
While reporting a different issue just now - after opening VS2015 I got "Error - Cannot load global packages." but with no other details and no stack trace.

**Comment by mousetraps** [comment] 2015-10-21 05:08
Have you tried our [latest dev build](https://github.com/Microsoft/nodejstools)? It includes a fix for #208, which sounds like the issue you're running into. I agree we should also try and gracefully fail, though, so let's keep this bug around.

**Comment by waynebloss** [comment] 2015-10-21 06:06
I am using the latest dev build as of today, but I did not yet recreate the offending condition to see if it's fixed. As soon as I do, I will give an update.

**Comment by sgireddy** [comment] 2015-11-11 18:02
This issue is not fixed, and the CPU spikes upto 30-40% and stays there until I stop VS. This is a blocking issue.

**Comment by mousetraps** [comment] 2015-11-12 00:29
Closing this as a duplicate of #208 

@sgireddy the high cpu usage sounds like a different issue, so please file a separate issue with more details about your project and dependencies you have installed, what build you're on, etc. so we can try to fix it.

**Closed by mousetraps** 2015-11-12 00:29 UTC
Labels: bug, code-intelligence, npm-integration
