### ISSUE TITLE
Meteor node process crashes on being attached by VS NTVS 1.1

### ISSUE THREAD

**Issue by rodrigorodriguez** [Microsoft/nodejstools#618] opened 2015-11-30 00:20 UTC
Using meteor debug, whenever the Visual Studio 2015 NTVS 1.1 (https://github.com/Microsoft/nodejstools) tries to attach to the Node debugger on port 5858 the meteor node process crashes. Here is the stack:

<pre>
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
  at errnoException (net.js:905:11)
  at Socket._write (net.js:646:26)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at Socket.Writable.write (_stream_writable.js:183:11)
  at Socket.write (net.js:616:40)
  at BackloggedStreamWriter.write (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\inspector.js:246:17)
  at Array.forEach (native)
  at Function._.each._.forEach (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
  at BackloggedStreamWriter.setTarget (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\inspector.js:265:9)
  at Server.self.interceptServer.net.createServer.on.self.interceptServer (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\inspector.js:92:23)
  at Server.emit (events.js:95:17)
  at TCP.onconnection (net.js:1192:8)

<pre>

**Comment by mousetraps** [comment] 2015-12-14 19:56
closing this as a duplicate of #510 - we haven't really focused on supporting meteor apps yet.

**Closed by mousetraps** 2015-12-14 19:56 UTC
Labels: feature

**Comment by mousetraps** [comment] 2015-12-14 19:57
Also since we haven't really dived into this much yet, maybe you have ideas - is there anything else for meteor apps you're looking for at this point? Or just make debugging work?

**Comment by inbaldoron** [comment] 2016-02-07 07:47
make debugging work will be awsome!
also codecompletion,  starting and stopping the server, attach to server and working with a remote server.
This would be a great feature for node tools, meteor is a powerful framework
