### ISSUE TITLE
NodeTools and VS, broken

### ISSUE THREAD

**Issue by drcmda** [Microsoft/nodejstools#1288] opened 2016-09-16 16:16 UTC
##### Expected Behavior

Press button. Build. Publish. Easy.
##### Actual Behavior

It takes ages. My computer is getting so hot i don't know if this can be healthy. Visual Studio eats up gigabytes of ram and going up. It seems to recycle telling me about a "Microsoft.NodejsTools.WebRole.dll" which i haven't included nor do i want to. 

```
------ Build started: Project: azure, Configuration: Release Any CPU ------
------ Publish started: Project: azure, Configuration: Release Any CPU ------
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
```

Before that it insists bloating up my project with typescript stuff, which i haven't requested, ignoring my repeated attempts to remove them. 

A simple build takes a while as well, but it's bearable. Initiating a publish then, for no reason, needs to build again, and this is were it really gets stuck. The same happens for package builds.

Since colleagues get similar issues something seems seriously broken to the point where making a simple publish to Azure takes up half a workday. Is there anything you can do?

- NTVS Version: 1.2
- Visual Studio Version: 2015 update 3
- Node.js Version: 6.6.0

**Comment by moncapitaine** [comment] 2016-09-16 16:48
Let me add: Intellisense and other stuff already switched off.

**Comment by mjbvz** [comment] 2016-09-16 19:58
Sorry to hear you are running into these problems. 

To help with the investigation, can you please go to `Help -> About Visual Studio` and use the `Copy Info` button to share all the information about your visual studio installation. I'd like to know which extensions you have installed and their the exact versions.

Then can you please provide a simple step by step repo for the publish problem? I'm specifically interested in what your NTVS project looks like and what you are trying to publish to Azure. Was the project created through the NTVS project templates or somehow else?

---

Separately, [here's more information about why NTVS downloads those typing's files](https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition). This is used to provide richer IntelliSense in VS2015, but it can be disabled entirely by going to `Tools -> Options` then `Text Editor -> Node.js -> IntelliSense` and deselecting `Automatically add IntelliSense typings folder to Node.js projects`. 

---

Also, what triggers the performance problems you are seeing? Just opening or editing an NTVS project? Attempting to publish? Does it happen for all projects or just this one? 

Thanks.

**Comment by drcmda** [comment] 2016-09-17 09:10
Here is the output you requested:
```
Microsoft Visual Studio Professional 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Professional

Visual Basic 2015   00322-40000-00000-AA078
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA078
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA078
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.6.00907.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.1   14.0.20622.0
Azure App Service Tools v2.9.1

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40518.2

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.34.0
TypeScript tools for Visual Studio
```

I made a barebones copy of the project here: https://github.com/awvinf/azurecopy
I removed the publish keys binaries which i can't publish. It basically relies on Node to serve a CAD system. It has two roles, a farm which starts CAD instances and can be scaled up and down and a public role which serves as a central hub, managing users and instances. Clients will connect to the public role.

We just want this to run on Azure. So we wrapped it in a solution, added a specific version of Node (6.6.0) in /assets/redist because the Azure default was outdated at the time. 

The issues are triggered by starting a publish. The IDE feels sluggish all the way but it starts to go reall bad when it builds. I tried to set the build output to detailed but when it starts recycling through the "Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll" thing it does not show anything, it just stays there for ever bringing the computer to its knees.

Thanks for all the help!

**Comment by paulvanbrenk** [comment] 2017-11-04 00:26
Closing as I can not reproduce and the linked project is no longer available.

**Closed by paulvanbrenk** 2017-11-04 00:26 UTC
Labels: need-more-info, performance
