### ISSUE TITLE
Forking an child process throws an eaddrinuse exception when in debug mode

### ISSUE THREAD

**Issue by mprattinger** [Microsoft/nodejstools#131] opened 2015-05-22 12:20 UTC
When running an nodejs app in debug mode and i want to fork an childprocess (child_process.fork(...)), i get an eaddrinuse exception.

I guess this happens because VS tries to attach the debugger to child process on the same port, which is currently in use by the main process.
![image](https://cloud.githubusercontent.com/assets/3177738/7770334/9dedf65e-008d-11e5-8f0d-ed56bc8af515.png)

**Comment by mousetraps** [comment] 2015-05-28 02:14
Did you try running ```node --debug app.js``` in the command line? If you get the same result, the issue is with the code or node itself.

**Comment by rg1220** [comment] 2015-06-19 16:15
For the sake of `need-more-info`, I ran into the exact same issue when forking. I also ran `node --debug app.js` from CMD and received the same EADDRINUSE exception. This is as simple as it gets:

**app.js**

    var fork = require('child_process').fork;
    var forked = fork('./fork.js');

    setTimeout(function () { 
        console.log('finished');
    }, 10000);

**fork.js**

    console.log("test");

**Comment by mprattinger** [comment] 2015-06-26 11:16
Hi,

i run the nodejs app from visual studio in debug mode. And when the run the forked child process i get the error.
regard Michael

**Comment by mousetraps** [comment] 2015-06-26 13:42
Still trying to understand. If this happens regardless of whether you are running ntvs... Is there a reason to believe this is ntvs-related?

**Comment by mousetraps** [comment] 2015-07-24 20:09
Closing this as external since it appears to be a node issue, but let me know if you think otherwise.

**Closed by mousetraps** 2015-07-24 20:09 UTC
Labels: debugging, need-more-info
