### ISSUE TITLE
Visual Studio Crashes on Opening

### ISSUE THREAD

**Issue by bmkleine** [Microsoft/nodejstools#73] opened 2015-04-21 22:41 UTC
I get 3 or 4 crashes when I try to open visual studio due to nodejs tools.  Event Viewer entry is below:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Microsoft.NodejsTools.Analysis.AnalysisUnit.AnalyzeWorker(Microsoft.NodejsTools.Analysis.Analyzer.DDG, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.Analyzer.DDG.Analyze(Microsoft.NodejsTools.Analysis.Deque`1<Microsoft.NodejsTools.Analysis.AnalysisUnit>, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.JsAnalyzer.AnalyzeQueuedEntries(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue+GroupAnalysis.Analyze(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue.Worker(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by mousetraps** [comment] 2015-04-22 21:00
Thanks for reporting this. We should fix the null ref, but would you mind also zipping up and sending us the project that this reproduces with so we can understand how this state came to be in the first place? If not the full project, the .ntvs_analysis.dat file will at least be helpful. Feel free to send it to ntvshelp@microsoft.com if you don't want to post here.

In the meantime, you can delete the .ntvs_analysis.dat file associated with your project and see if the problem is resolved when you reload your project (and the file gets recreated).

**Comment by miparnisari** [comment] 2015-05-13 14:44
I get the same error, VS 2013 Ultimate Update 4 crashses when opening the SLN.

Error:

The program devenv.exe version 12.0.31101.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: 2508
 Start Time: 01d08d88fec5dc8a
 Termination Time: 46
 Application Path: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
 Report Id: d398e69f-f97c-11e4-82d5-0050b65a27d1
 Faulting package full name: 
 Faulting package-relative application ID:

**Comment by miparnisari** [comment] 2015-05-14 17:11
Also, not sure if this is related, but the file size of `.ntvs_analysis` is 140 mb!!

**Comment by miparnisari** [comment] 2015-05-19 13:25
One more thing. I disabled ReSharper and installed the latest Dev version (https://github.com/Microsoft/nodejstools/releases/tag/v1.1.Dev-5.13.2015). At the time of writing it's still "Preparing the Solution..." :-1:

**Comment by miparnisari** [comment] 2015-05-22 14:49
I think I figured it out ... I disabled all my extensions and now it's loading fine. I can't say for sure but I think that the culprit is the Funnel extension (https://visualstudiogallery.msdn.microsoft.com/5396fa4a-d638-471b-ac3d-671ccd2ea369) which does a selective loading of the projects.

**Comment by mousetraps** [comment] 2015-07-06 11:14
This appears to be the same issue as #70, so closing this as a duplicate.

**Closed by mousetraps** 2015-07-06 11:14 UTC
