### ISSUE TITLE
Mocha tests discovered but do not seem to run

### ISSUE THREAD

**Issue by frauss** [Microsoft/nodejstools#683] opened 2016-02-11 19:47 UTC
I'm trying to move a Node.js project I created using WebStorm to Visual Studio and am having problems running Mocha unit tests.

When I try to 'Run all...' from the test explorer it seems build and run something but not my tests.

Here's the output I get:

```
------ Run test started ------
Processing: C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel contentFilter save single should create new content filter with the name 'Unit Test Filter'::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel contentFilter save multiple should find 5 content filters whose names start with 'Unit Test Filter'::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel contentFilter populate test create a test transform and test filter referring to it and populate it::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel endpoint save single should create new endpoint with the name 'Unit Test Endpoint'::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel endpoint save multiple should find 5 endpoints whose names start with 'Unit Test Endpoint'::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel contentRule save single should create new rule with the name 'Unit Test Rule::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel contentRule save multiple should find 5 rules whose names match the regex /Unit Test Rule Number \d+/'::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel contentRule populate test create a test rule and referenced filter and endpoints and populate it::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel transformation save single should create new transform with the name 'Unit Test Transformation::Mocha
  Creating TestCase:C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel transformation save multiple should find 5 rules whose names match the regex /Unit Test Transformation Number \d+/'::Mocha
Processing finished for framework of Mocha
========== Run test finished: 10 run (0:00:23.7025712) ==========
```

However, I receive none of the console output I would expect from my tests.

I imagine something is misconfigured but just not sure what.

Thanks,
Fred

**Comment by mousetraps** [comment] 2016-02-12 00:23
Is the test framework property set to mocha in file properties?
![image](https://cloud.githubusercontent.com/assets/762848/12995383/c68cd3e0-d0db-11e5-99e7-a45b574913f5.png)

**Comment by frauss** [comment] 2016-02-12 15:18
Yes.

[image: Inline image 1]

I see the tests in the test explorer:

[image: Inline image 2]

However when I try to run or debug them they don't seem to run and I'm not
seeing anything in the output indicating where the problem is.

Fred

**Comment by mousetraps** [comment] 2016-02-14 06:05
Thanks. What happens if you set a breakpoint on the first line of one of the tests, and right click > debug in test explorer? Does it run or hit the breakpoint? What if you add a console.log to the test? Does it show up in the Output after running the tests? (see screenshot below) Do you have a simple example that reproduces the issue?
![image](https://cloud.githubusercontent.com/assets/762848/13032177/b9877e3e-d29d-11e5-9ed0-5cbc60320f6a.png)

**Comment by frauss** [comment] 2016-02-14 22:50
No, it never hits the breakpoint. Here's the the results:

Test Name: keystoneModel contentFilter save single should create new
content filter with the name 'Unit Test Filter'
Test FullName: C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js::keystoneModel
contentFilter save single should create new content filter with the name
'Unit Test Filter'::Mocha
Test Source: C:\Sources\eAP\DigitalPlatforms\Syndication\Keystone\Node.js\KeystoneDMIngest\test\keystoneModel.Test.js
: line 0
Test Outcome: Failed
Test Duration: 0:00:01.8910134

Here's the Debug Output window:

The thread 'main thread' (0x1) has exited with code 0 (0x0).

The program '[1] node.exe @ tcp://localhost:65325/#ping=0' has exited with
code -1 (0xffffffff).

I never see a console window that indicates Node is running. Is there a way
to get more detailed output or another window I could check?

Fred

------ Run test started ------

========== Run test finished: 1 run (0:00:06.4980418) ==========

Here's the Debug Output window:

The thread 'main thread' (0x1) has exited with code 0 (0x0).

The program '[1] node.exe @ tcp://localhost:59895/#ping=0' has exited with
code -1 (0xffffffff).

**Comment by mousetraps** [comment] 2016-02-20 08:32
Does the same issue occur with the included mocha item templates?

**Comment by vickymittal** [comment] 2016-03-16 10:24
@mousetraps 
I encountered the same issue:

Steps:
1. Created a new Project, Node.js -> Blank Node.js Console Application.
2. In solution folder executed, npm install mocha
2. Under Solution, Add Item -> New Item -> JavaScript Mocha UnitTest file.
3. For UnitTest.js, changed Test Framework to Mocha
4. In Test Explorer, right clicked 'Test Suite 1 Test 1' -> Run Selected Tests, Test Passed.
5. In Test Explorer, right clicked 'Test Suite 1 Test 1' -> Debug Selected Tests, Test Failed.
6. Clicked on Output, got following screen:
![image](https://cloud.githubusercontent.com/assets/17675168/13809014/cc668946-eb8e-11e5-9902-735c26eb7bdd.png)
7. Output of Node.js Tools Live Diagnostics:
[Node.js Tools Live Diagnostics.txt](https://github.com/Microsoft/nodejstools/files/175706/Node.js.Tools.Live.Diagnostics.txt)

**Comment by vickymittal** [comment] 2016-03-16 16:00
@mousetraps The issue seems to be with Node.js 4.3.0, upgraded to 4.4, and it works now.

**Comment by frauss** [comment] 2016-03-16 16:49
Upgrading to 4.4 definitely fixed the issue. I had previously been running
4.2.6.

Not sure what the issue was but vickymittal thanks for the info!!

Fred

**Comment by vickymittal** [comment] 2016-03-17 14:59
@frauss, this was due to bug in nodejs (https://github.com/nodejs/node/issues/4440)

**Comment by mjbvz** [comment] 2016-06-22 20:38
Seems like this has a known resolution. Closing this issue.

**Closed by mjbvz** 2016-06-22 20:38 UTC
Labels: need-more-info, test-adapter
