### ISSUE TITLE
Any plan to release 1.3 for VS 2015 ?

### ISSUE THREAD

**Issue by fforjan** [Microsoft/nodejstools#1500] opened 2017-03-14 23:09 UTC
Dear NTVS team,

Our team is still going to use VS2015 for the next 6 months, any plan to have version 1.3 released for VS2015 ? It would be really helpful.

**Comment by billti** [comment] 2017-03-18 01:08
I just put a new release up at https://github.com/Microsoft/nodejstools/releases/tag/v1.3.Dev-03.06.2017 . We fixed a few bugs. Note you should also grab the latest TypeScript as mentioned. Let me know how this works for you.

We'll ship the final version for VS 2015 soon unless any new major issues are found.

**Comment by fforjan** [comment] 2017-03-18 07:57
Cool ! We've just updated to the latest TS 2.2.1 so it should be good. let me try :)

**Comment by SDP190** [comment] 2017-03-27 19:25
@fforjan are you actually using the NTVS v1.3.Dev-03.06.2017 mentioned above?
if yes, can you please tell me if you also have the same issue as I had posted here [https://github.com/Microsoft/nodejstools/issues/1510](url), thanks.

**Comment by fforjan** [comment] 2017-03-29 20:40
Let me switch to it, I was doing internal training for my team and didn't want to change my configuration.
I will do try it today if possible

**Comment by SDP190** [comment] 2017-03-29 21:51
Thanks for responding, btw I am also using the latest version of TypeScript as needed.
Since nobody complain but me, I wonder if it's a specific issue only occurs to me due to any bad configuration with VisualStudio/NTVS? (I ran VisualStudio Repair, and it did not fixed).

**Comment by paulvanbrenk** [comment] 2017-04-10 23:54
Closing this as it's not a bug ;)

**Closed by paulvanbrenk** 2017-04-10 23:54 UTC

**Comment by fforjan** [comment] 2017-04-11 13:48
@paulvanbrenk  what's  the process for such question if not here ?

**Comment by paulvanbrenk** [comment] 2017-04-11 16:47
@fforjan asking the question is great. Just closing this now as the question has been answered and there is no reason to leave it open.
