### ISSUE TITLE
Visual Studio 2015 Update 1 w/Node.js Tool 1.1 - Performance Warning & IDE Crashes

### ISSUE THREAD

**Issue by jwuliger** [Microsoft/nodejstools#663] opened 2016-01-14 15:02 UTC
Hello Node Team!

I need your help please.

I have been having serious IDE performance issues with any project that has to do with JavaScript. I have been looking for the root of the problem for the past couple of months to no avail.

**Symptoms:**

* Very "laggy" IDE experience. When I type something there is always a long delay before it is outputted to the screen.
* Random crashes all the time. I loose some work because of this if I am not always using "Ctrl + S"
* These symptoms happen like I said in any type of JavaScript project, so Node, Cordova, etc.

I do not have any issues/problems with a ASP.NET/C# projects. Now I am not sure if Node.js Tools is the problem but I just ran a "devenv.exe /log" and in the XML doc I have this entry:

```
  <entry>
    <record>228</record>
    <time>2016/01/14 14:21:49.046</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Performance warning: String load failed. Pkg:{29102E6C-34F2-4FF1-BA2F-C02ADE3846E8} (Node.js Tools - Interactive Window) LANG:0409 ID:200&#x000D;&#x000A;</description>
  </entry>
```

**My Workstation:**

* Windows 10 Enterprise
* Visual Studio 2015 Update 1 Enterprise
* Computer is very high end.

I was hoping someone could comment on the "String load failed" and at least maybe point me in the right direction on what to do.

I appreciate your time. Thanks!

**Comment by RobertSmart** [comment] 2016-01-20 11:16
I also have a high end computer running VS2015 and the UI locks up frequently. It seems to coincide with the status bar running node.js analysis and saving it to disk. What I don't get is why a new blank node.js project with 20 lines of code generates an .ntvs_analysis.dat file that is 110MB. it says the analysis runs in 20 milliseconds, so why is it locking the for noticiable amount of time (not that it should block the ui anyway).

**Comment by jwuliger** [comment] 2016-01-20 15:56
@RobertSmart Exactly! For me it is not just a Node project. It is also Cordova projects (Seems like anything that is JavaScript related). What I also found is that using the "HTML" editor is impossible. You try and type out a class name for example and 10 seconds later it outputs to the screen. The ONLY time I have not had performance issues id with a native .NET project and a website project. Those run smoothly. I have spent months trying to figure this out. Anything you google, you bet I have tried it! I LOVE Visual Studio. I have been using it all my career. It is really hard to switch Visual Studio Code so...well you can write code! I just hope some sort of solution comes soon.

**Comment by RobertSmart** [comment] 2016-01-20 16:35
I've started to run Atom shell and VS side by side as Atom Shell has much better handling for JSX. As long as you don't have the same file open in VS, it actually works quite well. you edit the code in Atom Shell, then debug it in visual studio. I would much rather they just fixed VS though! 

I have also had lots of problems with cordova projects too, but I noticed that there is an update for the cordova tools extension published today.

**Comment by mousetraps** [comment] 2016-01-20 22:59
@jwuliger - thanks for reporting this. I suspect multiple issues are piling up on you, so let's try and dive into them separately. 

> Very "laggy" IDE experience. When I type something there is always a long delay before it is outputted to the screen.

In which filetypes does the issue manifest itself? You mentioned HTML? And if it's also JS, then which project types does it include (or not include)? Language service & editor features are generally specific to filetype, except in the case of JS, where we have a proliferation of javascript engines mucking about so project-specific info would be helpful. 

> Random crashes all the time. I loose some work because of this if I am not always using "Ctrl + S"

When VS crashes, there should be a corresponding entry in the Windows Event log that often includes trace information. Any chance you could provide those entries? (it could be that you're running into multiple crashes too, so worth looking into that as well.)

@RobertSmart you mentioned that VS is locking up... is it crashing for you too? If so it would be great if you could also provide the corresponding Windows Event log entries. Regarding lockups, grabbing a dump while VS is hung would be helpful as well since the status bar isn't entirely reflective of everything that's actually going on under the covers.

**Comment by RobertSmart** [comment] 2016-01-20 23:17
It doesn't crash, but it does lock up for quite a while, enough to get the (not responding) showing in the title bar. So far this only seems to happen if i have javascript files open when working on a node.js project. How would i go about getting a dump for you? Thanks

**Comment by RobertSmart** [comment] 2016-01-22 12:20
I've done a dump using task manager when vs was locked up. How can I get it to you as it is over 1 gb in size after being compressed?

**Comment by mousetraps** [comment] 2016-01-22 20:35
@RobertSmart You can try uploading it to a fileshare service - either post here or send the link to me (sitani@microsoft.com). Alternatively, I believe that Task Manager only produces full memory minidumps, so if you want to get the size down further you can try Process Explorer.

**Comment by jbuedel** [comment] 2016-01-25 21:07
I believe I am experiencing this same problem. That is, Visual Studio 2015 becomes completely unresponsive. I've let it run for long periods of time and it never comes back, I ultimately kill it manually. There is always a message in the bottom left corner saying something like "Node tools analyzed 3 functions in 32ms" (something like that). 

It is very reproducible on my machine. Uninstalling Node.js Tools coincided with the problem going away. Based on that I'm quite sure it's this extension. Unfortunately I do not see anything helpful in the ActivityLog.xml or event log. I'd be happy to send any debugging info you might find helpful, just let me know what you need.

**Comment by mousetraps** [comment] 2016-01-25 22:20
@jbuedel - any chance you could share a minidump when the issue occurs, as requested above? Additionally could you provide some info about your computer, VS version, NTVS version, repro steps, etc.?

Thanks in advance!

**Comment by RobertSmart** [comment] 2016-01-25 22:26
I will also try and provide a mini dump tomorrow. Was out the office today.

**Comment by jwuliger** [comment] 2016-01-27 05:03
Hello!

My apologies for the late reply. I have collected as much information as I know how from the latest VS crash with a Node project.

I created a blank solution and then used "add an existing project". As soon as I added the project, VS started to hang/lock up and I could barely navigate the solution tree. When I tried to open a file VS crashed. I then collected the information I have attached to this post.

I do know that if I uninstall the Node Tools extension, I have no issues. Now I am thinking that this must be some sort of memory issue as the cause of the crash was a **System.OutOfMemoryException**

I am seeing other users report this exact problem, or very similar for the past couple months now. I really hope that this information can help you guys

Thanks for your time!

[App Crash Report.txt](https://github.com/Microsoft/nodejstools/files/106070/App.Crash.Report.txt)
[App Log Error 1.txt](https://github.com/Microsoft/nodejstools/files/106071/App.Log.Error.1.txt)
[App Log Error 2.txt](https://github.com/Microsoft/nodejstools/files/106072/App.Log.Error.2.txt)
[My Development Environment.txt](https://github.com/Microsoft/nodejstools/files/106074/My.Development.Environment.txt)
[All Installed Extensions.txt](https://github.com/Microsoft/nodejstools/files/106075/All.Installed.Extension.List.txt)

![systeminfo](https://cloud.githubusercontent.com/assets/14036569/12604230/ae41fabe-c487-11e5-8aef-09821a3fbc07.jpg)

**Comment by jbuedel** [comment] 2016-01-27 15:22
I'm not quite so convinced anymore that Node Js Tools is the root problem. So yesterday I reinstalled Node Js Tools (1.1.31117.00) and ran nearly all day without problems. I didn't do much, if any, js editing however. At the end of the day I started working on some javascript. After a short time Visual Studio got into a state where it would hang every 5 minutes or less. Restarting VS got past the hang, but it would soon happen again.

It seems to happen when intellisense is about to pop up.  Also, once it starts, it can happen while editing other, non javascript, files as well. I did get a dump from when VS was hung.  I will continue experimenting to see if I can zero in any further. 

[VSInfo.txt](https://github.com/Microsoft/nodejstools/files/106776/VSInfo.txt)
[Dump](https://dl.dropboxusercontent.com/u/7402014/devenv.7z)

**Comment by tedvanderveen** [comment] 2016-01-29 06:43
We are experiencing same issues when editing JS projects in VS. Hangs and crashes. Hope this can be improved soon.

**Comment by AronVanAmmers** [comment] 2016-02-02 13:04
We're experiencing similar issues with Node.js projects of several 100s of files, most of them written in TypeScript. CPU usage is almost always continuously 100% (of 1 CPU core) even when VS is idle, and on many occasions Visual Studio is barely usable.

I found that setting _Options > Text Editors > Node.js > IntelliSense > IntelliSense Level_ to **No IntelliSense** considerably reduces the symptoms or completely solves the issue. Surprisingly, IntelliSense in TypeScript files seems to work just fine, both when referring to our own files within this project and external references from `node_modules` (for which we have .d.ts definitions included using `tsd`).

**Comment by RobertSmart** [comment] 2016-02-03 11:56
I have had to turn off intellisense in this way in order to continue working, as vs was just grinding to a halt. The intellisense is set of off in the node.js settings, but it still seems to work fine, if not better than when it was switched on! Weird.

**Comment by mousetraps** [comment] 2016-02-04 19:09
@tedvanderveen @AronVanAmmers can you please share a dump, as requested above? It appears there are multiple root causes here, so I'm forking things off into separate threads so as not to overload this one and keep things more manageable.

**Comment by mousetraps** [comment] 2016-02-05 02:07
@jbuedel You mentioned that the UI was hanging. So I took a look at the main thread from the dump you provided, and it appears to incriminate EmojiVS. Could you try disabling that extension and see if that helps?

```
 	[Managed to Native Transition]	
>	mscorlib.dll!System.GC.Collect(int generation, System.GCCollectionMode mode, bool blocking, bool compacting)	Unknown
 	PresentationCore.dll!MS.Internal.MemoryPressure.ProcessAdd()	Unknown
 	PresentationCore.dll!MS.Internal.MemoryPressure.Add(long bytesAllocated)	Unknown
 	PresentationCore.dll!System.Windows.Media.SafeMILHandleMemoryPressure.SafeMILHandleMemoryPressure(long gcPressure)	Unknown
 	PresentationCore.dll!System.Windows.Media.SafeMILHandle.UpdateEstimatedSize(long estimatedSize)	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapFrameDecode.EnsureSource()	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapFrameDecode.BitmapFrameDecode(int frameNumber, System.Windows.Media.Imaging.BitmapCreateOptions createOptions, System.Windows.Media.Imaging.BitmapCacheOption cacheOption, System.Windows.Media.Imaging.BitmapDecoder decoder)	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(System.Windows.Media.Imaging.BitmapDecoder decoder, System.Collections.ObjectModel.ReadOnlyCollection<System.Windows.Media.Imaging.BitmapFrame> frames)	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapDecoder.Frames.get()	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()	Unknown
 	PresentationCore.dll!System.Windows.Media.Imaging.BitmapImage.EndInit()	Unknown
 	EmojiVS.dll!Emoji.Emoji.Bitmap()	Unknown
 	EmojiVS.dll!Emoji.Intellisense.EmojiCompletionSource.EmojiCompletion(Emoji.Emoji emoji)	Unknown
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Emoji.Emoji, Microsoft.VisualStudio.Language.Intellisense.Completion>.MoveNext()	Unknown
 	mscorlib.dll!System.Collections.Generic.List<Microsoft.VisualStudio.Language.Intellisense.Completion>.List(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Language.Intellisense.Completion> collection)	Unknown
 	System.Core.dll!System.Linq.Enumerable.ToList<Microsoft.VisualStudio.Language.Intellisense.Completion>(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Language.Intellisense.Completion> source)	Unknown
 	EmojiVS.dll!Emoji.Intellisense.EmojiCompletionSource.EmojiCompletionSource(Microsoft.VisualStudio.Text.ITextBuffer buffer, Emoji.IEmojiStore emojiStore)	Unknown
 	EmojiVS.dll!Emoji.Intellisense.EmojiCompletionSourceProvider.TryCreateCompletionSource(Microsoft.VisualStudio.Text.ITextBuffer textBuffer)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.CreateSourcesForBuffer.AnonymousMethod__0(Microsoft.VisualStudio.Language.Intellisense.ICompletionSourceProvider provider)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories<Microsoft.VisualStudio.Language.Intellisense.ICompletionSource, Microsoft.VisualStudio.Language.Intellisense.ICompletionSourceProvider, Microsoft.VisualStudio.Text.Utilities.IOrderableContentTypeMetadata>(System.Collections.Generic.IEnumerable<System.Lazy<Microsoft.VisualStudio.Language.Intellisense.ICompletionSourceProvider, Microsoft.VisualStudio.Text.Utilities.IOrderableContentTypeMetadata>> lazyFactories, System.Func<Microsoft.VisualStudio.Language.Intellisense.ICompletionSourceProvider, Microsoft.VisualStudio.Language.Intellisense.ICompletionSource> getter, Microsoft.VisualStudio.Utilities.IContentType dataContentType, object errorSource)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.CreateSourcesForBuffer(Microsoft.VisualStudio.Text.ITextBuffer buffer)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSourceCache.ViewSourceCache<Microsoft.VisualStudio.Language.Intellisense.ICompletionSource>.GetSources(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Text.ITextBuffer> buffers)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSourceCache.ViewSourceCache<Microsoft.VisualStudio.Language.Intellisense.ICompletionSource>.GetSources(Microsoft.VisualStudio.Language.Intellisense.IIntellisenseSession session)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSourceCache.GetSources<Microsoft.VisualStudio.Language.Intellisense.ICompletionSource>(Microsoft.VisualStudio.Language.Intellisense.IIntellisenseSession session, System.Func<Microsoft.VisualStudio.Text.ITextBuffer, System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Language.Intellisense.ICompletionSource>> sourceCreator)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.GetCompletionSources(Microsoft.VisualStudio.Language.Intellisense.IIntellisenseSession session)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.CompletionPresenterSession.PresentItems(Microsoft.VisualStudio.Text.ITrackingSpan triggerSpan, System.Collections.Generic.IList<Microsoft.CodeAnalysis.Completion.CompletionItem> completionItems, Microsoft.CodeAnalysis.Completion.CompletionItem selectedItem, Microsoft.CodeAnalysis.Completion.CompletionItem presetBuilder, bool suggestionMode, bool isSoftSelected)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.OnModelUpdated(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model modelOpt)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AbstractController<System.__Canon, System.__Canon, System.__Canon, System.__Canon>.Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.IController<System.__Canon>.OnModelUpdated(System.__Canon result)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation<Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model>.OnModelUpdated(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model result, bool updateController)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation<Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model>.ChainTaskAndNotifyControllerWhenFinished.AnonymousMethod__1(System.Threading.Tasks.Task[] tasks)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskFactory<System.Threading.Tasks.VoidTaskResult>.ContinueWhenAllImpl.AnonymousMethod__57_1(System.Threading.Tasks.Task<System.Threading.Tasks.Task[]> completedTasks, object state)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromResultTask<System.Threading.Tasks.Task[], System.Threading.Tasks.VoidTaskResult>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(object obj)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
```

**Comment by mousetraps** [comment] 2016-02-05 02:31
Okay, I've forked this thread off into separate issues (#678, #679, #680, #681) since it's clear there are multiple issues at play here. I'm going to close this thread now, but please file an issue separately with a dump as requested above if you are running into hangs, or with the corresponding Windows event log entries if you are running into crashes.

**Closed by mousetraps** 2016-02-05 02:31 UTC
Labels: bug, crash-or-hang, need-more-info

**Comment by jbuedel** [comment] 2016-02-05 14:58
I disabled EmojiVS and turned _Options > Text Editors > Node.js > IntelliSense > IntelliSense Level_ back to *Full*. I will let you know how it goes. Note that I had previously set the Intellisense to *No Intellisense* per the advice above and the problem completely went away.

**Comment by Nidonocu** [comment] 2016-03-24 15:44
Also had similar issue with VS 2015 locking up every five minutes when working on a Typescript Node.JS project and eventually crashing with an OutOfMemoryException.

Disabling Intellisense as described above worked as a work around.
