### ISSUE TITLE
Why does typings not generate my node/index.d.ts file?

### ISSUE THREAD

**Issue by Michael-Hamburger** [Microsoft/nodejstools#1145] opened 2016-07-18 20:20 UTC
Hi!

I am using TypeScript for about two weeks with VS 2015 Update 3 + nodejstools 1.2 RC.
I have a node.js project, which has some dependencies to other node-modules. Some of these node-modules are partly written in typescript. I am using git for the parent-project and all the node-modules.

The typings-folder is not added to the repository. Now I tried the project on another pc and I always got the error error MSB6006: "tsc.exe" exited with code 1. Strangely everything worked from the laptop! After some time I found out that the problem was missing *d.ts files inside of typings-folder. To be honest, I can't remember ever downloading these files in the first place. The folder is automatically created by Visual Studio and I simply used it.

The top of typings/globals/node/index.d.ts of says **// Generated by typings**. I simply copied this file to the other pc and it worked magically (yeah, 2 hours searching the net wasted...).

Can you explain, why _typings_ generated the file on my laptop but not on my desktop? Did I forgot to install something? Or is it a npm package which I need to install? Thanks!

**Comment by mjbvz** [comment] 2016-07-18 20:40
Here's some more information about automatic typings acquisition: https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition

The important point for your situation is that typings are only automatically acquired for Javascript projects, not Typescript projects. A typescript project is any project that includes any `*.ts` files, and we probably pick up a few false positives using this logic.

The underlying assumption is that Typescript users mange typings files themselves since the typings files are actually part of their projects, whereas with Javascript, we only download typings to power our IntelliSense. It seems like you may have started with a Javascript project, so `node/index.d.ts` was automatically downloaded, then if you then added any `*.ts` file, the project became a TypeScript project and the  `typings` folder would not be automatically recreated on other computers using that project

----

This sounds like the expected behavior, but we could improve the messaging here. Was  `MSB6006: "tsc.exe" exited with code 1` the only error message you saw? Are you still blocked by anything?

**Comment by Michael-Hamburger** [comment] 2016-07-19 06:11
Thanks for clarification. You say that typing files are part of the project. But the page you linked also says that typings-folder can be added to .gitignore.

Am I right that when using typings module and working typings-config that the definition files are downloaded automatically with npm install?

Yeah, when I build the project I got following error:

------ Build started: Project: node_paymentProcessor, Configuration: Debug Any CPU ------
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(242,5): error MSB6006: "tsc.exe" exited with code 1.
Done building project "node_paymentProcessor.njsproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

After searching I found https://github.com/Microsoft/TypeScript/issues/7557 this issue. But now I know that the problem was the missing definition files.

**Comment by mjbvz** [comment] 2016-07-19 18:39
That error is not that helpful... Does disabling `NoEmitOnError` as suggested in the linked Typescript issue improve the error messaging at all?

Regarding the typings files, it depends. In a JavaScript only project, the typings files are only used to power our IntelliSense. These typings files will be recreated for other NTVS users, so you can safely ignore the typings files, but there should not be any harm in including them either.

For Typescript projects, the typings are more part of the project itself because the Typescript compiler needs them. Typescript users are used to managing typings manually, and we did not want NTVS to interfere with these files. In that case, you should probably include the typings files in your project unless there is some other means for them to be acquired.

Does that make sense? Could the documentation be improved in some way to make this more clear?

**Comment by Michael-Hamburger** [comment] 2016-07-19 19:32
Your explanation makes (now) perfect senses. But I must say that I think it is a bit rigorous to say that NTVS should never download typings in Typescript projects. The usual stuff (node, angular, jquery, bluebird, request, ...) could be in a whitelist and downloaded by it. My ts-project now has typings module as a dependency and a typings.json to automatically download (after npm install as a postscript) typing definitions. That is exactly the same what NTVS does when the project is a js-project.

If a developer creates own definition files for his project he would add them to the repository. But I find it strange to make this manually when this can be automated.

You could copy and paste your typings passages in the link you provided. Or the typings-page in the wiki could be split up in two parts. One part for js-projects (automatic acquisition) and ts-projects (manually or typings package).

I am not so sure about the NoEmitOnError flag, I will test it tomorrow and get back to you. But I think the only thing that changed is that the exit code was 2 instead of 1.

Thanks for your help.

**Comment by mjbvz** [comment] 2016-07-27 18:00
I agree that we could considering exposing this as an option that users can enable for Typescript projects.

With the next release of Visual Studio however, we are moving off of downloading typings to power our IntelliSense. Typings acquisition was a workaround to enable better IntelliSense on VS2015. Our main concern  was messing up user's existing projects and since Typescript users were probably already managing their own `*.d.ts` files, we risk messing those up with automatic typings acquisition. 

Closing since the original question seems to have been answered. I'll make sure the wiki is up to date too. Please let me know if you have any other follow up questions about this.

Thanks.

**Closed by mjbvz** 2016-07-27 18:00 UTC
Labels: question
