### ISSUE TITLE
VS2015 RTM Exceptions on Project Load

### ISSUE THREAD

**Issue by atom0s** [Microsoft/nodejstools#308] opened 2015-07-21 19:45 UTC
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()<---
```
After loading a nodejs project these present in the output window. These are listed as output from 'Bower/npm'.

VS2015 RTM
NodeJS Tools 1.1 RC

**Comment by mousetraps** [comment] 2015-07-21 21:06
Thx for reporting this. Would you mind copying the full output from the output window? Does the npm node appear correctly in solution explorer? (for both global and local packages).

**Comment by atom0s** [comment] 2015-07-21 21:38
The above is the only output at all. Nothing else is in the log but that. 

The npm node is completely empty. It shows the default branches for 'dev', 'global', and 'optional'. But it does not show any of the packages at all.

**Comment by mousetraps** [comment] 2015-07-21 22:44
Gotcha Thx. Mind running the following cmds?
• npm ls --depth=0
• npm ls -g --depth=0

This may help us reproduce the issue

**Comment by atom0s** [comment] 2015-07-21 22:53
Is there a specific tool you want me to use to do this? Something within Visual Studio? Or from a normal powershell instance?

**Comment by mousetraps** [comment] 2015-07-21 22:54
No specific tool. Interactive window .npm cmd should work, or right click the project node and select "open in cmd prompt"

**Comment by atom0s** [comment] 2015-07-21 23:00
Command 1: http://pastebin.com/EgKwjngC
Command 2: http://pastebin.com/kCBmHutN

**Comment by mousetraps** [comment] 2015-07-21 23:07
Ahh looks like you flattened so the depth flag wasn't auper helpful in filtering things out. Can you send us your package.json as well? Thx!

**Comment by atom0s** [comment] 2015-07-21 23:19
Yeah we make use of flatten-packages since we kept running into MAX_PATH length issues.
Our package.json is:
http://pastebin.com/LRGvervC

**Comment by mousetraps** [comment] 2015-08-29 03:30
This will be fixed in our next release.

**Closed by mousetraps** 2015-08-29 03:30 UTC
Labels: bug, fun-size, in-progress, npm-integration
