### ISSUE TITLE
Update to 1.1 RC2

### ISSUE THREAD

**Issue by fromberg100** [Microsoft/nodejstools#417] opened 2015-09-04 16:10 UTC
Hi,

I just updated to NTVS 1.1 RC2 on VS2013 (Update 3).

Intellisense is not working at all.  

I uninstalled RC2 and reinstalled RC1 and intellisense works again.  Then I uninstalled RC1 and installed RC2 and intellisense does not work.

Is it perhaps I need to a clean uninstall?

Your help will be highly appreciated.

Thanks in advance and regards,
Fabian

**Comment by billti** [comment] 2015-09-05 01:28
Thanks. We found the cause for this. There was MEF import with the wrong type in the new snippets work. (Seems it still randomly works on some machines somehow (and on most VS2015 machines)). 

I've pushed a fix to master ( https://github.com/Microsoft/nodejstools/commit/ca2f319199d9b98a9a000021a6066a9208314133 ). I'm looking into some other issues and then will push another build out.

Sorry for the inconvenience, and thanks for reporting.

**Closed** 2015-09-08 20:17 UTC
