### ISSUE TITLE
Add telemetry to detect project characteristics that help drive performance improvements

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1115] opened 2016-06-29 21:44 UTC
This would include general characteristics like # of files in project, file size, etc. that would help us drive perf improvements in the right areas.

**Comment by mjbvz** [comment] 2016-07-08 01:02
After talking with the Typescript team and thinking more about the problem, we have decided to focus on using diagnostic window for performance investigations. There are so many factors involved in poor performance that we do not have a reliable way to detect this with telemetry alone in any actionable way.

Also, we do not want to collect any personal or organization identifying information in telemetry, which rules out uploading a list of installed node modules, file names, or anything similar. For users who have opted in to VS telemetry, we could likely collect generic project information, such as the number of files in a project. This sort of generic project telemetry would allow us get a better picture of what kinds of projects people are working with in the wild, so that we can better focus NTVS to address these use cases. 


If a user is seeing poor performance with NTVS, the most actionable way to investigate the root cause remains talking with them. We can request the output of the diagnostics window to help with this investigation. Using the diagnostics window allows users to see/edit what information they provide to us and makes it clear that this information is helpful for performance investigations.

**Comment by mjbvz** [comment] 2016-10-13 00:19
Closing. As detailed in the above comment, we ended up adding this information to the diagnostic window. Users having performance problems can send us this info to help us understand what may be going wrong.

**Closed by mjbvz** 2016-10-13 00:19 UTC
Labels: in-progress
