### ISSUE TITLE
ntvs 2015, debugging apps with large objects causes 100% cpu in node.exe

### ISSUE THREAD

**Issue by jasonswearingen** [Microsoft/nodejstools#558] opened 2015-10-20 22:07 UTC
I have a pretty complex node app,  debugging in 2013 is fast (mostly) but with 2015 performance tanks when my objects are massive.

the problem is when setting a breakpoint and stepping through my code.  every step or variable-hoverover causes node.exe to max out the cpu, for 15 sec or so usually  (sometimes, especially with big buffers it just doesn't recover at all).  It looks to have to do with some debugger-to-node roundtripping when there is a lot of memory used (when my user-defined objects are very large, multi-megabyte).   If I run the same code-path but with smallish objects the performance is acceptable.

after seeing the issue, I upgraded to the latest ntvs, typescript, and node.exe versions (as of today) and still having the issue on VS 2015.

The performance in vs2013 (update 5) is fine.

**Comment by mousetraps** [comment] 2015-11-16 05:52
Closing, as this appears to be a duplicate of #387, but please let us know if you believe otherwise, and we'll re-open.

**Comment by jasonswearingen** [comment] 2015-11-16 05:59
this is certainly related, though I mostly suffered when stepping through with the debugger, which is not described in the #387 ticket.    up to you if you feel they are similar enough issues to fold together!

**Comment by mousetraps** [comment] 2015-11-16 06:02
Ahh, yes - you're right. It also appears that your issue is more specific to VS 2015.

**Comment by mousetraps** [comment] 2015-11-16 06:03
And have you tried different versions of node to see if that has any impact?

**Comment by billti** [comment] 2015-11-16 17:50
Re the statement `when my objects are massive` - so I assume if you don't have massive objects performance is fine? Do you happen to have one of these massive objects displayed in the Watch / Locals window? Or a conditional breakpoint that uses an expression which touches one of these massive objects?

**Comment by jasonswearingen** [comment] 2015-11-16 18:16
@mousetraps Yes, you are right, I only have problems with VS2015.  I tried other versions of node (0.12.x x86 , and 4.2.1 x86 + x64)  and they all had identical issues.

@billti correct,  small objects have much better performance.  This is with nothing in watch/locals, and no conditional breakpoints.  

I can't provide a functional example, but here is the section of code where I reproed the issue:

```

					if (contentFilePath == null) {
						//empty promise
						var resolver = Promise.defer<Buffer>();
						contentPromise = resolver.promise;
						resolver.resolve(null);
					} else {
						contentPromise = nlib.fs.readFileAsync(contentFilePath);
					}

					Promise.join(userResponseFilePromise, contentPromise, (userResponseBuffer, contentBuffer) => {

				

						//construct final user-response object (including content)
						var userResponse = <ioDatatypes.IUserResponse>JSON.parse(userResponseBuffer.toString());

						//replaceNodes(userResponse.pageResponses[0], userResponse.pageResponses[0].pageRequest.suppressJson);

						var totalSize = 0;
						if (userResponseBuffer != null) {
							totalSize += userResponseBuffer.length
						}
						if (contentBuffer != null) {
							totalSize += contentBuffer.length
						}
						var data: string;
						var name: string;
						var encoding: string;
						var size: number;
						var isError = false;
						var statusCode = 200;
						if (contentBuffer != null) {

							switch (contentFileName) {

								case "content.jpeg":
									data = contentBuffer.toString("base64");
									name = contentFileName;
									encoding = "base64";
									size = data.length;
									break;
								case "content.png":
									data = contentBuffer.toString("base64");
									name = contentFileName;
									encoding = "base64";
									size = data.length;
									break;
								case "content.pdf":
									data = contentBuffer.toString("base64");
									name = contentFileName;
									encoding = "base64";
									size = data.length;
									break;
								case "content.html":
									data = contentBuffer.toString("utf8");
									name = contentFileName;
									encoding = "utf8";
									size = data.length;
									break;
								case "content.text":
									data = contentBuffer.toString("utf8");
									name = contentFileName;
									encoding = "utf8";
									size = data.length;
									break;
								case "content.json":
									data = contentBuffer.toString("utf8");
									name = contentFileName;
									encoding = "utf8";
									size = data.length;
									break;
								default:
									log.error("unknown content file name", contentFileName);
									isError = true;
							}
						} else {
							log.error("contentBuffer is null");
							isError = true;
						}
```

IIRC when the ```contentBuffer``` gets large,(like  15MB), the VS2015 ide is very slow on stepping through the ```(userResponseBuffer, contentBuffer) => {}``` method when debugging, with each step (F10) causing node.exe to max out a CPU for a long time.

Hope that helps.

**Comment by jasonswearingen** [comment] 2015-11-16 18:22
btw, in case this may be significant for reproducability,  my CPU is a i5, 4 core 3.6ghz,  and I have 32gb ram, and my os+programs+code is on a SSD,    my os is win10

**Comment by mousetraps** [comment] 2016-03-15 23:15
Looks like this is a duplicate of #387. Closing, but let us know if you think otherwise.

**Closed by mousetraps** 2016-03-15 23:15 UTC
Labels: bug, crash-or-hang, debugging, up-for-grabs
