### ISSUE TITLE
During opening solution 'Source array was not long enough.'

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#614] opened 2015-11-24 16:08 UTC
Full error:
```
error  : Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
```

**Comment by mousetraps** [comment] 2015-11-27 18:05
Can't reproduce, and there's no way we can do anything about this issue with so little information.

**Comment by kant2002** [comment] 2015-11-27 18:36
Unfortunately not, maybe this is not NTVS issue by iteself, VS 2015 is pretty buggy on itself. I post it here, just in case I could reproduce consistently.

Give me some time to try to reproduce, if I could not find any additional info, then don't mind. I just accept that current release of VS2015 is unreliable.

**Comment by billti** [comment] 2015-12-11 22:27
Closing with no further info. Will reopen if we can get more details on any issue here.

**Closed by billti** 2015-12-11 22:27 UTC
