### ISSUE TITLE
[lightweight-install] Unnecessary context menu clutter in Node.js workload

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1224] opened 2016-08-23 21:30 UTC
* [ ] [2] ISSUE 23: Manage Bower Packages appears in project menu
* [ ] [2] ISSUE 29: Add Connected Service… shouldn't appear in project list
* [ ] [2] ISSUE 30: Enable C# 6 / VB 14 shouldn't appear in project context menu
* [ ] [2] ISSUE 32: irrelevant options in test context menu
* [ ] [2] ISSUE 50: What are Android SDK breadcrumbs doing in Node workload?

<hr/>
![image](https://cloud.githubusercontent.com/assets/762848/17910474/e9c2b88e-693d-11e6-86a3-69faf0ac5f55.png)

![image](https://cloud.githubusercontent.com/assets/762848/17910502/ff8089b2-693d-11e6-8211-ecbdb598c17e.png)

![image](https://cloud.githubusercontent.com/assets/762848/17910506/07227d9c-693e-11e6-841c-d419ff0a6c97.png)

![image](https://cloud.githubusercontent.com/assets/762848/17910533/1aeeac9c-693e-11e6-8eb5-42575ed9e6f4.png)

**Comment by mjbvz** [comment] 2016-08-31 00:20
Most are now fixed or not regressions:

* [ ] ISSUE 23: Manage Bower Packages appears in project menu
  This is the only regression that seems to be vs15 specific. Not sure where it is coming from.

* [X] ISSUE 29: Add Connected Service… shouldn't appear in project list
  Fixed in latest builds

* [X]  ISSUE 30: Enable C# 6 / VB 14 shouldn't appear in project context menu
  Not VS15 specific

* [X] ISSUE 32: irrelevant options in test context menu
  Not VS15 specific

* [X] ISSUE 50: What are Android SDK breadcrumbs doing in Node workload?
  Fixed in latest builds as far as I can tell.

**Comment by mjbvz** [comment] 2016-09-30 23:59
Talked with web tools about the bower packages option. Seems to be by design on their side.

Closing for vs15.

**Closed by mjbvz** 2016-09-30 23:59 UTC
Labels: by-design
