### ISSUE TITLE
Why are Mocha tests each run as a separate suite?

### ISSUE THREAD

**Issue by ozyx** [Microsoft/nodejstools#1157] opened 2016-07-22 23:18 UTC
I have multiple Mocha test suites in the same NTVS project. When I run the tests in this project from Test Explorer by right clicking and selecting 'Run All Tests', each test is run as its own test suite. Is this by design or is there a way to control how VS runs the test? This same behavior occurs when running the tests as part of a TFS build.

Please let me know if you need me to elaborate on anything.
Thanks!

##### Expected Behavior 
before()
run test 1
run test 2
run test 3
after()
##### Actual Behavior 
before()
run test 1
after()
before()
run test 2
after()
before()
run test 3
after()

- NTVS Version: 1.1
- Visual Studio Version: 2013 Professional Update 5
- Node.js Version: 4.4.7

##### Steps to Reproduce
1. Create simple Mocha test suite with multiple tests and before() and after()
2. Right click on project in Test Explorer and select 'Run All Tests'
3. Observer that before() and after() are called for each test

**Comment by mjbvz** [comment] 2016-07-25 18:05
Thanks for the report. This is a known issue and being tracked by #518

The root cause is that we spin up a separate instance of node for each test, which causes the multiple calls to `before`, as well as major perf problems. Please let me know if you would like some pointers or any help investigating a fix.

Closing as dup of #518

**Closed by mjbvz** 2016-07-25 18:05 UTC
Labels: duplicate

**Comment by ozyx** [comment] 2016-07-25 20:23
Thank you for your response. 

Right now I'm working on some integration tests which require a certain order of events to work properly. Are there any known workarounds (aside from running tests from command-line) that might preserve the intended functionality of `before()`?

Cheers!
