### ISSUE TITLE
No parenthesis auto-complete w/ es6 intellisense

### ISSUE THREAD

**Issue by plushy1anthony999** [Microsoft/nodejstools#1209] opened 2016-08-16 21:43 UTC
##### Expected Behavior 
- When making a function declaration, after typing `function foo` I want to type `(` and have a pair of parenthesis be inserted, resulting in `function foo()`

##### Actual Behavior 
- Only a single `(` gets inserted, leaving me with `function foo(`

Visual Studio Setup:
- NTVS Version: 1.2 
- Visual Studio Version: Community 2015 w/ Update 3
- Node.js Version: 4.4.4
- Node es6 intellisense selected

I get a pair of parenthesis inserted when I tried nodejstools on VS2013, and also with VS2015 when I changed the node intellisense to es5. I thought about changing the intellisense mode because of here: [https://github.com/Microsoft/nodejstools/issues/1142](url) 

I had problems with auto brace completion as well, but the thread didn't talk about paranthesis, so I'm wondering if the issue also has to do with the typescript-powered es6 intellisense the editor uses?

**Comment by mjbvz** [comment] 2016-08-17 00:08
Yes, I believe you are correct that this is another manifestation of #1142. The [Typescript bug tracking this feature](https://github.com/Microsoft/TypeScript/issues/1484) mentions parens and other elements besides braces.

I'm following up with the Typescript team to verify this and see if there is any pre-release TS build for VS2015 that have this feature enabled.

**Comment by plushy1anthony999** [comment] 2016-08-17 01:04
> I'm following up with the Typescript team to verify this and see if there is any pre-release TS build for VS2015 that have this feature enabled.

Will this be possible without TS 2.0.1 or will the feature have to wait 'till after TS 2.0.1 comes out?

**Comment by mjbvz** [comment] 2016-08-18 16:56
@plushy1anthony999 I don't think so. To get brace completion today, you can try [NTVS on the VS15 preview](https://github.com/Microsoft/nodejstools/releases/tag/v1.2.Dev-7.24.2016). That should have brace completion enabled. Other than that, I'm still trying to work with the Typescript team to get this feature into VS2015 as soon as possible.

I'm closing this as a duplicate of #1142 so that everything is tracked in a single location. 

Thanks.

**Closed by mjbvz** 2016-08-18 16:56 UTC
Labels: editor
