### ISSUE TITLE
NPM not running on Azure Git deploy from VisualStudio.com

### ISSUE THREAD

**Issue by stevenlivz** [Microsoft/nodejstools#55] opened 2015-04-09 14:18 UTC
I hooked a new VS 2013 typescript/azure NodeJS project up an azure website to my git repo on VisualStudio.com and the deploy is fine and passes with no errors.

However, I do not check in node_modules (the IDE tells me not to) but npm is not run as part of the deployment so all the modules are missing. If i get a console on the server and run npm install, the modules are downloaded and everything works fine.

As I understand it, the presence of packages.json and the absence of node_modules means this should be automated. Is this a common new issue, or something unique to me or do i need to have something in the project to tell it to run npm on deploy?

**Comment by mousetraps** [comment] 2016-02-20 09:26
Closing as this issue is pretty old, and I can't reproduce.

**Closed by mousetraps** 2016-02-20 09:26 UTC
Labels: deployment, question
