### ISSUE TITLE
ES6 Intellisense in JSX

### ISSUE THREAD

**Issue by gborisl** [Microsoft/nodejstools#946] opened 2016-05-18 14:25 UTC
Getting red squiggles for ES6-style import statements in JSX files. I think that's causing the rest of the file to not be interpreted correctly by the text editor - red squiggles in markup, incorrect identation, etc.

VS2015 Update 2. NTVS 1.2 Alpha 2. ES6 Intellisense Preview enabled.

![image](https://cloud.githubusercontent.com/assets/12175855/15362199/6d74583e-1ce2-11e6-8389-9f8852978537.png)

**Comment by mjbvz** [comment] 2016-05-18 21:27
The root cause of this is that `*.jsx` is not associated with the node/typescript editor by default. Instead, it opens in the HTML editor or something similar.

To test this, I went to `Tools ->Options`, then `Text Editor -> File Extension`. Add an entry for `jsx` mapping to the Typescript editor (this is what powers our modern ES6 Intellisense experiance): 

![image](https://cloud.githubusercontent.com/assets/12821956/15375011/e04098ea-1d01-11e6-9747-fe850773f1a7.png)

But that doesn't actually work because the typescript editor prevents editing the `jsx` file. You have to change the extension to `tsx`. This gets basic syntax highlighting and syntax checking working at least. 

A few other observations:
* The `jsx` file is not added to the TypeScript virtual project. The `tsx` file is. We do track regular `js` files in the virtual project.
* It's not clear why the Typescript editor prevents you from even editing `jsx` files.
* Setting the `jsx` file extension to `Node.js` means you miss out on es6 intellisense and lots of other features. It also doesn't support react.

----

@billti, @jramsay 
Any thoughts on the problem as it relates to Typescript? Should Typescript register itself for jsx` files?

**Comment by paulvanbrenk** [comment] 2016-12-10 00:13
This should be fixed in Update 3, and NodeTools 1.2, with TypeScript 2.0+

**Closed by paulvanbrenk** 2016-12-10 00:13 UTC
Labels: external, intellisense
