### ISSUE TITLE
vs crash when try to edit file in views or public

### ISSUE THREAD

**Issue by yantrab** [Microsoft/nodejstools#848] opened 2016-04-12 14:51 UTC
Hi,

When i open my html file in public folder , there is a warning massage:

![image](https://cloud.githubusercontent.com/assets/12247800/14463846/5b16a134-00d5-11e6-89e7-0136582acb7f.png)

After  that , the vs crash and restart.
![image](https://cloud.githubusercontent.com/assets/12247800/14463994/bdc4d738-00d5-11e6-8de6-2e9940397a25.png)
OK!
I found out my problem, i added that files from by drop them from another project.
When i include them in project, the issue seem to be fixed.  

Maybe you should need to hide them.

**Comment by mjbvz** [comment] 2016-04-12 16:48
Looks like the problem is fixed?

From the description, it doesn't sound NTVS specific. Take a look at the end of `ActivityLog.xml` to if there are any hints and try the same steps with a non-NTVS project.

Closing since it seems to be resolved, plus this looks external. Please post a set of repo steps if you still believe it is an NTVS bug.

Thanks.

**Closed by mjbvz** 2016-04-12 16:48 UTC
Labels: external, need-more-info
