### ISSUE TITLE
package.json does not updates

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1616] opened 2017-07-11 04:28 UTC
##### Expected Behavior 
`package.json` open in the editor should provide prompt for reloading content

##### Actual Behavior 
Editor silently display previous content. Same for `package-lock.json`

- NTVS Version: 1.3.50417.1
- Visual Studio Version: 15.2
- Node.js Version: 8.1.3

##### Steps to Reproduce
1. Open `package.json` in the editor.
2. Run any npm command which modify `package.json`

**Comment by paulvanbrenk** [comment] 2017-07-11 21:24
Are you running the commands outside of VS, or are you using the NPM tools from the solution explorer?

**Comment by kant2002** [comment] 2017-07-12 03:34
I run commands outside VS.

**Comment by paulvanbrenk** [comment] 2017-07-14 21:59
I don't reproduce this in VS 2017 Update 3... can you check this option in VS.

![image](https://user-images.githubusercontent.com/5273975/28232339-001a0be8-68a5-11e7-9de7-cc26df2face6.png)

**Comment by kant2002** [comment] 2017-07-16 08:00
It was actually checked
![image](https://user-images.githubusercontent.com/4257079/28245709-cd43b6f2-6a2e-11e7-807e-a77917f1c016.png) and other project types does not have such issues.

**Comment by paulvanbrenk** [comment] 2017-07-21 17:43
Do other file types have the same issue?

**Comment by kant2002** [comment] 2017-07-27 11:29
No. I will try to create reproducible steps.

**Comment by paulvanbrenk** [comment] 2017-07-27 17:14
Thanks, can you also try with the preview[0], which hopefully has better behavior. They install Side By Side, so it won't break your existing installation.

[0]https://www.visualstudio.com/vs/preview/

**Comment by paulvanbrenk** [comment] 2017-09-01 18:30
Closing since I haven't been able to reproduce.

**Closed by paulvanbrenk** 2017-09-01 18:30 UTC
Labels: need-more-info
