### ISSUE TITLE
VS 2015 crashes due to exception in Microsoft.NodejsTools.Intellisense.TaskProvider.SendMessage(Microsoft.NodejsTools.Intellisense.WorkerMessage)

### ISSUE THREAD

**Issue by aguerot** [Microsoft/nodejstools#571] opened 2015-10-29 10:48 UTC
Visual Studio crashes with the error logged in the event viewer:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TryAddWithNoTimeValidation(System.__Canon, Int32, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.TaskProvider.SendMessage(Microsoft.NodejsTools.Intellisense.WorkerMessage)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.UpdateErrorsAndWarnings(Microsoft.NodejsTools.Analysis.IProjectEntry, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.NodejsTools.Parsing.CollectingErrorSink)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.ParseFile(Microsoft.NodejsTools.Analysis.IProjectEntry, System.String, System.IO.TextReader, Microsoft.NodejsTools.Analysis.IAnalysisCookie)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+<>c__DisplayClass4_0.<EnqueueFile>b__0()
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+<>c__DisplayClass5_0.<EnqueWorker>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

I can also provide a process dump of the crash if this helps.

Here is my env setup details:
Microsoft Visual Studio Enterprise 2015
Version 14.0.23103.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Enterprise
Architecture and Modeling Tools   00322-80000-00000-AA998
Microsoft Architecture and Modeling Tools
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
Visual Basic 2015   00322-80000-00000-AA998
Microsoft Visual Basic 2015
Visual C# 2015   00322-80000-00000-AA998
Microsoft Visual C# 2015
Visual C++ 2015   00322-80000-00000-AA998
Microsoft Visual C++ 2015
Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA998
Windows Phone SDK 8.0 - ENU
Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio
ASP.NET and Web Tools 2015 (Beta7)   14.0.60831.0
ASP.NET and Web Tools 2015 (Beta7)
ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/
Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.
GitFlow.VS.Extension   1.0
Visual Studio extension that integrates GitFlow
GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
JustDecompile Tools   1.0
Makes JustDecompile functionality available in VIsual Studio. Requires JustDecompile installation.
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools
Microsoft Code Digger   0.9
Microsoft Code Digger
Microsoft.Pex.VisualStudio   1.0
Pex
Node.js Tools   1.0.30428.03
Adds support for developing and debugging Node.js apps in Visual Studio
Node.js Tools - Profiling   1.0.30428.03
Profiling support for Node.js projects.
NodejsUwp   1.0
VS package for building Node.js UWP applications
NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools
Visual Studio Tools for Universal Windows Apps   14.0.23309.00 d14oob
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   3.11.1537.0 (a11147b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin.Android   5.1.7.12 (53fce3730830417896a42f365a5ba35f1ee58d9d)
Visual Studio plugin to enable development for Xamarin.Android.
Xamarin.Forms Intellisense   1.0
Provides intellisense for Xamarin.Forms in the XML editor.
Xamarin.iOS   9.0.1.0 (73db6324ad6864caae30bf4010c185598d262e69)
Visual Studio extension to enable development for Xamarin.iOS.
Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified
Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

Rgds,
Anthony

**Comment by billti** [comment] 2015-10-29 17:40
I see the NodeJS tools version is reporting as "1.0.30428.03". Can you try one of the recent 1.1 releases (see the releases page on this project) and see if the problem persists? We've fixed a ton of bugs since 1.0. (Indeed, part of the goal of 1.1 is to fully support VS2015, which it seems you are using).

**Comment by mousetraps** [comment] 2015-10-29 23:25
@billti is correct. In fact, this looks like a dupe of #392, so the fix should be available in our latest dev build. http://github.com/microsoft/nodejstools/releases

**Comment by mousetraps** [comment] 2015-11-01 16:14
Closing this as a duplicate. Please let us know and we'll reopen if this issue is still occurring for you with the latest release

**Closed** 2015-11-13 02:43 UTC
