### ISSUE TITLE
VS stuck "Waiting for parse to complete" on dust template in HTML editor

### ISSUE THREAD

**Issue by Ampakinetic** [Microsoft/nodejstools#592] opened 2015-11-14 02:11 UTC
I'm not sure if this is Node.JS tools specific, but Visual Studio gets stuck indefinitely intermittently when I've been working in another program (like a browser) and go back to editing a dust template in the HTML editor.  I have to use Task Manager, End Process to restart VS, there is nothing I can do to close it otherwise.

As soon as the editor gets focus, nothing works anymore (can't save, no cursor, can't scroll etc) however the VS IDE window still re-paints normally.  I'm pretty sure this didn't occur with older versions of Node Tools, so that's why I'm reporting this issue here.

Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Community

Node.js Tools   1.1.31104.02

**Comment by mousetraps** [comment] 2015-11-15 20:06
Thanks, looks like we'll need some more info then... would you mind sending us a dump of devenv.exe when the issue occurs? The quickest way to create a dump is by right clicking the process in Task Manager, and selecting "create dump file". Process explorer, procdump, etc. also work. You can then zip it up and upload it somewhere (post a link here or send it to ntvshelp at microsoft com)

**Comment by mousetraps** [comment] 2015-11-16 05:37
closing this as a duplicate of #570 - please follow up with us there!

**Closed by mousetraps** 2015-11-16 05:37 UTC
Labels: bug, crash-or-hang, need-more-info
