### ISSUE TITLE
Improve unit test loading / parsing error reporting (VS2013

### ISSUE THREAD

**Issue by danderson00** [Microsoft/nodejstools#134] opened 2015-05-23 00:06 UTC
A few scenarios where it is difficult to tell why unit tests are not being found and appearing in Test Explorer, with no reported reason why:

- no local mocha package - to repro, create a new console project, add the default mocha unit test template and select "Run All". No tests are loaded as mocha is not installed as a local module, no indication of this in the output window.

- error during parsing / executing test files (e.g. syntax error, non-existent module, etc). For example:

    var assert = require('assert');

    describe('Test Suite 1', function () {
        require('non-existent-module');

        it('Test 1', function() {
            assert.ok(true, "This shouldn't fail");
        })
    })

The test in this file is not loaded, and no errors are reported to the output window.

**Comment by mousetraps** [comment] 2015-05-28 01:59
dupe of #135

**Closed by mousetraps** 2015-05-28 01:59 UTC
Labels: duplicate
