### ISSUE TITLE
No tests were discovered when running test under vstest.console.exe

### ISSUE THREAD

**Issue by compulim** [Microsoft/nodejstools#852] opened 2016-04-12 20:25 UTC
When I run it under VS2015 Test Explorer, it works (list tests + run tests). But when running under `vstest.console.exe`, the TestDiscoverer is not able to pickup any tests listed in the `njsproj` file.

`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /ListTests:mytestproject.njsproj /UseVSIXExtensions:true`

It outputs:

```
Microsoft (R) Test Execution Command Line Tool Version 14.0.25123.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
```

It says nothing about the tests. In my other projects, `vstest.console.exe` is able to list out what tests I have in the test case.

Without able to discover any tests in the `njsproj` file, `vstest.console.exe` completed without running any tests. It generates no `TestResults` and outputs:

```
Microsoft (R) Test Execution Command Line Tool Version 14.0.25123.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
```

Tried to debug but `vstest.console.exe` does not has diagnostic log mode, so I can't see the debug log in the CS file.

The reason why I need it to run under `vstest.console.exe` is to able to put Node.js tests under Visual Studio Team Services (a.k.a. Visual Studio Online).

**Comment by mjbvz** [comment] 2016-04-12 21:39
Thanks for the report.

 I can confirm that running NTVS tests using `vstest.console.exe` does not work as expected, even when explicitly providing some extra hints and verifying that the NTVS test discoverers and test executors are loaded:

```
vstest.console.exe Example.njsproj /TestAdapterPath:"%LOCALAPPDATA%\14.0Exp\Extensions\Microsoft\Node.js Tools\1.2\"  /UseVsixExtensions:true
```

I believe the problem is that `vstest.console.exe` attempts to treat `Example.njsproj` as a dll during loading, which fails with a `BadImageFormatException`. This causes no tests to be found.

### Debugging The Test Adapter
I don't know too much about `vstest.console.exe` and this does not seem like one of our highest priorities at the moment, but anyone is free to take a look and submit a PR with a fix.

Here are some basic instructions for actually debugging the NTVS test adapter for this scenario (on VS 2015 with NTVS 1.2 Alpha):

1. [Get NTVS building locally](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions)
1. Open the `nodejstools` solution, and set launch target to `TestAdapter`
1. Open the properties for the `TestAdapter` project and go to the debug tab.
1. Use the following settings:

  * `Start External Program` = `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe`
  * `Command line Arguments` = `"C:\FULL_PATH_TO_EXAMPLE_PROJ\Example.njsproj" /TestAdapterPath:".\BuildOutput\Debug14.0\Binaries\TestAdapter\"`

Let me know if you run into any problems

**Comment by compulim** [comment] 2016-04-12 22:10
Finally figured out!

There is a line in the `njsproj`:
```
<VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">11.0</VisualStudioVersion>
```

Under `vstest.console.exe`, `VisualStudioVersion` is always set to 11.0. So it went to wrong place for `Microsoft.NodejsTools.targets`. My `vstest.console.exe` read 14.0.

If the try-finally block on TestDiscoverer is working properly, it will be much easier to debug. See https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/TestAdapter/TestDiscoverer.cs#L55. Despite the try-finally block should throw exception to upstream. The upstream kept its mouth shut. Maybe a bug on `vstest.console.exe` or by design.

Should we add a catch block and dump the exception by `logger.SendMessage(TestMessageLevel.Error, ex.Message);`?

BTW, I tried to put breakpoint and `Debugger.break()` to any code under `TestDiscoverer`. When running under `vstest.console.exe`, they  just skipped. But adding `logger.SendMessage` work, I am pretty sure my `TestAdapterPath` is correct.

Should we add a Wiki page too? I could give some help.

**Comment by mjbvz** [comment] 2016-04-12 23:23
Interesting findings, so are you able to run the test now?

We definitly want to bump up the `VisualStudioVersion`. There's a bug tracking removal of VS dev11 and dev12 support (#761). I'll take a look since this this work should probably go in to PR #847. Did you try running `vstest.console.exe` from a Visual Studio Command prompt? I believe that would have `VisualStudioVersion` set.

I'm also not seeing any breakpoints in the TestAdapter project being hit. This is strange since all the breakpoints seem to resolve (checked by enabling exception breaking for all com exceptions while debugging). I also do not see any exception being thrown in `TestDiscoverer.cs`, but adding the extra logging and rethrowing would not hurt. Do you want to submit a PR with that addition?

I agree we could use better documentation for the test explorer. Have you seen [this page](https://github.com/Microsoft/nodejstools/wiki/Test-Explorer) yet? Creating a section with some of your findings would be great and would help anyone running into similar problems. Let me know if you need any help looking into this.

Thanks.

**Comment by compulim** [comment] 2016-04-13 17:33
Yes, it's running okay now.

When I run `vstest.console.exe`, it defaulted `<VisualStudioVersion>` to `11.0`. `vstest.console.exe` logo said it is 14.0.25123.0, I think it's a bug on their side.

I am making a PR for adding a message + rethrow to `TestDiscoverer.cs`. And during the weekend, add a new section to the [Wiki page](https://github.com/Microsoft/nodejstools/wiki/Test-Explorer) to help others on enabling Mocha testing for VSTS.

**Comment by compulim** [comment] 2016-04-15 08:53
@mjbvz I have updated the [Wiki page](https://github.com/Microsoft/nodejstools/wiki/Test-Explorer). But since I have no access to `Microsoft/nodejstools.wiki`, I cannot add a new image, namely `VSTSConfiguringTestTask.png`. Can you commit it for me?

![vstsconfiguringtesttask](https://cloud.githubusercontent.com/assets/1622400/14556356/71666ba2-032a-11e6-8a70-2acbb96a3f58.png)

**Comment by mjbvz** [comment] 2016-04-15 19:54
Thank you for adding this! I've uploaded the image and the new sections look great.

Closing out this issue since the original problems all seem to have been resolved. Having this documentation should help out other people if they run into similar problems.

**Closed by mjbvz** 2016-04-15 19:54 UTC
Labels: enhancement, test-adapter, up-for-grabs
