### ISSUE TITLE
JSON error refreshing NPM package list

### ISSUE THREAD

**Issue by optimus-philbo** [Microsoft/nodejstools#1481] opened 2017-02-21 10:09 UTC
I have an issue when attempting to refresh the package list. I had been working on a Node.js project and decided to move this into Visual Studio. I downloaded the latest version of NTVS 1.2 and installed this. I then created a new empty node web project and attempted to refresh the packages. The following error occurs:

`Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\Phil\AppData\Local\Microsoft\Node.js Tools\NpmCache\bb5c8580-6d80-4b52-8728-26371022ab21\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Downloaded 1MB of the package list (67MB total)
Downloaded 2MB of the package list (67MB total)
Downloaded 3MB of the package list (67MB total)
Downloaded 4MB of the package list (67MB total)
Downloaded 5MB of the package list (67MB total)
Downloaded 6MB of the package list (67MB total)
Downloaded 7MB of the package list (67MB total)
Downloaded 8MB of the package list (67MB total)
Downloaded 9MB of the package list (67MB total)
Downloaded 10MB of the package list (67MB total)
Downloaded 11MB of the package list (67MB total)
Downloaded 12MB of the package list (67MB total)
Downloaded 13MB of the package list (67MB total)
Downloaded 14MB of the package list (67MB total)
Downloaded 15MB of the package list (67MB total)
Downloaded 16MB of the package list (67MB total)
Downloaded 17MB of the package list (67MB total)
Downloaded 18MB of the package list (67MB total)
Downloaded 19MB of the package list (67MB total)
Downloaded 20MB of the package list (67MB total)
Downloaded 21MB of the package list (67MB total)
Downloaded 22MB of the package list (67MB total)
Downloaded 23MB of the package list (67MB total)
Downloaded 24MB of the package list (67MB total)
Downloaded 25MB of the package list (67MB total)
Downloaded 26MB of the package list (67MB total)
Downloaded 27MB of the package list (67MB total)
Downloaded 28MB of the package list (67MB total)
Downloaded 29MB of the package list (67MB total)
Downloaded 30MB of the package list (67MB total)
Downloaded 31MB of the package list (67MB total)
Downloaded 32MB of the package list (67MB total)
Downloaded 33MB of the package list (67MB total)
Downloaded 34MB of the package list (67MB total)
Downloaded 35MB of the package list (67MB total)
Downloaded 36MB of the package list (67MB total)
Downloaded 37MB of the package list (67MB total)
Downloaded 38MB of the package list (67MB total)
Downloaded 39MB of the package list (67MB total)
Downloaded 40MB of the package list (67MB total)
Downloaded 41MB of the package list (67MB total)
Downloaded 42MB of the package list (67MB total)
Downloaded 43MB of the package list (67MB total)
Downloaded 44MB of the package list (67MB total)
Downloaded 45MB of the package list (67MB total)
Downloaded 46MB of the package list (67MB total)
Downloaded 47MB of the package list (67MB total)
Downloaded 48MB of the package list (67MB total)
Downloaded 49MB of the package list (67MB total)
Downloaded 50MB of the package list (67MB total)
Downloaded 51MB of the package list (67MB total)
Downloaded 52MB of the package list (67MB total)
Downloaded 53MB of the package list (67MB total)
Downloaded 54MB of the package list (67MB total)
Downloaded 55MB of the package list (67MB total)
Downloaded 56MB of the package list (67MB total)
Downloaded 57MB of the package list (67MB total)
Downloaded 58MB of the package list (67MB total)
Downloaded 59MB of the package list (67MB total)
Downloaded 60MB of the package list (67MB total)
Downloaded 61MB of the package list (67MB total)
Downloaded 62MB of the package list (67MB total)
Downloaded 63MB of the package list (67MB total)
Downloaded 64MB of the package list (67MB total)
Downloaded 65MB of the package list (67MB total)
Downloaded 66MB of the package list (67MB total)
Download complete - updating database
Reading 69689344 bytes from C:\Users\Phil\AppData\Local\Microsoft\Node.js Tools\NpmCache\bb5c8580-6d80-4b52-8728-26371022ab21\all_packages.json (21/02/2017 10:01:19)
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'flumt.repository.url', line 1, position 69631852.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackage(JsonTextReader jsonReader, NodeModuleBuilder builder)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\Phil\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting bb5c8580-6d80-4b52-8728-26371022ab21
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'flumt.repository.url', line 1, position 69631852.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackage(JsonTextReader jsonReader, NodeModuleBuilder builder)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()
`

I have also tried with the latest DEV build (2016-11-02) and the same issue occurs.
I have tried cleaning the NPM cache.
I have tried manually deleting the cache folder at C:\Users\<user>\AppData\Local\Microsoft\Node.js Tools

- NTVS Version: 1.3.41102.01
- Visual Studio Version: 14.0.25431.01 Update 3
- Node.js Version:  6.9.4

**Comment by billti** [comment] 2017-02-23 22:58
Hmmm.... I wonder if that is related to this: http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint .  I'll look into it.

**Comment by HolisticDeveloper** [comment] 2017-02-24 16:12
I'm also hitting this on a new install of NTVS 1.2 on VS 2015 Update 3, although it's choking on a different part of the string:

```
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'node-earthlive.bugs', line 1, position 149712506.
```

This makes the npm UI in VS unusable, although I can still use npm at the command line.

**Comment by billti** [comment] 2017-02-24 18:48
I just tried and see the issue also. It's possible some recent package authors are putting stuff in their package.json that is causing it to choke (we've fixed issues here before). I'll need to debug it to figure out what exactly. Thanks for raising.

**Comment by billti** [comment] 2017-02-24 22:32
It looks like NPM is actually returning a truncated package, and thus the JSON is malformed. (It also explains why folks are seeing this fail at different points, depending on the contents of the registry as it changes over time and where the download is getting truncated).

I thought it was a bit suspect when I saw it saying it was downloading 67MB total, as its close to a couple hundred MB now.

If you look at the registry file downloaded ("%LOCALAPPDATA%\Microsoft\Node.js Tools\NpmCache\all_packages.json") you'll probably observe that the file contents just stop abruptly.

Assuming this isn't an issue on our end (and it shouldn't be as the code didn't change, it just stopped working), I'll need to ping the NPM folks to see what is going on.

**Comment by thinkOfaNumber** [comment] 2017-03-09 04:29
Is this related to [Microsoft/nodejstools/issues/99](https://github.com/Microsoft/nodejstools/issues/99)?

**Comment by HolisticDeveloper** [comment] 2017-03-21 21:49
FWIW it seems to be working now.

**Comment by billti** [comment] 2017-03-23 01:07
Great! Yeah, it just worked for me too. Looks like NPM fixed it on there end. Closing.

**Closed by billti** 2017-03-23 01:07 UTC
Labels: bug

**Comment by vivekindo85** [comment] 2017-03-29 19:15
I am trying to load NPM package on vs13 and nodetool 1.1 getting empty all_packages.json not able to install any packages.

**Comment by chadwackerman** [comment] 2017-05-08 14:08
@billti it's doing it again. But I'm sure your internal tests already alerted you to that... right?

**Comment by billti** [comment] 2017-05-08 18:20
Doesn't matter whether our tests spot it or not... not a lot we can do if the issue is on the NPM end.

FWIW: We have a pull request in progress to remove the dependency on this API. https://github.com/Microsoft/nodejstools/pull/1501

**Comment by chadwackerman** [comment] 2017-05-09 00:02
Don't close the bug until you ship the fix.

**Comment by spevilgenius** [comment] 2017-06-15 08:54
Started happening to me this morning! Same error. Was a fix ever made on NPM end?

**Comment by billti** [comment] 2017-06-20 17:13
I don't believe NPM fixed it, or plans to. We merged in a fix to use the new NPM API (https://github.com/Microsoft/nodejstools/pull/1558). This will be shipping in future releases of VS 2017 (where NTVS is included in the product).
