### ISSUE TITLE
Add support for refactor rename

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#167] opened 2015-06-03 19:33 UTC
We lost this when we migrated away from JSLS

**Comment by zam6ak** [comment] 2015-06-18 16:37
this would be **very** useful +1
Any ETA on this feature?

**Comment by mjbvz** [comment] 2016-09-09 22:39
Closing as duplicate of #193 , which itself has been closed as currently out of scope for the NTVS project. We would likely try to leverage Typescript to implement this functionality in the future.

**Closed by mjbvz** 2016-09-09 22:39 UTC
Labels: editor, feature, up-for-grabs
