### ISSUE TITLE
Should provide some indication to the user that typings are bing downloaded

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1017] opened 2016-06-12 01:02 UTC
Otherwise the project opens up, IntelliSense doesn't work immediately, and it's unclear what's going on.

**Comment by mjbvz** [comment] 2016-06-13 18:55
I believe this a duplicate of the feature we were targeting with #797.

However, we only start to acquire typings after NPM install completes and the node_modules folder settles down, so it still may be unclear why there is no intellisense if a user starts interacting with a project right away.

**Closed by mjbvz** 2016-06-13 18:55 UTC
Labels: duplicate, enhancement
