### ISSUE TITLE
vs 2015 "project / properties / ts build / redirect js output to dir" does not work

### ISSUE THREAD

**Issue by kevinpas** [Microsoft/nodejstools#322] opened 2015-07-27 01:16 UTC
vs 13 works but vs 15 does not.

See branch "AddVS15" of https://github.com/kevinpas/Klib6

Then go to the tools folder: https://github.com/kevinpas/Klib6/tree/AddVS15/Tools

There are two folders there, one for vs 13 and one for vs 15

The vs 13 solution works using the output folder.

The vs 15 solution works but does not use the output folder.

**Comment by NoelAbrahams** [comment] 2015-07-27 08:27
There is a bug in `compile-on-save` for TypeScript projects in VS. Are you referring to that? In any case this doesn't seem to be an NTVS issue.

**Comment by kevinpas** [comment] 2015-07-27 22:34
Voted wrong location

**Comment by kevinpas** [comment] 2015-07-29 22:11
Sorry for the fickleness but I think this is the "currently" best location for this.

When I run the following from the command prompt my output shows up in the expected place:  tsc -module commonjs -t ES5 -outDir ../../Output NameValue.ts

When I try to do that in vs 2015 the output remains in the default location.  vs 2013 puts the output where I want.

**Comment by mousetraps** [comment] 2015-07-30 01:58
Does this happen for all ts projects or just node+TS projects?

**Comment by BigDataSamuli** [comment] 2015-08-20 09:31
I have the same issue, it happens with all newly created node+TS projects but not with the "HTML Application with Typescript"-project.

I have some older node+TS projects originally created with VS2013 and for those the redirect output option still works on VS2015. I have VS2015 Pro and NTVS 1.1 RC.

**Comment by billti** [comment] 2015-08-20 18:44
Per the above, there were some TypeScript issues in 1.5.4 that should be fixed in 1.6 (e.g. https://github.com/Microsoft/TypeScript/issues/4350 ). Once you have the TypeScript fixes, please reopen this issue if you are still seeing problems.

**Comment by kevinpas** [comment] 2015-08-20 23:20
Doesn't seem to work.  I closed vs 2015, installed the latest tsc.  Nothing shows up in the desired output folder. But output gets dropped in the source folder.

tsc  -v  --> message TS6029: Version 1.6.0-dev.20150820

**Comment by andrewpatto** [comment] 2015-08-28 05:49
I think I'm seeing the same behaviour. Started with blank console node+TS project - irrespective of the settings in the Typescript Build property panel for the project, output js seems to always get compiled as per file in source folder.

I am trying to get "combine javascript out into file" to work but I am presuming it is the same bug as kevinpas ("redirect output into directory" is also not working for me)

NTVS 1.1, vs2015 pro

**Comment by andrewpatto** [comment] 2015-08-28 06:03
I don't think the Typescript settings are being used at all.. this is an out of the box node express app.

Cranked the msbuild detail level up - the tsc command line being run as part of the build seems to bear no relationship to property panel.

![tscbug](https://cloud.githubusercontent.com/assets/1973827/9540122/13ebaed4-4d9e-11e5-8d6e-4296b8588dfd.JPG)

**Comment by andrewpatto** [comment] 2015-08-28 06:14
In contrast - NTVS 1.0 and vs2013

![tscworks](https://cloud.githubusercontent.com/assets/1973827/9540238/c8d4764a-4d9f-11e5-84fd-c2a027916d81.JPG)

**Comment by andrewpatto** [comment] 2015-08-28 06:23
Investigating some more - the issue seems to be an overly specific PropertyGroup condition in the .njsproj file.

    
      <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Any CPU'">
        <TypeScriptTarget>ES6</TypeScriptTarget>
    ...
        <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
        <TypeScriptOutFile>dss-core.js</TypeScriptOutFile>
      </PropertyGroup>


if changed to

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">

then the settings start appearing the command line.

So at least that is a temporary work around. I'm not enough across the build systems to know why 'Any CPU' on a typescript project causes this issue..

**Comment by mousetraps** [comment] 2015-09-16 19:05
Thanks for investigating - I an also reproduce the issue, so we'll look into this.

**Comment by mousetraps** [comment] 2015-09-28 05:39
Hi all, I made some configuration changes to my machine - in particular I updated to the latest version of typescript, and a slightly later build of VS (I was on a pre-release build from a few days before RTM), and this bug no longer reproduces for me when creating a new project.

So closing this as no-repro and external for now, but it would be helpful if people could verify that taking the latest updates to VS and TS solve the issue. 

If it continues to be a problem, then we can patch it up, but the fix is a little hacky and I'd prefer not to include it if it turns out to be unnecessary.
https://github.com/mousetraps/nodejstools/commit/d9a6190079c9cd0f8f0c7c0ffaffb2b3df13eda4

Regarding the property group specification, that is because the platform should be "AnyCPU", not "Any CPU". Unfortunately there is no good way for us to fix the previous projects automatically - so manually modifying the project property is the way to go here.

**Closed by mousetraps** 2015-09-28 05:39 UTC
Labels: bug, in-progress, typescript
