### ISSUE TITLE
Error when hover mouse over code

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#276] opened 2015-07-12 03:47 UTC
I run debug bits and that's why I found this error probably.
Take a look at following code
```
router.get('/', function (req, res) {
    res.json({ title: 'Express' }<<BEGIN>>)<<END>>;
});
```

When hovering over `)` between `<<BEGIN>>` and `<<END>>` blocks, then exception occurs. You should mouse over from the right side where `;` character is present, otherwise value for `{ title: 'Express' }` would be displayed.

```
Failed to find object literal value
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateObjectLiteral(ExpressionEvaluator ee, Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression[] astNodeList)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node)
   at Microsoft.NodejsTools.Analysis.ModuleAnalysis.GetValuesByIndex(String exprText, Int32 index)
   at Microsoft.NodejsTools.Intellisense.ExpressionAnalysis.get_Values()
   at Microsoft.NodejsTools.Intellisense.QuickInfoSource.AugmentQuickInfoWorker(ExpressionAnaly......
```

**Comment by kant2002** [comment] 2015-07-13 04:16
Please advice how to start debugging. Running from the debugger is not practical, since `Microsoft.NodejsTools.Intellisense.ExpressionAnalysis.get_Values` called very often and very often not related to my issue.

i need start from this point because since error in `Analyzer.ExpressionEvaluator.EvaluateObjectLiteral` looks trivial and means that we have corrupted(?) analyzer state. The evaluator try to find object literal `{title: 'Expess'}` in the GlobalEnvironment and fails to do that. When I inspect data in the `GlobalEnvironment` looks like that object contains some object literal which corresponds to `{title: 'Expess'}`, but I don't yet understand how whole thing works, so need help and little guidance in that area.

**Comment by kant2002** [comment] 2015-07-14 03:35
Other way how I could debug that is possible something like in the issue #106. 

1. Add test to the DebuggerTests.cs file
2. Add file to the Nodejs\Tests\TestData\DebuggerProject\ with JS snippet above.

**Comment by kant2002** [comment] 2015-07-14 03:45
Or maybe `Nodejs\Tests\AnalysisTests\AnalysisTests.cs` good fit too.

**Comment by kant2002** [comment] 2015-07-18 05:23
@mousetraps or somebody else, could suggest how should I debug this error? Do I work in right direction, or other set of tests better suited for this?

**Comment by kant2002** [comment] 2015-08-11 12:09
Friendly ping

**Comment by billti** [comment] 2015-08-21 18:18
Only on debug bits. Moving out to future milestone unless we see this impacting releases.

**Comment by kant2002** [comment] 2015-10-08 16:30
Seems that this issue causes freezing in the Release bits too. At least very often when I hover over areas with large count of `{` NTVS is freezing. Could not 100% sure say that this is the related to this issue, but on first glance seems related.
@billti and @mousetraps please take a look.

**Comment by kant2002** [comment] 2015-12-17 14:45
When I add following code
```
var x = function (req, res) {   
    var data = {};
}
```

When VS start producing issues in Debug.
But also on empty project I also start notice that ntvs_analysis.dat start eating space Just by closing and reopening solution it grow from 2Mb to 53Mb. Maybe this is related to erron in analysis, but maybe not.

**Comment by mjbvz** [comment] 2016-03-29 20:16
Simple repo file for the original issue:

```js
({ });
```

This does not seem to effect ES6 Preview.

Root cause is that the node we get in `EvaluateObjectLiteral` is not the same object as the one stored in our analysis set dictionary. They have the same properties and are functionally equivalent as far as I can tell, but return different hash values. This causes the lookup to fail, throwing the assertion.

**Comment by mjbvz** [comment] 2016-03-29 20:34
Actually never mind, the `EncodeSpan` of the two nodes are slightly different, but their other properties are the same.

Additionally, if you get rid of the parens, there does not seem to be any problem:

```
var a = { x: 2 };
```

That seems like one possible root cause.

**Comment by kant2002** [comment] 2016-04-04 08:14
From what I understand, is that expression evaluator confuses when inside `()`, I seen similar issues which related to expression evaluation in different places. If ES6 Preview does not affected, should I care about this issue? In the couple next days I will definitely take a look at 1.2 Alpha and if automatic TSD acquisition does not break my project I will move to 'ES6 Preview' settings. Also if I have time I will take a look at simpler repro case, maybe i could fix that.

**Comment by mousetraps** [comment] 2016-04-05 06:10
@kant2002 we'll be taking bug fixes on the ES5 intellisense experience, but will be focusing most of our efforts on the new ES6 Preview going forward.

**Comment by mjbvz** [comment] 2016-06-23 00:19
Closing this since, as Sara said, we are really focusing on our modern ES6 IntelliSense engine going forward.  Also, after a quick investigation, the fix appears to be non-trivial.

Try upgrading to [NTVS 1.2 Beta](https://github.com/Microsoft/nodejstools/releases) to use the new ES6 IntelliSense and please report any issues you run into or share any feedback on the new IntelliSense experience. Thanks.

**Closed by mjbvz** 2016-06-23 00:19 UTC
Labels: bug, code-intelligence, up-for-grabs
