### ISSUE TITLE
Missing colors and tooltip for internal imported modules 

### ISSUE THREAD

**Issue by lostfields** [Microsoft/nodejstools#1135] opened 2016-07-08 10:21 UTC
##### Expected Behavior 
Correct colors and Intellisense with mouse over for imported modules included in the project
##### Actual Behavior 
Missing colors and Intellisense with mouse over.

- NTVS Version: 1.2.40627.01
- Visual Studio Version: 14.0.25421.03 Update 3
- Node.js Version: 6.2.2

##### Steps to Reproduce
1. Using outdir for compiling if that's important
2. Create a file called "imyclass.ts" and export a interface named "IMyClass":
`export interface IMyClass { id: number }`
3. Create a file called "myclass.ts" and included the interface with: 
`import { IMyClass } from './imyclass';`
4. Write a new class:
`class MyClass implements IMyClass { constructor(public id) { }; }`
5. The tooltip for IMyClass says "import IMyClass" and the color is white (or black in light mode). The expected color is light green and tooltip "interface IMyClass".

**Comment by mjbvz** [comment] 2016-07-08 18:34
Thanks for the detailed report.  I can confirm the problem.

This does not seem NTVS specific, and I believe the root cause is something with Typescript. @billti @paulvanbrenk is this a known issue?

Interestingly, this form seems to work just fine:

```js
import * as m from './imyclass';

class MyClass implements m.IMyClass { constructor(public id) { }; }
```

![image](https://cloud.githubusercontent.com/assets/12821956/16697675/b07f626e-44ff-11e6-98ff-53aa3b45201c.png)

**Comment by paulvanbrenk** [comment] 2016-07-08 18:37
@mhegazy do you know if this is indeed a known issue.. I seem to remember there was a reason for this.

**Comment by mhegazy** [comment] 2016-07-08 20:00
We currently do not colorize aliases by their target. so aliases are always black. Issue https://github.com/Microsoft/TypeScript/issues/2890 tracks coloring them correctly.

**Comment by mjbvz** [comment] 2016-07-08 20:30
@paulvanbrenk and @mhegazy thank you for the quick follow up. I'm going to close this issue on the NTVS side since there's already a Typescript bug tracking this.

**Closed by mjbvz** 2016-07-08 20:30 UTC
Labels: external
