### ISSUE TITLE
Will not install with Visual Studio 15 Preview 4

### ISSUE THREAD

**Issue by MarkDRichards** [Microsoft/nodejstools#1238] opened 2016-08-30 13:51 UTC
Will not install with Visual Studio 15 Preview 4

##### Actual Behavior 
Gives an error that Visual Studio 15 must be installed.

- NTVS Version:  Dev Build From 7/24/2016
- Visual Studio Version:   15 Preview 4
- Node.js Version: v4.4.7

##### Steps to Reproduce
1. Install Visual Studio 15 Preview 4
2. Try to install NTVS

**Comment by mjbvz** [comment] 2016-08-30 18:22
Thank you for reporting this. This error is not entirely unexpected, and we are still figuring out how best to ship dev builds for VS15.

Starting with VS15 Preview 4, NTVS is shipping in the `Node.js workload` as a modern vsix extension. I don't think we want to use our msi installer going foward, but also do not know what the best way is to distribute manually installed extensions in this brace new world. I'll investigate further.

Until then, I've added a note [to the release](https://github.com/Microsoft/nodejstools/releases/tag/v1.2.Dev-7.24.2016) to explain the best way to try out NTVS in VS15 Preview 4.

**Comment by mjbvz** [comment] 2016-09-30 23:57
Closing as by design. It seems like shipping the in the VS15 preview is out best story currently. The latest dev release no longer includes a VS15 msi, and explains how to pick up the latest bits using VS15 preview.

**Closed by mjbvz** 2016-09-30 23:57 UTC
Labels: by-design, installation
