### ISSUE TITLE
Console application halts at end of the last line

### ISSUE THREAD

**Issue by mayankdedhia** [Microsoft/nodejstools#89] opened 2015-04-30 04:06 UTC
Currently in my project when the whole code completes execution the console doesn't closes and I can view the output of it, but when same code is executed on other machines at the code completion the console closes so output couldn't be visible. I don't know what the behavior should be from out of this two, but I believe it should be consistent across systems.

At all systems the versions are -
- Node - **v0.12.0**
- VS  - **2013 Express**

**Comment by mousetraps** [comment] 2015-05-01 03:23
Agreed. This didn't used to happen, and it also looks like this issue only occurs when the debugger is attached, so maybe something has changed in V8 APIs recently.

**Comment by mayankdedhia** [comment] 2015-05-04 09:20
Is there a way to get consistent behavior across systems?

**Comment by mousetraps** [comment] 2015-05-04 09:24
Yes, by fixing the bug ;-) or calling process.end

Other issues are taking priority on our end at the moment, but feel free to play around with the code in thd meantime.

**Comment by mousetraps** [comment] 2015-06-09 19:54
Investigating this now - are you sure you're running the same version of node on both systems? I see consistent experiences across systems using the same version of node.

**Comment by mayankdedhia** [comment] 2015-06-10 10:13
Now I don't have access to both the systems which I had checked earlier. So I've checked with the other available systems and I'm getting inconsistent experiences across systems with different version of node.

**Comment by mousetraps** [comment] 2015-06-17 07:37
Narrowed this down to an issue with recent versions of Node (after 0.10.36)... the debug process is not terminating properly, and we're not picking up any information that would let us hack around the issue by terminating the process some other way. 

See the following issues for more detail:
https://github.com/joyent/node/issues/25358
https://github.com/nodejs/io.js/issues/1788

Unfortunately this is also causing a bunch of test failures, so we'll have to look into disabling some of our debugging tests for the time being.

Marking this as external, but not closing so we can make sure to revisit it when everything is working and the issue is fixed in Node itself.

For the time being, if you want a "consistent" experience, your best bet is to turn on **Wait for input when process exits abnormally** and **Wait for input when process exits normally** in **Options** > **Node.js Tools**, and you can use Ctrl+C to close the window and end your debugging session.

**Comment by mayankdedhia** [comment] 2015-06-17 07:46
Thanks for the in depth analysis. I'll try the work around you suggested.

**Comment by paulvanbrenk** [comment] 2017-11-14 21:07
Node 8 and later now only closes when you stop debugging... though not as flexible it's at least consistent.

**Closed by paulvanbrenk** 2017-11-14 21:07 UTC
Labels: bug, debugging, external
